### ISSUE TITLE
Voting on comments

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/steemit.com#1000]
Voting a comment isn't raising the comment in the trending comment page?

When a I voted a comment before the comment moved up immediately, did that change?

**Comment by roadscape** [comment]
Sorts are now performed on (SBD) payout rather than rshares. So it's possible that smaller votes which do not budge the payout by $0.01 or more will not bump a post. We should fall back to using rshares or raw vote count when comparing two posts with equal payout amounts.

**Comment by FreeBornAngel** [comment]
Thanks for the explanation!

**Comment by pfunks** [comment]
I've noticed that post-payout, the comments that had votes but basically got rounded to 0 aren't sorted by previous payout rshares. I believe the idea to keep comment sorting by previous payout has already been implemented.

 Is this a necessary performance tradeoff, or would it be possible to sort comments post-payout by rshares as well?

**Comment by roadscape** [comment]
I've implemented a fix where sort comparison falls back to rshares when the SBD payout amounts are equal
