### ISSUE TITLE
"tags" tag make a dead-link from outside Steemit.com

### ISSUE THREAD

**Issue by KrNel** [steemit/steemit.com#1005]
Hello, please add a filter for the word "tags" when creating a post. It currently doesn't stop a post from being made. The result? The link is only accessible from within steemit, such as my Blog page. Copy and paste it into a browser as URL, and it is a "not exist" steemit page.

https://steemit.com/tags/@krnel/do-you-want-to-see-all-the-tags-on-steemit-here-you-go

Correcting this will avoid users in the future having a dead post from outside steemit. 

Thank you for the continued work on steemit. Peace.

**Comment by sneak** [comment]
"Doc, it hurts when I do that!"
