### ISSUE TITLE
Suggestion:  when downvoting, the voting power is depleted with the stake percent of the member, not with a fixed number

### ISSUE THREAD

**Issue by dragosroua** [steemit/steemit.com#1009]
Example: Someone has 90% voting power remained and can move 10% of the reward pool. When he downvotes a post, his voting power is depleted with 9%, at 81%. For the next downvote, his voting power will be depleted with 8.1% and so on.

Rationale and potential benefits in this article:

https://steemit.com/steemit/@dragosroua/a-proposal-for-solving-flagging-downvotes-and-spam-management-on-steemit

**Comment by roadscape** [comment]
Upvotes and downvotes already deplete voting power by a ratio, not a fixed number.
