### ISSUE TITLE
account exceeded maximum allowed bandwidth per vesting share error

### ISSUE THREAD

**Issue by cryptomental** [steemit/steemit.com#101]
As described on https://steemit.com/steemit/@cryptomental/where-should-we-report-issues-with-steemit-com-account-exceeded-maximum-allowed-bandwidth-per-vesting-share

```
(account_vshares * max_virtual_bandwidth) > (account_average_bandwidth * total_vshares): account exceeded maximum allowed bandwidth per vesting share account_vshares: 20509961725 account_average_bandwidth: 3668842644 max_virtual_bandwidth: 62540677012346197 total_vesting_shares: ${total_vesting_shares}
```

**Comment by roadscape** [comment]
alifton's response in the thread is accurate:

> It has to do with posting velocity and isn't a bug to the best of my knowledge. It's designed to stethrottle too many replies being posted in a short period of time. I hit it yesterday as well while replying back and forth a lot in a comment thread during a discussion.

> If you just wait a minute or so and post your reply again you should be fine.

As you collect rewards over time, your throughput will increase.
