### ISSUE TITLE
Registration NOT work

### ISSUE THREAD

**Issue by dacom-dark-sun** [steemit/steemit.com#1020]
When i try to register, i have error like that: 
`Unfortunately, we don't yet have support to receive SMS from your carrier, please try again later.`

We have tried numbers from Russia and from Switzerland, result is same.

**Comment by valzav** [comment]
Switzerland numbers (+41) should work. Russian and Ukraine numbers are temporarily not supported - we've seen a lot of abuse coming from those countries. We are looking for ways to enable them.
