### ISSUE TITLE
Russia Blocked Phone Number - How long until people can register?

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steemit.com#1022]
I have a lot of people from Ukraine and Russia that wants to join the network. When should we expect the block of their phone number to be open again?

**Comment by valzav** [comment]
First we need to figure out how we can prevent faucet's abuse. Implementing invitations might be a good to way to tackle this issue.

**Comment by RenaudGagne** [comment]
True. Invitations could also be an amazing way to grow the user base. Kind of like Pinterest did: 
https://steemit.com/steem-marketing/@cryptoctopus/growth-hacking-we-can-learn-from-pinterest
