### ISSUE TITLE
User's blog, posts do not display more than 20 entries

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steemit.com#103]
See for example [this user report](https://steemit.com/steemit/@piedpiper/my-steemit-blog-is-very-misleading-now).  `get_state()` only returns 20 items, paginated display needs some other API call (likely `get_discussions_by_author_before_date()`).

Tangentially related to #93.

**Comment by jcalfee** [comment]
This was a paging bug.  Comments were being included in the limit.  So a post with lots of comments could trick the paging into thinking it was done.  This will be fixed on the next deploy.
