### ISSUE TITLE
Clicking on resteemer or poster username in a resteemed post fails to load their user page

### ISSUE THREAD

**Issue by pfunks** [steemit/steemit.com#1030]
Tested in both Firefox and Chrome, when clicking on a username in a post that you are seeing because it's been resteemed (either on a feed page or on a user page), it fails to load the user's page. The header (showing the username in the upper left) and URLbar update but the content does not.

Here I clicked @katharsisdrill's name:

![image](https://cloud.githubusercontent.com/assets/22420130/22145168/d6c4f9d8-dec5-11e6-8b9a-3b8067a43f81.png)

And clicking @fishingvideos does the same:

![image](https://cloud.githubusercontent.com/assets/22420130/22145238/19efd0c0-dec6-11e6-9731-5ac91fecab78.png)

**Comment by roadscape** [comment]
Same issue as #1029
