### ISSUE TITLE
Votes older than 30 days are not loading in local Steemit.com instance

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#1034]
In my local Steemit.com instance, it is not loading votes that are older than the 30 day threshold. I have tried completely uninstalling and reinstalling steemit.com (including the MySQL database), and it did not fix the issue.

Note - this is not causing any actual issues for me (so it is not a high priority), but I wanted to report it in case it is an issue with the project when it is built from scratch.

Here is a screen shot of a set of posts from the actual Steemit.com website:
![image](https://cloud.githubusercontent.com/assets/20735105/22156464/f3d91652-def8-11e6-896c-2f56a9f69d4e.png)

Here is the same set of posts from my local instance (note the number of votes in the posts older than 30 days)
![image](https://cloud.githubusercontent.com/assets/20735105/22156432/cd726252-def8-11e6-98af-983e9d8bb3a6.png)

**Comment by roadscape** [comment]
To fix this, you will need to compile steemd with `-DCLEAR_VOTES=OFF` passed to cmake.
