### ISSUE TITLE
Some images not loading because of 400 (Bad Request) / 502 (Bad Gateway)

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steemit.com#1045]
Since moving image hosting from `img1.steemit.com` to `steemitimages.com` some of images are not loading properly.

At least in such nested case as this one:
`https://steemitimages.com/256x512/https://img1.steemit.com/0x0/http://puu.sh/pfuhF/280727a862.png`

Original url 'http://puu.sh/pfuhF/280727a862.png' loads properly
next proxy `https://img1.steemit.com/0x0/http://puu.sh/pfuhF/280727a862.png`
returns `502 Bad Gateway`
and current `400 Bad Request`
with: `{"error":"Supported image formats are: gif, jpeg, and png"}`

Rewriting above url to `https://steemitimages.com/256x512/http://puu.sh/pfuhF/280727a862.png` works as expected.

**Comment by jredbeard** [comment]
A redirect for img, img0, and img1.steemit.com has been put in place and effectively resolves this issue for now.
