### ISSUE TITLE
Imgur images are broken again

### ISSUE THREAD

**Issue by abitmore** [steemit/steemit.com#1046]
See https://steemit.com/garden/@alohaoy/missing-my-garden for example.

**Comment by Gandalf-the-Grey** [comment]
After removing `https://steemitimages.com/0x0/` prefix from image url to get original from imgur, there is  same result, so it looks like imgur / user related issue (i.e either imgur or user removed those images)

**Comment by abitmore** [comment]
Looks like it's the case.. but not all images have been removed from `steemitimages.com`, for example [this image](https://steemitimages.com/0x0/http://i.imgur.com/IMM4uOi.png) in [this post](https://steemit.com/health/@alohaoy/starting-out-in-natural-medicine-part-1-learning-the-lingo) is still there, but [the thumbnail](https://steemitimages.com/256x512/http://i.imgur.com/IMM4uOi.png) showing in [the list](https://steemit.com/@alohaoy) is broken.

**Comment by abitmore** [comment]
Response from the author ([link](https://steemit.com/garden/@alohaoy/missing-my-garden#@alohaoy/re-abit-re-alohaoy-missing-my-garden-20170123t203915900z)):
>Something happened to my Imgur account...I lost over 650 images. I have started using Supload for future posts but I don't know how I can fix the previous posts that are all messed up now.

I hope the new Steemit image hosting service will come sooner.

**Comment by jcalfee** [comment]
Looks like justin found the originals and uploaded them..

**Comment by jcalfee** [comment]
well .. most of them .. still a few missing

**Comment by alohaoy** [comment]
Thank you so much for fixing this issue! I really had no clue what to do about it. I don't know if my imgur was hacked or what happened...really appreciate the fix!!

**Comment by jredbeard** [comment]
Your welcome - I'm sorry imgur dumped your pictures. Glad we still had them for you. :)
