### ISSUE TITLE
Cannot read property 'name' of undefined in ExtractMeta.js:64

### ISSUE THREAD

**Issue by valzav** [steemit/steemit.com#1058]
Looks like it happens when account is not found, e.g. https://steemit.com/@bitcoinmagazine

**Comment by mcifani** [comment]
Odd.  The ExtractMeta should only trigger when the onchain call is successful(UniversalRender) resulting in a 200 status.  Curious..Is our latest code on prod?

**Comment by valzav** [comment]
yes latest code on production

**Comment by mcifani** [comment]
This was upated in PR https://github.com/steemit/steemit.com/pull/1060 - Closing issue since it's now resolved.
