### ISSUE TITLE
Post not showing up...

### ISSUE THREAD

**Issue by ClamBaker** [steemit/steemit.com#106]
Hail. Hope all is well. Love the platform.

It's @klye here reporting a bug with my girlfriends account @xcynosure regarding a post that isn't showing up in her profile. Her first post still clearly shows at https://steemit.com/@xcynosure but her second post located: https://steemit.com/verification/@xcynosure/re-verification-and-why-my-and-possibly-your-verification-sucked doesn't show up there..

Any ideas on what is causing this? I did see a flag on it from a troll but didn't think it would affect its visibility.

**Comment by svk31** [comment]
Yes, I'm afraid this is caused by the filter that removes replies from that list of posts, all replies start with `re-` as does this post. I've since improved the filter as others have reported this issue, so in the next release this post will show up again.
