### ISSUE TITLE
Registering and publishing as a legal entity?

### ISSUE THREAD

**Issue by SkubicaMirko** [steemit/steemit.com#1062]
I would like to ask a couple of questions regarding registering as a legal entity.
We are a collective working in the Association for promoting human potential and creativity - Prism. We run a project in which we create content together. We write articles about artists.  Authors of the article are not the individuals. Is it possible to register as an Association Prism? We would like to publish our original content. Is it in accordance with your policy and the guidelines?

**Comment by roadscape** [comment]
Absolutely! Anyone can join. To get started: https://steemit.com/enter_email
