### ISSUE TITLE
Comments Tab Not Indicating More To Read

### ISSUE THREAD

**Issue by taoteh1221** [steemit/steemit.com#1065]
When I review my comments tab, some longer shortened comment previews end in ... properly, BUT some long comments are clipped after the period of the end of the sentence, WITHOUT a ... indicating there is more to read if you click on it. So a user may easily assume they have read the whole comment, when in fact they have not.

You should be able to easily fix this shortened preview indication issue by always trimming any whitespace off the ends, remove any non-alphanumeric characters off the end, and then append ... to it afterwards.

**Comment by mcifani** [comment]
Thanks taoteh. This is now improved in a PR and will be released soon. Closing ticket.

**Comment by taoteh1221** [comment]
@mcifani Awesome. Your welcome, glad to help.
