### ISSUE TITLE
Close sign is scrollable on post modal

### ISSUE THREAD

**Issue by tibonova** [steemit/steemit.com#1071]
Post modal has double scrollbar, and one of them moves the close sign in a narrow interval.

[![post-modal-xbaab1.gif](http://www.steemimg.com/images/2017/01/28/post-modal-xbaab1.gif)](http://www.steemimg.com/image/schuu)

**Comment by mcifani** [comment]
Thanks.  Fix in PR https://github.com/steemit/steemit.com/pull/1078
