### ISSUE TITLE
Chrome for Android Push Notifications Undefined URL

### ISSUE THREAD

**Issue by taoteh1221** [steemit/steemit.com#1073]
On my Android phone in Chrome, push notifications from steemit.com are all linking to https://steemit.com/undefined

**Comment by ausbitbank** [comment]
Can confirm, I get the same problem but it's not consistent. 
Sometimes the links work, I'm still trying to figure out why some do and some don't.

Chrome Dev 53.0.2782.9 on Android 6.0.1

**Comment by taoteh1221** [comment]
@ausbitbank Odd, it is not consistent for me either. Just got another push notification and it worked properly, directing me to the replies page. Android 7.0 (OnePlus 3), Chrome 55.0.2883.91
