### ISSUE TITLE
Even when flagged spam effectively affects display of non-spam posts 

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steemit.com#1084]
Lately, a single user with three low sp, low rep accounts was able to cause this:
![image](https://cloud.githubusercontent.com/assets/6341057/22500154/f640eea6-e862-11e6-8100-4a213fce615b.png)
Even when community decided to get rid of this spam it still makes certain category unreadable. Just graying out those entries is not enough as it takes too much space on page anyway.
Making such posts even less visible, or even not visible by default (global setting for low-reputation top level posts) would work much better in such cases.

**Comment by roadscape** [comment]
These would be hidden if the author's rep was below 0.

**Comment by roadscape** [comment]
Done

**Comment by abitmore** [comment]
A side note, hidden posts can suck out author rewards stealthily.

Can we have a per-user config? For example, by default all posts from authors with negative rep are hidden, but the threshold can be changed by users / viewers locally.

**Comment by roadscape** [comment]
Posts with a positive payout are not hidden, and there is a "*Show more* low value posts" function on the right-hand pane.
