### ISSUE TITLE
Add referral parameter when sharing to social networks

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#109]
https://www.steemit.com/[postlocation]/?r=steemdrive

**Comment by jcalfee** [comment]
@thecryptodrive "Is it possible to add the links automatically to our FB/Twitter and LinkedIn Shares? I can do it for twitter manually, but can't edit the others see pic"

**Comment by roadscape** [comment]
We wouldn't want to do this by default. Do we want to make it configurable via settings pane?

We could have a "hidden" settings pane for advanced/power users.. e.g. chrome://flags/

Otherwise, this is low-priority and probably *wontfix*
