### ISSUE TITLE
Trying to replying to comment past 6 level should be better handled

### ISSUE THREAD

**Issue by Transisto** [steemit/steemit.com#1093]
Take this example : https://steemit.com/photography/@transisto/re-thecryptofiend-re-transisto-re-thecryptofiend-re-transisto-re-thecryptofiend-smoky-and-the-blanket-20170201t212614781z

I am able to click reply, write a long reply then get told "Comment is nested 6 posts deep, maximum depth is 6."

Maybe there should be a way to just quote the comment I'm replying to and post it to the previous valid parent for this post.   At least not letting me fill a comment and linking me to the person closest comment would be a practical solution.

Question : Is this a limitation of Steem or Steemit ?

**Comment by TimCliff** [comment]
It is at the blockchain level. It should be changed in the next hardfork.

Here is the GitHub issue:
https://github.com/steemit/steem/issues/767

**Comment by Transisto** [comment]
THANKS
