### ISSUE TITLE
<sub> tags are not correct line height between img & h2

### ISSUE THREAD

**Issue by klye-dev** [steemit/steemit.com#1095]
Image shows problem better: http://puu.sh/tKYeJ/bc978d81cf.png

html code that caused this:
```
<center>http://puu.sh/tKUl9/5a00bf2faa.png</center><sub><center>( It goes on like this for likely thousands of flags - screencap from[ steemd.com/@asshole](https://steemd.com/@asshole))</sub></center><center><h2>It Looked Like The Flags Would Never End..!</h2></center>
```
Thanks for checking it out guys. 

<3 KLYE

**Comment by roadscape** [comment]
Your `<sub><center>` tags are not nested properly. If you change it to `<center><sub>` it works fine. `center` is a block-level element while `sub` is inline, so always put the `sub` inside
