### ISSUE TITLE
Problems with the way steemit.com parses tags and what it includes in the "links" field

### ISSUE THREAD

**Issue by arhag** [steemit/steemit.com#11]
It stops parsing the tag at a hyphen, so creating tags with hypens in them is currently not possible.

I also think there needs to be a way to include a hashtag without automatically adding it as a tag. Sometimes I just want to use a hashtag (without wrapping it in quotes or in a code span) without having  steemit.com treat it as anything special.

See details in this post: https://steemit.com/test/@arhag/testing-tags

**Comment by arhag** [comment]
You shouldn't be converting a hashtag as the text inside a hyperlink.

I want to create a link to the Slack channel potential-bugs like so:
```
[#potential-bugs](https://steem.slack.com/messages/potential-bugs/)
```

But I cannot because of how steemit.com is parsing the hashtag. Same goes for the @ mentions.

**Comment by arhag** [comment]
I found a [workaround](https://steemit.com/test/@arhag/testing-tags#@arhag/re-arhag-testing-tags-20160521t004125070z). But the link issue mentioned in the above post still needs to be fixed.

And I still think there should be an easier way to "escape" tags and @ mentions than using the zero width space Unicode character.

**Comment by jcalfee** [comment]
Please re-test after the next release.  I pushed some fixes for this.
