### ISSUE TITLE
when a post pays out after 12 hours, the blue upvotes disappear

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#110]
"...so you don't know you voted for it before and click on it and you get an annoying error that you can't vote after payout. I like the votes to stay blue because I can check which are new comments/replies even after the payout date"

**Comment by aaroncox** [comment]
Removing this little bit shows the past votes. This has always bothered me too.

If I'm going to get the error, might as well be when I'm trying to uncast an old vote.

**Comment by roadscape** [comment]
Thanks, the change has been implemented.
