### ISSUE TITLE
cant open an account

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#111]
here is the issue my sister is encountering when trying to open an account:

10 assert_exception: Assert Exception creator.balance >= o.fee: 
Isufficient balance to create account {"creator.balance":"0.320 
STEEM","required":"3.000 STEEM"} th_a steem_evaluator.cpp:91 do_apply 
{"op":["account_create",{"fee":"3.000 
STEEM","creator":"steem","new_account_name":"lamouthe","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM831pbQwfv3WP2stAQUrJMEjjaJEGfFtrXN4MYAgqH9MjycdKMq",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6NaygfWotN5NhHMT3yqAmZtuTGvWnnCnNenArR14FDos3WJBDt",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5KbaLaUtb3ZFjkDiDZ7XWH4MSLUDDAmusfcJuM6AcLwpStmb8K",1]]},"memo_key":"STM5ncGtbBsPDQspY3tnwnJoVPquvWNnrgXhe7GDxFkTueTBRihmG","json_metadata":""}]} 
th_a database.cpp:2842 _apply_transaction 
{"trx":{"ref_block_num":40314,"ref_block_prefix":4186542510,"expiration":"2016-08-08T16:03:21","operations":[["account_create",{"fee":"3.000 
STEEM","creator":"steem","new_account_name":"lamouthe","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM831pbQwfv3WP2stAQUrJMEjjaJEGfFtrXN4MYAgqH9MjycdKMq",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6NaygfWotN5NhHMT3yqAmZtuTGvWnnCnNenArR14FDos3WJBDt",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5KbaLaUtb3ZFjkDiDZ7XWH4MSLUDDAmusfcJuM6AcLwpStmb8K",1]]},"memo_key":"STM5ncGtbBsPDQspY3tnwnJoVPquvWNnrgXhe7GDxFkTueTBRihmG","json_metadata":""}]],"extensions":[],"signatures":["207f6871e57cabdd5c82392e107d8014d909e71354150c7575ee8b7fce7759bcc26f81bd2472e5617ef2cb8cdf72d79a96434727d7c7914d96d54927e429d42e02"]}} 
th_a database.cpp:2846 _apply_transaction 
{"trx":{"ref_block_num":40314,"ref_block_prefix":4186542510,"expiration":"2016-08-08T16:03:21","operations":[["account_create",{"fee":"3.000 
STEEM","creator":"steem","new_account_name":"lamouthe","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM831pbQwfv3WP2stAQUrJMEjjaJEGfFtrXN4MYAgqH9MjycdKMq",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6NaygfWotN5NhHMT3yqAmZtuTGvWnnCnNenArR14FDos3WJBDt",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5KbaLaUtb3ZFjkDiDZ7XWH4MSLUDDAmusfcJuM6AcLwpStmb8K",1]]},"memo_key":"STM5ncGtbBsPDQspY3tnwnJoVPquvWNnrgXhe7GDxFkTueTBRihmG","json_metadata":""}]],"extensions":[],"signatures":["207f6871e57cabdd5c82392e107d8014d909e71354150c7575ee8b7fce7759bcc26f81bd2472e5617ef2cb8cdf72d79a96434727d7c7914d96d54927e429d42e02"]}} 
th_a database.cpp:671 push_transaction digest 
0a15f0bbf365a01abca15e7ebe1a7cf7c800900d3905c122a2aa8eeec0b51e27 
transaction 
7a9dae9189f949ada8570109b80b00000000000003535445454d000005737465656d086c616d6f75746865010000000001039e722f6eee092f38f4a92fc39b244dcbbd799e4b134b52376cca9c083a8e3399010001000000000102c37e63e39046badc9d468e2424635e6029cf13af4d7cb4c2cfc371ebb2656c83010001000000000102390256fc65f4b349de49630e47cd8c99639e2dc88931a908a720e9abf70988140100027657e37408f39ec83b5a1adea8ee776c97630ef0948933e9cdfdb818f74873a4000001207f6871e57cabdd5c82392e107d8014d909e71354150c7575ee8b7fce7759bcc26f81bd2472e5617ef2cb8cdf72d79a96434727d7c7914d96d54927e429d42e02
{"ref_block_num":40314,"ref_block_prefix":4186542510,"expiration":"2016-08-08T16:03:21","operations":[["account_create",{"fee":"3.000 
STEEM","creator":"steem","new_account_name":"lamouthe","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM831pbQwfv3WP2stAQUrJMEjjaJEGfFtrXN4MYAgqH9MjycdKMq",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6NaygfWotN5NhHMT3yqAmZtuTGvWnnCnNenArR14FDos3WJBDt",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5KbaLaUtb3ZFjkDiDZ7XWH4MSLUDDAmusfcJuM6AcLwpStmb8K",1]]},"memo_key":"STM5ncGtbBsPDQspY3tnwnJoVPquvWNnrgXhe7GDxFkTueTBRihmG","json_metadata":""}]],"extensions":[],"signatures":["207f6871e57cabdd5c82392e107d8014d909e71354150c7575ee8b7fce7759bcc26f81bd2472e5617ef2cb8cdf72d79a96434727d7c7914d96d54927e429d42e02"]}

**Comment by valzav** [comment]
Registrar account was running out of funds - this is not ui issue.
