### ISSUE TITLE
"you can only vote once every 3 seconds" error does not make second vote disappear in UI

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#1113]
1. vote up two comments one second apart.
1. both turn blue (voted)
1. receive "you can only vote once every 3 seconds" error message
1. both remain blue (voted)
1. refresh page
1. only first vote shows as voted (ui erroneously reported second vote when it didn't take)

**Comment by mcifani** [comment]
This is actually happening for any vote exception(i.e not enough vote weight as well).  Updating logic to gracefully handle this better.

**Comment by abitmore** [comment]
I think #1131 is related.

**Comment by mcifani** [comment]
PR update in https://github.com/steemit/steemit.com/pull/1154
