### ISSUE TITLE
@ mentions from accounts with less then 0 rep should not cause pop-ups.

### ISSUE THREAD

**Issue by neoxian** [steemit/steemit.com#1115]
This is a pretty simple one.  If an account achieves a reputation less then 0.  Then the @ mentions should not cause pop-up to appear.  This would fit in line with the general philosophy hiding an account with low rep.

**Comment by sneak** [comment]
The threshold has been implemented as 40 rep or below, and afaik is live now.

https://github.com/steemit/steemnotify/commit/f084562989025351df535178e28f4d90f6875119

**Comment by neoxian** [comment]
Thank you!
