### ISSUE TITLE
On the profile page show a list of accounts you are following.

### ISSUE THREAD

**Issue by valzav** [steemit/steemit.com#112]

**Comment by aaroncox** [comment]
I may take a stab at this one tomorrow. If anyone else is, please let me know so I'm not duplicating anyones effort.

**Comment by aaroncox** [comment]
I think I'm starting to get the hang of this?

## What the user is following/followed
![image](https://cloud.githubusercontent.com/assets/677686/17578580/9054b5d4-5f3f-11e6-90c6-4e202622f011.png)

## Who is following the user
![image](https://cloud.githubusercontent.com/assets/677686/17578587/9c4248e8-5f3f-11e6-9d86-65c01798bad9.png)

Some notes:

- No messaging yet if no followers/followed exists.
- Paginators are set to 50.
- You can access these pages by clicking the numbers under your username in the blue header area. `40 Followed` goes to /@username/followed and `249 Following` goes to /@username/following.

**Comment by aaroncox** [comment]
Apologies for the failed pull request, was trying it for the first time from the Github client as opposed to the command line.

**Comment by roadscape** [comment]
This has been live for some time, closing
