### ISSUE TITLE
autolinkifier does not detect .tech TLD

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#1127]
https://steemit.com/introduceyourself/@zcoinofficial/zcoin-joins-steemit#@zcoinofficial/re-maxse-re-zcoinofficial-zcoin-joins-steemit-20170208t174426569z

.io gets a link

.tech does not

(We should probably vendor in a TLD list, huh?)

**Comment by roadscape** [comment]
Currently, we don't autolink anything that doesn't start with a protocol. Looking at the raw post data explains the visual inconsistency:

```
Hi @maxse, thanks for the welcome.  [zcoin.io](https://zcoin.io) is our official website.  zcoin.tech is owned by someone no longer with the project.
```
