### ISSUE TITLE
When posting with the introduceyourself tag

### ISSUE THREAD

**Issue by Team-Steem** [steemit/steemit.com#1129]
When posting with that tag and clicking the post button, it would be nice if there was some sort of warning letting people know they should upload a photo of themselves holding a "hello Steemit" sign or video saying hello steemit. There should be examples and also a mention about verifying account with other social network accounts. 

There is so many nice introduction post that are reduce to quasi worthlessness because they don't have a verification of any sort. Also the trending page would benefit a lot from having those kinds of posts these days. 

I know those warnings could turn off some authors but there must be some kind of way and I'm leaving it to you to sort it out.

**Comment by sneak** [comment]
> I'm leaving it to you to sort it out.

Please constrain your issues in this repo to the code (and related bugs) contained herein; this is more "workroom" and less "committee chamber". :)

**Comment by TimCliff** [comment]
@Team-Steem - This is covered on the welcome page. 

New users will see this when they first create an account:
https://steemit.com/welcome

Here is a screen shot of what it shows for "introduceyourself" posts:

![image](https://cloud.githubusercontent.com/assets/20735105/22768529/694fd804-ee48-11e6-9ec6-83112e59785e.png)

**Comment by Team-Steem** [comment]
I was pretty sure it was covered as much as I'm pretty sure not many people read it. I guess successful people do read it and thus make successful introduction posts. Maybe I was looking too deep with this proposal but I still think it has some merit.

**Comment by TimCliff** [comment]
The roadmap has "New user tutorial". I believe the plan is to have some sort of onboarding process, which will guide new users through the process of getting started. Until then, the ones that take the time to read the suggestions will be more successful than those who don't :)

**Comment by Team-Steem** [comment]
Aw I agree. I guess I was too taken by the number of nice introduction post that won't get any votes because they didn't verify their account or posted a Steemit picture.
