### ISSUE TITLE
login remember me gets the login form out of sync

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#113]
[svk] bug related to the "remember me" button, which makes it so that if you click it after having entered your username you will need to re-enter your username. Even though the input field still shows your username, the code no longer knows it (this is the bug).

**Comment by aaroncox** [comment]
I'd also like to add that clicking the "remember me" button will clear out the password field. I assume this is a related issue to the click bindings modifying the form data. 

When I perform any "active" key activities on the site I typically paste in my password from the password manager, then uncheck the "remember me" box. This then forces me to paste again, boo.

**Comment by svk31** [comment]
Yea it clears the whole form I think, can be quite frustrating.

**Comment by jcalfee** [comment]
both should be fixed ..  0dc0aa11f1c6736bd361d1ae28c8b55625003682
