### ISSUE TITLE
After voting on a comment, another comment appeared to be upvoted too

### ISSUE THREAD

**Issue by pfunks** [steemit/steemit.com#1131]
I voted on the top comment, and the comment at the same level of nesting below showed the blue upvoted icon. It did not actually upvote the comment, and did not show the comment to have any vote count either, but the icon was blue. Before my vote, the top comment was in the position of the lower comment because it was made after it. @abitmore said he's also experienced this error.

![image](https://cloud.githubusercontent.com/assets/22420130/22785452/ee02e90a-ee99-11e6-92b8-3e617ffe0aa1.png)

**Comment by roadscape** [comment]
There is a small chance this is related to #1132

**Comment by abitmore** [comment]
Because after a vote, the order of comments is changed.
For example, now there are 2 comments, A has 2$ pending payout and B has 1$, so A is on the top; then you vote on B (the second), make it 3$, now B will be on the top; but on B it will show a upvoted icon (I guess it's added directly but not after confirmed by the backend).

**Comment by mcifani** [comment]
Currently working on related issue https://github.com/steemit/steemit.com/issues/1113, I'm improvin logic on rendering the vote button state(colors).  Most likely will also correct this issue.

**Comment by mcifani** [comment]
There is a pending PR https://github.com/steemit/steemit.com/pull/1154 which addressed a similar issue on the vote button state.  The new logic should also resolve any pending issue here.  I can't seem to replicate this error locally.  Pfunks, please test https://github.com/steemit/steemit.com/pull/1154 locally or wait until our next release to test in production.  Please re-open this ticket if it happens again after either scenario.
