### ISSUE TITLE
Can we get a mute list?

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/steemit.com#1134]
Maybe I would like to give some folks another chance but I don't remember who they are.
A list gives me that option.

If I could get a count of times I have been muted, that would be good feedback, too.

**Comment by TimCliff** [comment]
It is there on your settings page.

**Comment by roadscape** [comment]
Yep, it's in the settings. 

As for getting a count of times you've been muted, this would be best provided by an external service, and not on steemit.com.

**Comment by FreeBornAngel** [comment]
D'oh, there is a list.
Thanks!!

I really don't want to go off steemit, I don't like the external services, so far.
