### ISSUE TITLE
Internal market shows Last price: 0

### ISSUE THREAD

**Issue by tibonova** [steemit/steemit.com#1136]
# Last price

![7996ba144db78a7a4d397aff527a4dc7.png](http://www.steemimg.com/images/2017/02/10/7996ba144db78a7a4d397aff527a4dc7.png)

# Trade History

![abd49cd63d3a278affd33ebf68fb52bc.png](http://www.steemimg.com/images/2017/02/10/abd49cd63d3a278affd33ebf68fb52bc.png)

---

`Last price = 0` suggests that someone traded STEEM for zero. However, that doesn't appear in the `Trading History`, therefore something is wrong.

**Comment by roadscape** [comment]
This might be caused by a dust/"remainder" order. Those might be getting filtered out of the Trade History table, I don't recall. Is this the first time you've seen it?

**Comment by tibonova** [comment]
Yes, this was the first time I've seen it (it remained zero after opening this report for a while), though I'm not a frequent user of the market. 

Since no one should/will sell for zero (it's a gift, not a trade), I suggest that don't change `last price` if `new price = 0`. That would provide more useful information and less misunderstanding.

**Comment by roadscape** [comment]
Thank you for the report. This seems to be a backend API issue, so I've continued the discussion here: https://github.com/steemit/steem/issues/863
