### ISSUE TITLE
No mention of tarantool is made in the installation instructions

### ISSUE THREAD

**Issue by neoxian** [steemit/steemit.com#1140]
It seems like you need tarantool to run steemit.com but no mention is made on how to install this in the installation instructions.

**Comment by mcifani** [comment]
You shouldn't need tarantool to start, although certain functionality won't work. Do agree the readme should include instructions.

**Comment by neoxian** [comment]
Which functionality doesn't work without tarantool?  I did notice that user icons don't show up.

**Comment by mcifani** [comment]
Updates in PR https://github.com/steemit/steemit.com/pull/1142

**Comment by neoxian** [comment]
Thank you!
