### ISSUE TITLE
Unable to Edit Articles

### ISSUE THREAD

**Issue by rlloyd2001** [steemit/steemit.com#117]
I keep getting this error when I try to edit past articles. I have not been able to come up with a work around.
Transaction failed: comment.last_payout == fc::time_point_sec::min(): DISMISS

**Comment by rlloyd2001** [comment]
This is in Chrome..

**Comment by svk31** [comment]
It's not possible currently to edit articles after the 12h payout. This may change in the future (it used to be possible), but for now this is a blockchain level limitation.

**Comment by rlloyd2001** [comment]
That seems like an unreasonable limitation to not ever be able to edit or delete a posted article. It would've been nice to have a warning on this or at least keep the article in a 'draft' state for a longer period of time if needed.

**Comment by roadscape** [comment]
This is a blockchain limitation but the edit period will be increased to 30 days after the next hardfork. Once a post is on the blockchain it will always be there, it can never be deleted, only hidden. I do believe it is possible to "delete" a post if it has no comments yet.

You raise a good point that we need better warnings about these "quirks". I've created a separate issue: #153
