### ISSUE TITLE
Last Update Has Broken HTML centering and direct linking

### ISSUE THREAD

**Issue by thecryptofiend** [steemit/steemit.com#1177]
It seems that something has been updated and that has broken how the "center" tags work.  I just checked through my old posts (which were fine before the update) and they are all showing the same issue.

I have also noticed that direct links to my post no longer work either for me or anyone else. This is my post from tonight and this is the direct link:

[https://steemit.com/health/@thecryptofiend/vitamin-d-may-prevent-colds-and-flu](https://steemit.com/health/@thecryptofiend/vitamin-d-may-prevent-colds-and-flu)

I have made a post about this issue here:

https://steemit.com/steemit/@thecryptofiend/html-centering-and-post-linking-error-since-last-update-16th-february-2017

**Comment by mcifani** [comment]
Thanks @thecryptofiend we'll look into it shortly.  Oddly it's only your older post.

**Comment by sneak** [comment]
Weird that

https://steemit.com/health/@thecryptofiend/vitamin-d-may-prevent-colds-and-flu

doesn't work but

https://steemit.com/@thecryptofiend/vitamin-d-may-prevent-colds-and-flu

does.

**Comment by thecryptofiend** [comment]
Thanks guys it is very weird and also the fact that all my old posts are now centred formatted even thought they were fine before.

**Comment by roadscape** [comment]
@thecryptofiend you are saying they are *not* supposed to be center-aligned? Does busy.org render them any differently?

> Weird that
> 
> https://steemit.com/health/@thecryptofiend/vitamin-d-may-prevent-colds-and-flu
> 
> doesn't work but
> 
> https://steemit.com/@thecryptofiend/vitamin-d-may-prevent-colds-and-flu
> 
> does.

Strange indeed. I don't get this error locally, so it's possibly a bug with steemd `v0.16.3`

**Comment by thecryptofiend** [comment]
> @thecryptofiend you are saying they are not supposed to be center-aligned? Does busy.org render them any differently?

No they have titles which should be centred but the text should not be.   Now all the text is centred as if there is a broken html tag even though I have checked them multiple times and there isn't one.  My old posts which were fine before are showing the same issue now:

https://steemit.com/photography/@thecryptofiend/colour-infrared-photos-of-the-angel-of-the-north

They are formatted the same on BUSY too.  Looks like there is a problem with center html tags only.  For titles I use html heading tags and interestingly these are working normally - the body text is not displaying as title text - only the centering is faulty.

**Comment by roadscape** [comment]
I do see some issues with the way tags are nested.. for example:

```
<center><h1>Introduction</center></h1>
```

The closing tag is improperly nested, so that's probably what's causing it to stay open

**Comment by thecryptofiend** [comment]
@roadscape Thanks I never spotted that I had them the wrong way around in my template!  Changing them seems to fix it but I'm not sure why it wasn't breaking things before but has started now.  Is there any way to fix them in my old posts without having to find each and every one?

**Comment by roadscape** [comment]
@thecryptofiend it's due to an update in an underlying parser package. It seems to have became more strict in how it handles invalid nesting of tags. Unfortunately, there is no easy way to fix all old posts, unless someone writes an automation tool or adds a compatibility layer.

---

For future reference, I believe this is the change (htmlparser2 3.9.1 -> 3.9.2): https://github.com/fb55/htmlparser2/compare/f4651bd...e1f12f6

**Comment by thecryptofiend** [comment]
@roadscape Thanks for your help mate.  It would be awesome if someone could do that - I don't know enough about such things - I didn't even know they had to be the right way around lol!

**Comment by KrNel** [comment]
What about the "health" tag not working? The link still doesn't work when the link is used... not good.

**Comment by sneak** [comment]
Ahh, /health got accidentally hijacked by our container's health check endpoint. Will be fixed today.

**Comment by KrNel** [comment]
Thanks!
