### ISSUE TITLE
Add commas to the view count

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#1178]
![image](https://cloud.githubusercontent.com/assets/204121/23049302/d65459be-f480-11e6-993e-ba8149438dbb.png)
[the post](https://steemit.com/life/@wadepaterson/20-questions-with-john-goehrke-the-guy-who-landed-a-date-with-genie-bouchard)

**Comment by mcifani** [comment]
Update PR in https://github.com/steemit/steemit.com/pull/1199
