### ISSUE TITLE
Phone verification on signup error

### ISSUE THREAD

**Issue by mfsousa** [steemit/steemit.com#1187]
I'm trying to signup and it keep failing with the error Unable to verify phone, please try again later.

For debug, here is the phone number I'm using:
- Country: Brazil (+55)
- Phone Number: 85998131415

I'm sure didn't made any mistake typing the number... could someone check why it is failing?

**Comment by mfsousa** [comment]
Finally after many attempts it worked. I don't know if someone did something, maybe enabling my number, but thanks.

All OK now.

**Comment by sneak** [comment]
We had a temporary issue with our service that is now resolved. Sorry about that!

**Comment by sneak** [comment]
Thank you for reporting it, that was the right thing to do. :)
