### ISSUE TITLE
Feed section not loading

### ISSUE THREAD

**Issue by PixelNoob** [steemit/steemit.com#119]
Feed section does not load when following too many users.

**Comment by roadscape** [comment]
Could you show a sample URL?

**Comment by aaroncox** [comment]
If there's a feed loading error, I don't think it's because of someone following too many users. 

[alexoz on steemit](https://steemit.com/@alexoz) afaik is the one following the most users at 938. The [feed on the profile page](https://steemit.com/@alexoz/feed) seems to load just fine.

**Comment by PixelNoob** [comment]
This happened to me and a couple of other users for a very brief period of time yesterday, it was later fixed.

Issue closed.
