### ISSUE TITLE
Norwegian numbers cannot be verified

### ISSUE THREAD

**Issue by rohtie** [steemit/steemit.com#1190]
After confirming email, one is asked to provide the phone number. I choose the norwegian  country code and entered my norwegian number.  Then on submission I got the error message "Unable to verify phone, please try again later."

A friend of mine ran into the exact same issue with his norwegian number yesterday. 

I tried to format my number a bit differently on successive tries,  but none of them worked. 

Some formats I tried(x is a number):
xxxxxxxx 
0xxxxxxxx
xx-xxx-xxx

**Comment by sneak** [comment]
Please give it another try. We had a temporary issue with our service that is fixed now. 

Thank you for reporting it, and sorry for the inconvenience!

**Comment by rohtie** [comment]
Thanks, it works now!
