### ISSUE TITLE
Cannot change my own post title

### ISSUE THREAD

**Issue by cryptomental** [steemit/steemit.com#122]
I created a post where I would like to change the title from 'engineered' to 'reverse-engineered'.

https://steemit.com/steemit/@cryptomental/can-a-viral-introduceyourself-post-be-engineered

The above post contains links to a few other steemit.com posts. When I click on the above link I see the post but I cannot see my user menu (the wheel is spinning). I tried the same on two different browsers and different PCs and it is 100% reproducible.

**Comment by cryptomental** [comment]
Reproduced on Ubuntu 14.04 LTS 64 bit, Chrome and Firefox and on Ubuntu 16.04.1 LTS on Firefox 48.0.

**Comment by roadscape** [comment]
Have you tried logging in in an incognito window? Are there any errors in the console?

**Comment by jcalfee** [comment]
Can you clarify?  You should be able to edit and change the title.  However, you can't change the URL, that will never change after the first post.

**Comment by cryptomental** [comment]
I checked today again morning. Still 100% reproducible. I cannot see anything useful on the console. See the screenshot: http://i.imgsafe.org/d60af4cfe9.png and the spinning wheel.

When I opened an incognito window and logged in, the page became unresponsive after I pressed 'Edit' post link. See another screenshot: http://i.imgsafe.org/d60bd6f25b.png

I also noticed that one of my CPU cores becomes 100% utilized when this happens.

The issue does not happen when I am only browsing logged out/logged in. Only when I want to edit this one particular post.

**Comment by cryptomental** [comment]
And to answer @jcalfee question, I do not want to change the URL, just the title.

**Comment by jcalfee** [comment]
I see an issue trying to pull up the editor on this post.  My browser is unresponsive too..

**Comment by roadscape** [comment]
I managed to collect a profile:
![image](https://cloud.githubusercontent.com/assets/5168676/17626050/95e3b1fe-6079-11e6-992f-a17769a313b8.png)

It appears to be an issue with `react-rte` but I haven't yet found the reason why it's even running upon Edit. The markdown editor eventually loaded for me and the page was again fully responsive. i.e. it appears to be an issue only of ReplyEditor initialization

**Comment by jcalfee** [comment]
You were lucky to get that profile.  Ha, not easy to do.  I did change the startup to light it up and seems to avoid the issue completely.  I was able to go into edit mode on your post.  Please try it again, it was just deployed.

**Comment by cryptomental** [comment]
Thanks a lot, it seems to be fixed! I could not change the title anyway and I suspect it is related to the fact that it cannot be changed after the first payout. I see an error message saying:

```
comment.last_payout == fc::time_point_sec::min():
```

but at least I can see the markdown now and the browser does not hang anymore.
