### ISSUE TITLE
comment anchor points need adjustment to offset the static top menu

### ISSUE THREAD

**Issue by aaroncox** [steemit/steemit.com#124]
Found this on steemit a bit ago.

https://steemit.com/steemit-bug/@ash/steemit-bug-report-comment-anchors

What's happening is when the page scrolls to an anchor, the static navigation at the top of the page is covering the anchor point. An adjustment should be made either through a plugin or through detaching the anchors to offset it's position accounting for the navigation elements.

**Comment by shanejonas** [comment]
The problem is the size of the images/iframes. They don't load and take up space by the time it scrolls you to the right `y` value.

**Comment by aaroncox** [comment]
That's part of the problem as well, but even without any images/iframes on a post, it's still happening. 

Upon further discussion, yet another part of this problem is the message at the bottom of each post that says "Authors get paid...". 

Example here:

![page-jump](https://cloud.githubusercontent.com/assets/677686/17608501/bcb91730-5fe1-11e6-8d70-36fca11ab887.gif)

The logic on that element should probably be changed to hide on default, and then showing if we detect they aren't logged in.

**Comment by roadscape** [comment]
I cleaned up anchor/scrolling logic and added a 200px scroll offset for now. Without the banner issue, a 60px scroll offset works well to position the comment comfortably at the top of the screen.

To hide the promo banner until login status is known may be good as a general behavior, though it's not clear to me why it wouldn't be known immediately upon page load. Pushing the content down is not ideal, but better than the comment disappearing off the top of the screen. Hence the 200px workaround.

Inserting/removing elements and expecting scroll-to to work is not simple.. there is probably a better way to approach this issue

**Comment by roadscape** [comment]
Workaround in place and working.
