### ISSUE TITLE
No posting authority @cryptoctopus

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#127]
All of a sudden I no longer have posting authority. What's going on?

**Comment by valzav** [comment]
Try to change your password or restore account if you changed your owner key recently

**Comment by roadscape** [comment]
@SteemitFbAdmin still having this problem? If so, please add more details.

**Comment by roadscape** [comment]
Another report..

> I'm having trouble submitting too. Getting a "Missing Posting Authority" message.
>
>> I think you have to post with posting password, log in with posting password/wif etc
>
> That wasn't it. I was able to post anyway, but not that partiular article. It was a html problem with an image address having an enya in it. For some reason it caused that error on Steemit.

**Comment by jcalfee** [comment]
This should be fixed...  Reopen if needed.
