### ISSUE TITLE
Duplicate Spam Posts

### ISSUE THREAD

**Issue by taoteh1221** [steemit/steemit.com#128]
You all may want to consider a detection system in your steemit.com back end, for mass spam like this post's comments section. It's a stalker posting the same exact reply over and over and over, again and again. It would be nice to not have to use voting power to flag multiple instances of the same exact reply, when trying to clean up the comments section GUI.
https://steemit.com/art/@kaylinart/some-of-my-best-artwork-mixed-photos#@nameles/re-taoteh1221-re-kaylinart-some-of-my-best-artwork-mixed-photos

**Comment by roadscape** [comment]
Steemit.com's backend is (currently) almost entirely the steemd node, which does not support any sort of spam detection. We rely on the community to help with this. 

However, I've created a separate ticket which will help visually clean up spam comments: #141
