### ISSUE TITLE
login

### ISSUE THREAD

**Issue by Bitdv** [steemit/steemit.com#129]
Ok it seems im locked out of my account , password isnt working , non of the private WIF keys are working , they are correct , i have them saved as screenshots,text files and printed , i tried to use account recovery, it said password hasnt been used in last 30 days , well it has , same as the WIF keys (private), i was trying to set up mining with the private wif activity key as instructed in the guides i was using , not sure if this has done anything to my account , looking for guidance as I have just about 2k SP , dont want to lost it , my account username is shawn-brewer

**Comment by svk31** [comment]
Your keys were changed yesterday, did you do it yourself or not?

![image](https://cloud.githubusercontent.com/assets/6890015/17648455/5270a0be-6216-11e6-9588-74fa4d51dacd.png)

**Comment by Bitdv** [comment]
nope i didnt had no reason to

**Comment by svk31** [comment]
Well if you didn't change your keys then it looks like you were hacked. Unless you used the "Change password" feature, that would change all your keys.

**Comment by Bitdv** [comment]
i didnt , but when it wouldnt let me login i tried to use the change password feature but it kept saying it was incorrect password so i went to the recover account section and it said that i hadnt used the password in the last 30 days , which is incorrect , and i asked in the steemit chat and i was told the private keys could also be used but they also gave me the same response, so what do i do from here ???

**Comment by Bitdv** [comment]
so am i able to salvage my account or is it gone with the 2k steem power i have in there ??

**Comment by roadscape** [comment]
Were these transactions initiated by you?
![image](https://cloud.githubusercontent.com/assets/5168676/17743986/d79ae4ac-6473-11e6-9d74-0c194d76bf8d.png)

**Comment by Bitdv** [comment]
yes they were initiated by me the upvote that i did , when i did the upvote it logged me out and this is when it all started

**Comment by roadscape** [comment]
What commands did you run when you were trying to set up your account for mining? It seems like you may have replaced the wrong keys on your account, because you still don't have a signing key: https://steemd.com/@shawn-brewer

----

If one of your keys/passwords is the *current* owner key, this form will help you:
https://steemit.com/@shawn-brewer/password

If one of your keys/passwords is a *recent/previous* owner key, this form will help you:
https://steemit.com/recover_account_step_1

**Comment by Bitdv** [comment]
Ok im really confused i just thought i would try it again and i was able to recover my account , its exactly what i did the other day , but im in thanks sorry for the dramas i was stressed and well it worked this time
