### ISSUE TITLE
Body of posts missing 

### ISSUE THREAD

**Issue by deviedev** [steemit/steemit.com#133]
The body of two of my posts are missing when view on steemit. They appear just fine on steemd, though. Is this a bug? 

my username is deviedev. the posts in question are my intro and the one on human rights treaties.

**Comment by lantto** [comment]
Example: https://steemit.com/introduceyourself/@deviedev/environmental-attorney-girl-with-a-guy-s-name-here-s-my-story

Body on blockchain:
```html
<p><center><img src=\"http://imgur.com/0nd9gr6.png\" /> \n</center></P>\n\n\n# HELLO! My name is Devin and I am a lawyer living in Manhattan. \n\nI tend to shy away from elaborate social introductions--mostly because I am an introvert, but also because the legal profession, as a whole, is fairly reserved. So don't tell my boss.\n\n# Why I'm here: \nMy journey to becoming a cryptocurrency enthusiast started with my husband. He is a developer and dabbles in all things internet. \n\n<p><center><img src=\"http://imgur.com/vnlQQyS.png\" /> \n</center></P> \n\n**See what I mean?** \n\nAnyways, my curiosity often leads to obsession, so what started out as some light Wikipedia reading soon turned into wallets, exchanges, and daily visits to coinmarketcap.com. Now, here I am making my social debut in the name of blockchains. How far I've come! \n \n# A little about me:\n \nIn a study of nature versus nurture, I'd probably be an outlier. The product of addicts, adopted, first to go to college, etc. I won't bore you with the details because I'm sure many of you have seen Lifetime movies before. However, out of that came an unshakable drive to right wrongs, if you will. A couple of degrees and lots of student loans later, I became a lawyer.    \n   \nI believe people should be protected from industry irresponsibility and wrongdoing, which is why my legal career has focused primarily on environmental and mass tort litigation. I love the challenge of collective actions and the responsibility that representing hundreds of people brings. I think it is important to spread awareness, so you can expect to see lots of posts on the latest human health or environmental issue.\n \nDon't worry though, it won’t be all business. I'm interested in everything. \n\nME:\n\n<p><center><img src=\"http://imgur.com/wBoZvvO.png\" /> \n</center></P>
```

**Comment by roadscape** [comment]
I notice that the opening tag is `<p>` and the closing tag is `</P>`, that could be an issue for some parsers.

Also, this is a mix of markdown and HTML. Which editor did you use to generate the post?

**Comment by deviedev** [comment]
What do you mean by editor? Unfortunately, I'm not well-versed on this type of stuff.

When I first started, I used code that I found via Google. I don't believe that I put in capital Ps though, if that makes a difference. Anyways, all of my earlier posts were displaying just fine (even after payout) until a few days ago. You can still see them on steemd.com still, but not on steemit. 

If it is not a big, I am happy to repost using markdown--I just don't want to get flagged for doing so.

**Comment by roadscape** [comment]
Did you originally create this post in Markdown mode? Or in the HTML (visual editor) mode?

To me, it looks like you may have used the markdown mode, with some custom HTML mixed in.

There are 2 issues:

1) A quirk on our end is that any post starting with `<p>` is assumed to **not** be markdown.
2) Your tags are mismatched: `<p>..</P>` (one lowercase 'p', one uppercase) -- this is causing further rendering problems.

Luckily the solution is simple: don't use `<p>` tags at all. Markdown inserts them automatically. You can still use `<center>` to center images as you currently do.

**Comment by roadscape** [comment]
I seems @jcalfee has found a solution that will fix your post. 

After we release it I would recommend going into your post and removing the `<p>` and `</P>` tags to make it future-proof!

**Comment by roadscape** [comment]
The post is now showing properly.

**Comment by deviedev** [comment]
@roadscape @jcalfee Thank you for resolving this! Everything looks great. And I apologize for the delayed response--got tied up with work stuff. 

I will remove the old tags and refrain from using html in the future. Thanks again! Everyone's hard work is much appreciated.
