### ISSUE TITLE
Dev environment for running steemit locally -- updates to README required

### ISSUE THREAD

**Issue by bmann** [steemit/steemit.com#135]
I got steemit.com and steemd running locally on my Mac (the latter thanks to @TigerND and his homebrew items. The README is pretty good, I've made some changes and will do a pull request for OS X.

I'm up and running and looking at localhost:3002. How do I seed the database with a local dev login?

**Comment by roadscape** [comment]
A local dev login for what? Currently there's no testnet, so there's no such thing "dev login" for steem or steemit.com. You'll just need to create an account for testing via the faucet or CLI.

**Comment by bmann** [comment]
I have Steemit running in my Dev environment locally with a blank database. I want to do local development for visual fixes and pull requests. 

Can you point me at how to create an account for testing?

Happy to document.

**Comment by roadscape** [comment]
There are 3 ways to create a steem account:

1) cli_wallet: `create_account string creator, string new_account_name, string json_meta, bool broadcast` command
2) Mining an account
3) Faucet: https://steemit.com/create_account

**Comment by roadscape** [comment]
Were you able to create an account?

**Comment by bmann** [comment]
@roadscape I'm not sure I'm asking for the right thing.

I have an account on steemit.com (http://steemit.com/@bmann) -- I can login, and know what all my passwords / keys are. I had that before, no problems there.

For local development, I have a copy of the steemit.com running at localhost:3002

I'm running steemd locally with ```steemd --rpc-endpoint 127.0.0.1:8090``` as listed in the README.

I can view localhost:3002 and see an "empty" instance running. I try and login with "bmann", and get "Username does not exist" (because it's connecting to the local steemd node, which isn't synced with anything).

So, does the local steemd need to be connected to different seed nodes so I can login using my existing account?

**Comment by aaroncox** [comment]
@bmann Is local node running on testnet or something? I think most of us while doing development have nodes that are connected to the live network and all of the live accounts work fine for testing.

**Comment by bmann** [comment]
You tell me @aaroncox :P I'm trying to follow the README successfully, and ```steemd --rpc-endpoint 127.0.0.1:8090``` is the only thing I have to go on. Do I need to also connect to seed nodes in configuration?

**Comment by bmann** [comment]
OK, got some Twitter DMs from @TigerND 

In the README, we should be saying that you need to be running a full node locally. The command should be something like:

```steemd --rpc-endpoint 127.0.0.1:8090 --seed-node="seed.steemed.net:2001" --seed-node="52.74.152.79:2001" —witness=“YOURACCOUNT”``` (can someone confirm?)

And I guess you need to be fully synced and basically setup to be mining. Which takes like 8 - 11GB of memory? Guess I'm not going to be using my laptop for dev!

Thanks all.

**Comment by bmann** [comment]
Will leave open to reference in a pull request.

**Comment by svk31** [comment]
There's no need to run a local instance of steemd anymore, just use `wss://node.steem.ws` instead.

**Comment by aaroncox** [comment]
@bmann - Sorry I didn't get back to you on this earlier.

> And I guess you need to be fully synced and basically setup to be mining. Which takes like 8 - 11GB of memory? Guess I'm not going to be using my laptop for dev!

You don't need a mining/witness setup to run locally, but you will need a node with most of the plugins enabled like the readme on steemit/steemit.com indicates. If you're looking for examples of setting it up yourself, you're [welcome to follow this guide](https://steemit.com/steem/@jesta/building-a-high-availability-steemd-node-for-web-apis), it's how the servers for steem.ws are setup.

For local development, you obviously don't need two nodes like the guide suggests, but all the relevant configuration you'd need is there. 

Otherwise feel free to use the steem.ws node like @svk31 mentioned - that's how I've been doing my development. Feel free to message me on steemit.chat if you need any info without a 36 hour delay ;)

**Comment by bmann** [comment]
@svk31 that's great! How do I configure the steemit.com development environment to reference that node? I'll update my pull request to reference that we don't actually need to setup or configure steemd at all for local development.

I assume it's this section of config:
```
"ws_connection_client": "ws://localhost:8090",
  "ws_connection_server": [
    "ws://localhost:8090",
    "ws://localhost:8091",
    "ws://localhost:8092"
  ],
```

Would we just replace ```localhost``` with ```wss://node.steem.ws```? Can someone share that section of their config file, please.

@aaroncox no worries, I'm not looking for speed, I'm looking to improve documentation for those that come after me, so I'm doing this out in the open.

Looks like I can make pull requests for both README as well as ```config/steem-example.json``` unless people have other pointers?

**Comment by svk31** [comment]
@bmann Exactly, just replace the `ws_connection_client` string and the first entry in the `ws_connection_server` array with `wss://node.steem.ws`.

**Comment by faddat** [comment]
@bmann I have a server running with a reasonably good dev env.  I'm willing to clone that for you (and for anyone else) so you can get into things.  It took me a somewhat ridiculously long time to get all of the components of this glorious behemoth talking to each other happily, but I've now got them done.

**Comment by bmann** [comment]
@faddat it wasn't too bad for me (I'm on the Mac, and brew commands are awesome). The point is to update the README to reflect reality! Dockerfiles would also be helpful as a way to "clone" the environment so it is repeatable.

**Comment by faddat** [comment]
![image](https://cloud.githubusercontent.com/assets/7142025/17870907/8bd4988c-68e3-11e6-9b7a-994918e8ab6d.png)

**Comment by bmann** [comment]
OK, would appreciate review of my pull request #156.

Now on to some REAL pull requests!

**Comment by bmann** [comment]
Woot! Thanks everyone, merged!

**Comment by thomsonimjd** [comment]
@bmann could you please let me know how to run the steemit using this command steemd --rpc-endpoint 127.0.0.1:8090. I am a newbie infact on steemit. I would like to hard fork it, please let me know, thanks.
