### ISSUE TITLE
Freezing when "post" is clicked.

### ISSUE THREAD

**Issue by aboundlessworld** [steemit/steemit.com#136]
Hey there! Thanks for all the help.

I've been having trouble posting for an entire day now. I'm sure you all are crazy busy but would love to get this fixed as soon as possible. I can leave comments on other people's posts no problem, but when I go to post my own it freezes with the endless spinning wheel right after I click post.

I've tried on Chrome, Safari, and Brave and have reset my cache. Any ideas on what might be causing this?

Thanks so much! 

<a href="http://www.aboundlessworld.com/wp-content/uploads/2016/08/Screen-Shot-2016-08-15-at-20.52.46.png"><img src="http://www.aboundlessworld.com/wp-content/uploads/2016/08/Screen-Shot-2016-08-15-at-20.52.46-1030x629.png" alt="Screen Shot 2016-08-15 at 20.52.46" width="1030" height="629" class="aligncenter size-large wp-image-5493" /></a>

**Comment by roadscape** [comment]
Please check in the console for any javascript errors and report back with what you find.

**Comment by roadscape** [comment]
One thing I notice: it looks like copied-and-pasted HTML with some attributes we don't allow (`class`, `style` for instance). This should not be freezing the page, but perhaps it has something to do with this bug.

**Comment by roadscape** [comment]
Another similar report, this was due to an "illegal char" in a link url in the post body.

> ["https://chrome.google.com/webstore/detail/steemd-steem-↔-steemit-we/knjonokngbbpdnnmgadcfcidojbedioj"]}	cause: illegal char code: 8596 
stack: RangeError: illegal char code: 8596

**Comment by jcalfee** [comment]
Likely fixed in https://github.com/steemit/steemit.com/commit/c5d22107c33479ce9430a17f3590999c56e3264a

Let us know if this is still an issue.
