### ISSUE TITLE
Publish a public roadmap

### ISSUE THREAD

**Issue by ripper234** [steemit/steemit.com#139]
Can you tell us the bird eye's view of what you're working on?
What do you hope you achieve this month/quarter?

I suggest a publicly viewable Trello board ([example](https://trello.com/b/ZnTQyumQ/slack-platform-roadmap-for-developers)), or Github milestones.

**Comment by faddat** [comment]
I'd like to second this and extend it to dev work on the blockchain as well. The more we know, the more we can help out.

**Comment by TimCliff** [comment]
This is not the same thing as an official road-map, but there is this post here for "The Steemit Wish List". Anyone who wants to help out with feature development should check it out to see what the community is asking for.

https://github.com/steemit/steemit.com/issues/195

**Comment by sneak** [comment]
This repo is for steemit-dot-com-the-codebase, not steemit-the-company. :)

**Comment by roadscape** [comment]
We're using gh milestones and a Steemit, Inc roadmap is forthcoming.

**Comment by sneak** [comment]
Followup: It will be published loudly on or before 1/1. :)
