### ISSUE TITLE
Steemit flag Accountability System Idea

### ISSUE THREAD

**Issue by SparkedDevelopment** [steemit/steemit.com#140]
Was braining storming some ideas an this is what i came up with.

Steemit flag Accountability System Idea:
https://steemit.com/steemit/@sparkeddev/steemit-flag-accountability-system-idea

**Comment by roadscape** [comment]
It's a good idea, but this type of feature needs to be implemented/enforced in the backend first. There might already be an open issue for it at https://github.com/steemit/steem
