### ISSUE TITLE
Using <> in article (editor mode)

### ISSUE THREAD

**Issue by lukmarcus** [steemit/steemit.com#145]
For example I used <table> in editor mode. It looks fine in preview but after posting it goes totally wrong.

**Comment by roadscape** [comment]
> For example I used
>
> in editor mode. It looks fine in preview but after posting it goes totally wrong.

Did something get cut out here?

By editor mode, you referring to the wysiwyg HTML editor correct?
![image](https://cloud.githubusercontent.com/assets/5168676/17780998/6d9f30b2-653b-11e6-9654-a264e9505392.png)

**Comment by lukmarcus** [comment]
Yes, this editor. When I used <table> it looks fine on preview (when I switched to raw html) but after posting article some text dissapered.

**Comment by lukmarcus** [comment]
{table}

**Comment by roadscape** [comment]
The title of this issue is `Using <> in article`, I'm not sure what this means

And I don't understand what you mean by `{table}`. Please edit your comment instead of adding more comments because it's not clear what you are trying to say.

**Comment by lukmarcus** [comment]
OK. I used `<table>` when writing article. I wrote it in editor then switch to raw html to see if this will look ok in preview. And it was fine. Then after posting Steem used it as normal html `<table>` and cut text from article.

**Comment by jcalfee** [comment]
Do you have a link to your article?

**Comment by jcalfee** [comment]
Please edit your post and put <html> at the top then </html> at the very bottom.  Let us know if that fixes it.

**Comment by jcalfee** [comment]
If your post is mixing markdown and html I don't think it will work out..  You might want to convert to a markdown [table](https://guides.github.com/features/mastering-markdown/) instead. 

I suspect the post does not have <html>  around it but has a <table> inside.  If your post has no markdown, you could wrap it in <html> ... </html>.  If you don't do that, it passes the post to remarkable to render which then escapes it and shows the literal table.

**Comment by lukmarcus** [comment]
There is still problem with that but another kind. Look at article - https://steemit.com/steem/@lukmarcus/dollar-vigilante-jeff-berwick-and-his-steemit-adventure-statistics-and-graphs . There is a table with column "#". Previosly there was word "number" and below "article01", "article02" and so on. Those words were cut in half so I changed it.

**Comment by jcalfee** [comment]
Please re-open if this is still an issue.
