### ISSUE TITLE
Tables look different in browsers

### ISSUE THREAD

**Issue by lukmarcus** [steemit/steemit.com#146]
There is a problem with viewing tables in different browsers. It looks fine in preview (also all browsers) but then... More in article: https://steemit.com/steemit/@lukmarcus/what-s-wrong-with-less-than-table-greater-than-on-steemit-firefox-and-edge-vs-chrome-and-opera

**Comment by roadscape** [comment]
Could you share the link of the steemit.com post showing this table issue?

For reference:
![image](https://cloud.githubusercontent.com/assets/5168676/17781281/b72d7792-653c-11e6-8f10-18a5822ac6e5.png)

**Comment by lukmarcus** [comment]
https://steemit.com/introduceyourself/@lukmarcus/statistics-for-top-100-5-most-popular-steemit-introductions-part-1-intro-introduceyourself
