### ISSUE TITLE
on the transfer form in To field turn all user's input into lowercase

### ISSUE THREAD

**Issue by valzav** [steemit/steemit.com#148]

**Comment by jcalfee** [comment]
It allows uppercase now but it will fail validation.  What are we trying to do here? Is the blockchain going to take mixed case?  I have not tried that.

**Comment by jcalfee** [comment]
`is_valid_account_name( name ): Account name JSC is invalid`

**Comment by jcalfee** [comment]
Mobile devices really like to uppercase the first letter.  The auto-lowercase was immediate feedback that it you have the name right.
