### ISSUE TITLE
Make the mute button hide posts from users that have been muted.

### ISSUE THREAD

**Issue by l0k1-smirenski** [steemit/steemit.com#150]
Almost every other discussion forum on the internet has a function to let a user filter which users they see appear on their feed. The mute setting merely greys out the posts, which effectively only highlights the post.

**Comment by mcifani** [comment]
Your feed tab can serve that purpose as a curation list - posts based on users you choose to follow. You can tailor your following list for specific users content you wish to see.

**Comment by l0k1-smirenski** [comment]
That is very inflexible and limited. I already use it and I still have trouble finding good content. This is why I am building this thing.

**Comment by jcalfee** [comment]
It is intended to hide.  Mute should be leaving out top-level posts on all feeds.  It should be hiding comments too.  I'll have a look this could use some more testing.

**Comment by jcalfee** [comment]
I think this fixes it..  The feeds and comments hide if your muted.  You can still do to muted user's page to see all their activity.  This has not been deployed yet though...

**Comment by l0k1-smirenski** [comment]
Fantastic. Thankyou for the work you are doing. I think the website sits at the head of the spear, in pushing for gaining userbase and investment. I am absolutely ecstatic that something is being done. I will keep working on my own project to make a nice, clean, fast interface for linux users, but what is done with the website will have far more effect on the ecosystem at this point. There is mobile apps in the pipeline, and they will naturally conform to the website. So this is wonderful news to me.

**Comment by l0k1-smirenski** [comment]
It still is a bit quirky. It seems to work perfectly on posts, and on comments on the main comment branch under posts, but it doesn't work consistently on child nodes under the main comment chain.

**Comment by jcalfee** [comment]
Do you have a link and an example of who is muted?

**Comment by l0k1-smirenski** [comment]
An example can be found here:

https://s20.postimg.io/o9oiqg0i3/Screenshot_from_2016_08_30_18_53_29.png

When you mute a user with a post, you don't see the post at all unless you go to the user's blog feed. When you mute a user and they post a comment on a post, their post falls under the little red line at the bottom where also low rep posts get hidden. But when a muted user posts a comment on a comment, or a comment of a comment, etc, they still appear as greyed out like before.
