### ISSUE TITLE
can't remove accidentally-granted upvote on post

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#155]
gives the following:

`Transaction failed: abs_rshares > 50000000 || abs_rshares == 1: voting weight is too small, please accumulate more voting power or steem power`

**Comment by faddat** [comment]
Usually, if I accidentally upvote something,  I can click the upvote button again, and it will be un-up-voted.  But, maybe the post already paid out?  

Or..... Hum.  it is an odd error, that much is certain.

**Comment by roadscape** [comment]
This is a known bug, to be fixed in the next hardfork.

https://github.com/steemit/steem/pull/270

**Comment by roadscape** [comment]
This issue is being tracked in #211
