### ISSUE TITLE
Internal Server Error @ submit_email

### ISSUE THREAD

**Issue by ligi** [steemit/steemit.com#157]
I am trying to register - but I always getting one Internal Server Error after submitting the email. I am using reddit in the first step - not much more info I can provide. Let me know if there is something I can help to track down the error.

**Comment by valzav** [comment]
Thank you for the report, the issue has been fixed by commit #940afbd. Please try again.

**Comment by ligi** [comment]
yes - thanks - could create a account now - was a bit bumpy in the beginning - was complaining that I had to verify my email - but I got no mail - but this might be because the old process was interrupted ..
