### ISSUE TITLE
Throttle Curation Rewards After Posts Reach a Certain Payout Amount

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#158]
The way that content rewards are being incentivized by the current curation system is a big item of discussion. I know there are a lot of ideas being considered. One that has been brought up before (including by Dan) is to enforce some type of limit or throttle on the curation payment once a post reaches a certain payout.

Here is my post outlining the proposal:
https://steemit.com/curation/@timcliff/why-rate-limiting-curation-rewards-is-vitally-important-to-the-future-of-steemit

Also, here is one from another author offering a similar idea:
https://steemit.com/steemit-ideas/@liondani/don-t-remove-curation-rewards-just-stop-them-when-the-post-reach-the-trending-page

Please consider this for a future enhancement. It is my opinion that this is an important update and should be made as soon as possible!

**Comment by roadscape** [comment]
This would need to be a backend change -- https://github.com/steemit/steem
