### ISSUE TITLE
Still problem with cutting words in tables

### ISSUE THREAD

**Issue by lukmarcus** [steemit/steemit.com#159]
There is still problem with that but another kind. Look at article - https://steemit.com/steem/@lukmarcus/dollar-vigilante-jeff-berwick-and-his-steemit-adventure-statistics-and-graphs . There is a table with column "#". Previosly there was word "number" and below "article01", "article02" and so on. Those words were cut in half so I changed it.

**Comment by roadscape** [comment]
How is this different from #146?

Please include a URL where we can see the issue, or sample post data that we can use to reproduce the problem.

**Comment by jcalfee** [comment]
Issue 146 is closed... re-open if this is still a problem.
