### ISSUE TITLE
In Chrome, Edit/Update causes error message

### ISSUE THREAD

**Issue by ScotterMonk** [steemit/steemit.com#163]
When I make a change to my story and click "Update", a red error message comes up:
"comment.last_payout == fc::time_point_sec::min():"
I see it *does* update the story.
![2016-08-22-update-error](https://cloud.githubusercontent.com/assets/21178861/17863565/b39e7d6c-685f-11e6-8852-c390b4627fe3.jpg)

**Comment by roadscape** [comment]
This may be a dupe of #117. Also, our error messages will be more descriptive soon.

> I see it does update the story.

Does it actually update (save) the story, or are you referring to the preview below?

**Comment by roadscape** [comment]
Can't reproduce, closing
