### ISSUE TITLE
youtube iframe performance

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#164]
I was looking at @kennyskitchen's post "THE 40 anarchists you want to be following on Steemit!" for performance.  Basically I narrowed it down to the Youtube iframes.  Removing the iframes showed a much better performance improvement than removing the comments.  

So, this demo appears to do the trick.  It does not load the iframe at all until an the preview image is clicked.  This is the behaviour I see on Facebook.

https://www.sitepoint.com/faster-youtube-embeds-javascript

This will only work for a service that provides a separate URL for am image preview (like YouTube does).

**Comment by roadscape** [comment]
For reference, the post with many embeds:
https://steemit.com/anarchy/@kennyskitchen/the-40-anarchists-you-want-to-be-following-on-steemit

This would be useful to have, but it will require some modification to the rendering chain. HtmlReady is the closest fit for this logic, but with sanitization as the last step we'd need to grow the whitelist. We may want to keep a tight/strict sanitizer earlier in the flow and use a general sanitizer at the end.

Also, embeds come in 2 forms: youtube URLs as well as full iframes. I'm wondering if we need a post pre-processing step where we standardize markup. When an iframe with youtube embed is detected, it would converted back into a plain (standardized) youtube URL. Then later in the chain we only deal with one incoming format and always generate the full iframe (or click-to-play div) ourselves. There are other cases in which a pre-processing step could be useful, such as fixing older posts for backwards-compatibility.

**Comment by jcalfee** [comment]
I'll use a branch...

**Comment by jcalfee** [comment]
I like your reference link..

**Comment by jcalfee** [comment]
43e32326e3405cbc7bc26898fab848ef4cf4b264
