### ISSUE TITLE
Issue with certain Youtube Links

### ISSUE THREAD

**Issue by rgcrypto** [steemit/steemit.com#17]
https://youtu.be/Jj--BIaXwbA could not be embedded because of the "--" within the link.

**Comment by jcalfee** [comment]
Related: https://github.com/jonschlinkert/remarkable/issues/142
I'll find a work-around.

**Comment by jcalfee** [comment]
I turned off the typographer temporarily pending remarkable bug fix.

**Comment by jcalfee** [comment]
Could be a while, so I closed this ticket.

**Comment by jcalfee** [comment]
Videos like yours should work after the next release.

**Comment by rgcrypto** [comment]
thanks!
