### ISSUE TITLE
Vimeo embeds do not work

### ISSUE THREAD

**Issue by hizzvizz** [steemit/steemit.com#171]
Expectation: I have posted on steemit.com and used youtube embeds in this post. The work in the preview and the video plays fine on desktop and mobile browsers.

Result: Here is an embed code I've tried to use from vimeo.

<iframe src="https://player.vimeo.com/video/179213493" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/179213493">Blue Watercolor Drops</a> from <a href="https://vimeo.com/user3713293">Ruben Brito</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

This either shows nothing, or shows a message saying vimeo embeds aren't supported.

**Comment by roadscape** [comment]
Could you please provide a link to the post which exhibits this behavior?

**Comment by hizzvizz** [comment]
I can't actually post with the vimeo embed. I will attach [a screenshot](http://i.imgur.com/undefined.png) to show you the current behavior.

**Comment by jcalfee** [comment]
This commit will let you use this format after the next release:
`<iframe src="https://player.vimeo.com/video/179213493" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

**Comment by hizzvizz** [comment]
Thanks!
