### ISSUE TITLE
Medium-like Editor Integration

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#185]
This [branch](https://github.com/steemit/steemit.com/tree/medium-editor) replaces the Rich Text editor with the [yabwe/medium-editor](https://github.com/yabwe/medium-editor) ..

Packages used:

https://www.npmjs.com/package/react-medium-editor
https://www.npmjs.com/package/medium-editor-insert-plugin

**Comment by JasonMcz** [comment]
When is this gonna get merged to the master branch and get deployed?

**Comment by jcalfee** [comment]
Something to consider: https://app.classeur.io provides a real-time view of markdown and styling together.  Also interesting how they can support uploading of images..

**Comment by sneak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Editor](https://trello.com/c/hF9VD7vj/35-editor)

**Comment by sneak** [comment]
lol editor
