### ISSUE TITLE
vote count beyond 30 days always shows 0

### ISSUE THREAD

**Issue by aaroncox** [steemit/steemit.com#188]
After a posts 30-day payout, the `active_votes` array is returned from the API empty. This causes posts past 30 days to lose their vote counts.

The culprit is [VotesAndComments.jsx - Line #54](https://github.com/steemit/steemit.com/blob/master/app/components/elements/VotesAndComments.jsx#L54).

**Comment by jcalfee** [comment]
When https://github.com/steemit/steem/issues/337 is completely UI updates may be needed.

**Comment by roadscape** [comment]
> There is a build option CLEAR_VOTES that clears votes from consensus that is on by default.
>
> -DCLEAR_VOTES=OFF will keep them around. Not sure if it stores new votes after an archived post though... Will check on that.
>
> Ultimately, this will be moved to a plugin rather than a build option, but it was an easy workaround.

I'll check if we can use this flag on steemit.com nodes

**Comment by Gandalf-the-Grey** [comment]
Checked, used, fixed.
