### ISSUE TITLE
On https://steemit.com/~witnesses it shows on the bottom the 51 witness

### ISSUE THREAD

**Issue by liondani** [steemit/steemit.com#189]
On the https://steemit.com/~witnesses page under the option to vote for a witness besides first 50 it appears the name of the 51 witness!!! 

![screenshot from 2016-08-26 16 38 04](https://cloud.githubusercontent.com/assets/6908400/18007362/6a2216f8-6bac-11e6-8e8f-65d11074ebd1.png)

**Comment by Someguy123** [comment]
Not a bug, but a feature 👍  

People didn't realise who they voted for using that box, so now it shows who you've voted for outside of the list under that box.

**Comment by liondani** [comment]
Oh well! Sorry!
