### ISSUE TITLE
Post missing from user's profile page/feed

### ISSUE THREAD

**Issue by aaroncox** [steemit/steemit.com#190]
I've spent the last hour or so digging around trying to find the cause of this, and it's a mystery to me. 

[mikemacintire](https://steemit.com/@mikemacintire)'s introduceyourself post is missing from his profile feed. It should be the last entry in that feed (currently).

- Profile Page: [https://steemit.com/@mikemacintire](https://steemit.com/@mikemacintire)
- The Missing Post: [https://steemit.com/introduceyourself/@mikemacintire/hi-steemit-i-m-mike-macintire-former-poker-pro-turned-photographer-and-i-m-on-a-mission-to-make-steemit-more-beautiful-drone](https://steemit.com/introduceyourself/@mikemacintire/hi-steemit-i-m-mike-macintire-former-poker-pro-turned-photographer-and-i-m-on-a-mission-to-make-steemit-more-beautiful-drone)

Running curl against the socket returns it as the 20th post:

```
curl https://steemit.com/wspa --data '{"id":1,"method":"get_discussions_by_author_before_date","params":["mikemacintire","","1970-01-01T00:00:00","20"]}'
```

Any clues/ideas as to what's happening here?

**Comment by jcalfee** [comment]
It is there now.. Maybe the needed to rebuild an index on the server.  Can you confirm and close the ticket please?

**Comment by aaroncox** [comment]
There may still be an issue here, but I can't find it. I ran that curl command against 3 different api's and it was missing from all of them. Closing the issue though, since there's nothing to follow.
