### ISSUE TITLE
Please change the tip value to show only SBD value

### ISSUE THREAD

**Issue by hizzvizz** [steemit/steemit.com#193]
Description: As a new user, when I see the tip total for a post I believe I have access to the total amount.  The whitepaper does explain steem power, but seeing a tip value that is half of what is liquid will make some potential new users call the platform a scam.

**Comment by iamsmooth** [comment]
This has always been my view. "You receive a reward of X, plus an additional matching amount of SP" has always seemed like a better way to explain it.

**Comment by roadscape** [comment]
If you consider post rewards as expenses to be reviewed, it does not make sense to underestimate them imo.

On the UI, there will soon be a checkbox to select if you want 50-50 SD/SP or 100% SP rewards. 
The default will be 100% SP. In this case, we would not want to show $0 for all these posts. 
(btw - in steemd, the SD reward is configurable on a continuous scale from 0% to 50%)

That said, there is plenty of room for improvement in communicating these nuances to users. 
Any and all suggestions are welcome. The tricky part is adding more info to the UI without making it even more intimidating ;)

But as far as the original suggestion to show only SBD value, I don't think it will work.
