### ISSUE TITLE
Add support for pastebin iframe embeds

### ISSUE THREAD

**Issue by hizzvizz** [steemit/steemit.com#196]
I am writing a post that references code I've written in processing. I wanted to embed a syntax highlighted code snipped in steemit, but it says the iframe code isn't supported.

http://i.imgur.com/E4NIxsi.png (message shown in post preview)

Here's the embed code I am trying to use.

`<iframe src="//pastebin.com/embed_iframe/BnRQgJtu" style="border:none;width:100%"></iframe>`

**Comment by hizzvizz** [comment]
embed code i am trying to use

<iframe src="//pastebin.com/embed_iframe/BnRQgJtu" style="border:none;width:100%"></iframe>

**Comment by hizzvizz** [comment]
`<iframe src="//pastebin.com/embed_iframe/BnRQgJtu" style="border:none;width:100%"></iframe>`

**Comment by roadscape** [comment]
Consolidating iframe discussion into #271
