### ISSUE TITLE
“Failed to load resource: net::ERR_CONNECTION_REFUSED” for assets, css, app.js and vendor.js in production 

### ISSUE THREAD

**Issue by samargurjar** [steemit/steemit.com#197]
I am setting up a local copy of steemit.com 

Everything works in development environment but when I try to run same in production following steps provided in github repo, it gives error in console : "Failed to load resource: net::ERR_CONNECTION_REFUSED" 
![production-issue](https://cloud.githubusercontent.com/assets/3243302/18048077/be18dd8e-6dfd-11e6-9c9f-1c9cba0abb0a.png)

I am unable to relate this issue to anything. I am relatively new to webpack. Any help will be appreciated.

**Comment by samargurjar** [comment]
https required for localhost. any suggestions on that?

**Comment by jcalfee** [comment]
Do you have steemd setup and listening.  in steemit.com/config/steem-dev.json you might hvae ws://192.168.1.73:8090 then start or configure steemid with `./steemd --rpc-endpoint 127.0.0.1:8090`.  There could be a public steemd endpoint you could use instead (maybe with the piston project) but I don't have that url.

**Comment by jcalfee** [comment]
http://localhost:3002/ should work fine..

**Comment by samargurjar** [comment]
everything works fine in development. also no issues in fetching data from steemd node. Only problem is assets and js are loading with https in the browser.

**Comment by samargurjar** [comment]
ok, so it's not an issue but a feature. I fixed it by removing "content="upgrade-insecure-requests" from  server-html.jsx so that i can test production on local. it's useful for production.
