### ISSUE TITLE
Boost Payment value on posts outside of the first_payout phase seem to reset

### ISSUE THREAD

**Issue by aaroncox** [steemit/steemit.com#199]
I promoted a 2 week old post as an experiment, [transaction here](https://steemd.com/tx/5d08b332d64b678affac1cc214fee95201bc79d1). It was showing at the bottom of the promoted posts section for an hour or so.

After ~1hr - the post itself no longer is displayed on the promoted posts page, and has a "Boost Payment" of 0.000. 

I'm speculating here, but a vote was cast on the post at around the same time it's Boost Payment value went to 0. It's very possible that the vote triggered an update on the post object which reset the Boost Payment.

I'm not sure if this issue belongs here or in steemit/steem, but in the mean time, it might be a good idea to just hide the "Boost Post" button on posts that are no longer in the first payout phase.

**Comment by aaroncox** [comment]
Also I just voted on this post and it disappeared from the list:

https://steemd.com/steem/@inertia/radiator-steem-ruby-api-client

**Comment by aaroncox** [comment]
Other users from chat have also confirmed they are seeing posts disappear from the promoted content page as well.

**Comment by aaroncox** [comment]
Also discovering that you can boost a reply as well, which doesn't do anything except burn the SBD. 

Example URL here: https://steemit.com/tag/@oecp85/re-jesta-psa-don-t-use-the-promote-post-feature-on-a-post-that-s-already-paid-out-20160830t030606580z

**Comment by NateBrune** [comment]
@aaroncox I just added a check to ensure root post.

**Comment by aaroncox** [comment]
I put up a PSA earlier on steemit just to try and warn people of the issue. Please let me know if this wasn't the appropriate action for the situation. 

It didn't seem to get much traction via chat and I was unsure of the proper channels to move this through. My goal was to prevent any unneeded drama as people potentially complained of promoted content halting on older posts. This hopefully limited that from happening slightly.

I'd invite everyone who up voted my PSA post for visibility to remove their votes after we get the situation under control. I wasn't looking for a payout.

**Comment by jcalfee** [comment]
related: https://github.com/steemit/steem/issues/222

**Comment by roadscape** [comment]
This has since been fixed.. the rules are to show "Promote" only during first payout and only on root posts.
