### ISSUE TITLE
Power Up of Vests is not requesting Proper Authority

### ISSUE THREAD

**Issue by bytemaster** [steemit/steemit.com#2]
anyone else having problem powering up their steem? I have 200+ steem listed that I want to power up but it says insufficient funds when i try.

The error is likely misleading, it is probably failing on authority check.

**Comment by jcalfee** [comment]
I was able to run a smaller power up.  Can you tell me which account your using?

**Comment by pheonike** [comment]
The account is pheonike

**Comment by jcalfee** [comment]
I fixed a user interface issue.  It has been deplied to steemit.com.  Please re-open if this is still an issue.
