### ISSUE TITLE
Feature Request: Delete posts or comments

### ISSUE THREAD

**Issue by faidell** [steemit/steemit.com#20]
Right now it is only possible to edit post or comments.

**Comment by jcalfee** [comment]
http://localhost:3002/steem/@jsc/steemit-delete-proposal

**Comment by jcalfee** [comment]
In testing: added delete feature for posts and comments (available only for material with no net rewards and no replies)

**Comment by faidell** [comment]
Great! Thank you so much. Keep up the good work.

**Comment by jcalfee** [comment]
The delete is done.  I use the blockchain operation..  It lets you delete posts with no replies and no positive payouts.  If this is true you will see a Delete link by the Reply and Edit links...

**Comment by asp-learner** [comment]
Hi, I was wondering if there is a possibility to delete a post that has up votes and comments. If not, I was thinking about editing it and writing something like "to delete". Anyway, what would you suggest concerning an artcile that I wrote, has up votes and comments and that I want to remove? Thank you very much.

**Comment by jcalfee** [comment]
This is correct.  I have a few of those too..  If it has a payout it was valuable to someone and the shareholders paid for it.  So as a courtesy leave it if you can stand it and just start looking forward to doing new post that you want to keep.

**Comment by asp-learner** [comment]
Okay, well it has just 4 up votes so no payout ($0.00). I would have liked to remove it ... Thank you for your answer, I think I'll just empty it and leave it there to die peacefully :).

**Comment by asp-learner** [comment]
I thought of something else, asking the up voters to remove their up votes and comments so that I can remove the article. However I couldn't remove my up vote, it seems that after a while one can no longer remove their up vote. Is this correct?
