### ISSUE TITLE
Fix Steem Deposit link from wallet

### ISSUE THREAD

**Issue by Tadasu85** [steemit/steemit.com#201]
The steem deposit button on steemit.com currently pushes back to # which is obviously no good. This needs to be fixed.

**Comment by aaroncox** [comment]
@Tadasu85 It's very possible that # is the proper response, and a modal/popup window should be triggering on click. It's not though, so there's definitely some sort of problem here. 

I don't see any errors immediately in console, but I'll investigate a bit further.

**Comment by jcalfee** [comment]
If there is a websocket problem it can cause the onClick initializers to fail.

**Comment by Tadasu85** [comment]
Dude how the hell is this not fixed yet FFS, Dan and Ned you guys are really not impressing me here this is a SEVERE Issue which has been verified by a number of users!

**Comment by jcalfee** [comment]
fixed

**Comment by Tadasu85** [comment]
Thank you.
