### ISSUE TITLE
implement reblog/repost feature

### ISSUE THREAD

**Issue by valzav** [steemit/steemit.com#203]

**Comment by faddat** [comment]
What's the functionality that this adds, exactly?

**Comment by jcalfee** [comment]
Good question.. Can you make since of this?  This is how I figure it out..

https://github.com/steemit/steem/search?q=reblog

**Comment by faddat** [comment]
aha, I've got it.

It's twitter retweets :).  

Thank you for the link!  I do remember something called reblogs but seriously we're talking mid-late 1990's intarwebs.....

**Comment by roadscape** [comment]
todo:

 - styling: make it blend better
 - users ask for ability to undo Reblog
 - remove from PostSummary? (otherwise, add to mobile view)

**Comment by faddat** [comment]
@roadscape 

Just throwing in my $.02 here:  I'm not so certain about this feature, overall, because it doesn't seem to fit the format.  Possibly needs tweakage, possibly just me being strange.
