### ISSUE TITLE
Unable to convert SBD to STEEM

### ISSUE THREAD

**Issue by Xeldal** [steemit/steemit.com#206]
If you click the link to "convert to STEEM" it links to the trending page and you get the "convert to steem" pop-up over top of this.  If you are logged in with posting key you're obviously unable to convert and when given the prompt to login with active key, doing so does nothing.  You'll be prompted again to login over and over again.

However, if you are logged in with the active key and click "convert to STEEM" the background trending page will not load and you will not be able to enter an amount to convert in the pop up.

using both Chrome and Firefox.

**Comment by jcalfee** [comment]
This should be fixed on next deploy.  The Blocktrades deposit coin selector drop down was effected too.     That is fixed now..
