### ISSUE TITLE
Add support for flat.io iframe embeds

### ISSUE THREAD

**Issue by hizzvizz** [steemit/steemit.com#208]
I tried adding an iframe embed from flat.io and I got an unsupported message. It would be nice to see support for flat.io embeds.

`<iframe src="https://flat.io/score/57c84c518be7d0122effdf95-giant-steps-redux?embed" height="400" width="100%" frameBorder="0" style="border-radius:10px;box-shadow:0px 4px 8px 0px rgba(0,0,0,0.16);"></iframe>`

[unsupported message](http://i.imgur.com/hHnbCHW.png)

**Comment by roadscape** [comment]
Consolidating iframe discussion into #271
