### ISSUE TITLE
Feature: Search Function - Filter by Date/Time Period, Multiple Categories, Exclude Categories

### ISSUE THREAD

**Issue by KrNel** [steemit/steemit.com#209]
If someone wants to find posts from last week, because they were busy, on vacation, etc., they have to scroll and scroll and scroll until they get over thousands of posts to reach it. Right now the ability to find posts is difficult. You can't always just search for interesting posts via the google search, as that is based on specific search parameters. 

The search to find posts we want to curate, would also help if we could search specific tags/categories, and also very helpful would an exclusion search, to show everything except specific tags/categories.

Thank you for considering these enhancements for Steemit. I think it would improve the ability to find useful content that tailors to people's wants, and help with dividing curation in groups who do this. I know it would help me find what I want by not having to see posts I am not interested in.

Peace.

**Comment by roadscape** [comment]
#125 encompasses this request
