### ISSUE TITLE
Feature request: Edit history

### ISSUE THREAD

**Issue by arhag** [steemit/steemit.com#21]
Besides the creation time, if a post/comment was edited, it should have another time that says when the post was last edited (e.g. a link that says "(edited <time>)").

Clicking on that link would flip the post/comment to reveal an edit history UI (for just that post/comment in the context of the larger discussion tree). The edit history UI would allow the user to see a timeline of all edits made to the post/comment, and to jump to any of the snapshot points in the timeline to see the state of the post/comment at that time.

Questions remain regarding whether the JSON metadata at each snapshot time should also be made available in some way, and also whether it should affect the display of the post/comment (for example if a post was marked NSFW and then later the NSFW mark was removed with an edit, should viewing its older version in the edit history replace the images in the post with a click-to-reveal placeholder?). Also, it would be really nice if the status of the votes for the post/comment could also be updated to reflect their state at each snapshot time.

This is a pretty major feature request because it not only requires a lot of new UI work, but it also requires writing new code in steemd to provide the data necessary to the client. I'm thinking steemd would need to be able to retrieve all comment operations of the post/comment and then replay that mini-blockchain (with appropriate content patching code) in order up to the generation requested by the caller before returning that snapshot state (of title, body, json_metadata, and other metadata like last_update) to the caller. Ideally, it would also retrieve all the vote operations related to that post and process them in order up to the last_update time of the requested generation of the post/comment and return the state of votes with the response to the caller.

Finally, back to the client UI level, I think it would be useful if the URL request for a post/comment accepted a generation field (e.g. `?generation=1`). In that case steemit.com would automatically flip the appropriate post/comment to the edit history view and show the requested generation of the post/comment on page load. This would allow people to link to a particular version of an edited post and know that they are linking people to content that they have read and know will not be later changed to something else by the author.

**Comment by roadscape** [comment]
You raise good points/concerns but these issues are beyond the scope of the GUI at this time, so I'm closing the issue.

I agree this would be quite useful, but most of these details will need to be planned on the backend. Yesterday @abitmore was asking if a content_edit_history plugin would be useful.. not sure if he was volunteering or not ;)

**Comment by sneak** [comment]
Idea: We could also just link to the post on a block explorer that has history, as a quick punt for now.

**Comment by abitmore** [comment]
Done some work:
* https://github.com/abitmore/steem/tree/dev-comment-history-plugin
* https://steemit.com/steem/@abit/steemd-comment-edit-history-plugin-first-version

**Comment by abitmore** [comment]
https://steemit.com/steemdata/@furion/this-app-shows-you-edit-history-for-any-post

**Comment by roadscape** [comment]
#1145 and #1146 should cover the concerns of this issue.
