### ISSUE TITLE
Newbie. Can't post anything or upvote an article. [abs_rshares > 50000000]

### ISSUE THREAD

**Issue by ziogio98** [steemit/steemit.com#211]
Hello.

When I try to post or upvote something, that's what I get: "abs_rshares > 50000000 || o.weight == 0: voting weight is too small, please accumulate more voting power or steem power".

My name on the site is ziogio.

**Comment by jcalfee** [comment]
Looks like the price of steem fell so this has made it much tougher.  The quotas are not based on reputation though only on steem power.  You can earn steem power from comments when they get a vote from someone holding some steem power already.

Must be a tough, it has to do with economics.  The witnesses have to store and maintain all this data so we need to be sure the value of the accounts are at a certain point to cover the costs.  Interesting that you were not cut off from comments though.

You wallet has $2.71 and I see you have a reputation score of 44..  I can see your voting power is at 100%: https://steemd.com/@ziogio

What you posted is interesting.  I document it here to explain your experience:
>I want to publish my introduction, but I can't.
>I want to upvote things, but I can't.
>I want to upvote comments, but I can't.
>I can just comment.

I see a potential payout of $10 on your comment about not being able to post.  I think the community solved your issue but it just has not payed out yet.  This is what boosted your rep score:

https://steemit.com/steem/@steemitqa/how-many-people-do-you-follow#@ziogio/re-steemitqa-re-ziogio-re-steemitqa-re-ziogio-re-steemitqa-how-many-people-do-you-follow-20160902t003031687z

Let us know if you can post after payout (maybe 14 more hours)...

**Comment by ziogio98** [comment]
For now the problem is the same. But I'm amazed by the amount of votes in my comment! I'll try again later :)
