### ISSUE TITLE
problem with feeds (following/unfollowing)

### ISSUE THREAD

**Issue by lukmarcus** [steemit/steemit.com#212]
Two kinds of problems:
- when I follow new person I can't see his/hers older articles in feed
- when I unfollow someone I still see his/hers old articles in feed

**Comment by jcalfee** [comment]
That is how it works.. Your feed is a copy of the events after they happen.  I imagine this is faster and easier on the processing side, it does have an interesting side effect on the user interface.  I'm got use to it easily.  I know this is not going to be changed.

I'll close the ticket but you can still reply.

**Comment by lukmarcus** [comment]
But why should I still see articles that I unfollow? There's no sense in that. And if I find someone new to follow I would like to see older posts from my feed.

**Comment by jcalfee** [comment]
Guess you'll have to really trust them before you follow?

**Comment by willkriski** [comment]
Same here - unfollow should unfollow, pretty simple as a user concept maybe not for blockchain?
