### ISSUE TITLE
New accounts cannot be created

### ISSUE THREAD

**Issue by aaroncox** [steemit/steemit.com#213]
```
10 assert_exception: Assert Exception o.fee >= wso.median_props.account_creation_fee: Insufficient Fee: 6.000 STEEM required, 5.000 STEEM provided {"f":"6.000 STEEM","p":"5.000 STEEM"} th_a
```

Got a report from a user that this is what's happening when they attempt to signup. They are unable to create a new account on steemit.com right now.

**Comment by aaroncox** [comment]
User now reports that it's working again - not sure if you guys resolved it or if this could be an intermittent problem.

**Comment by valzav** [comment]
resolved - it now deposits 10 STEEM instead of 5

**Comment by aaroncox** [comment]
Thanks @valzav!
