### ISSUE TITLE
update package.json to install react-foundation-components from NPM

### ISSUE THREAD

**Issue by f3rnando** [steemit/steemit.com#214]
react-foundation-components is already an npm package.

the way its installed via github is discontinued so it wont work as of now.

`    "react-foundation-components": "^0.11.2",`

instead of
`
    "react-foundation-components": "git+https://github.com/valzav/react-foundation-components.git#lib",`

**Comment by svk31** [comment]
It uses a github repo because we've made modification to the package and the original package was more or less abandoned.

Since when is installing via github link discontinued, Node v7 ?

**Comment by f3rnando** [comment]
Ok, this is odd, I retried the process and it worked. May be a connection shortage? Im pretty sure I was usgin Node v6.5.0 with NVM. Also, the deprecation of dumb http is quite old, does github still supports it despite their warning and deadline? Nevermind.

Ignore this issue, I'll close it in a few minutes. Excuse me for wasting your time :P
