### ISSUE TITLE
Reducing subjectively excessive payouts is a valid reason for downvoting/flagging

### ISSUE THREAD

**Issue by iamsmooth** [steemit/steemit.com#215]
According to the white paper and my understanding of the system design, subjective value and preventing of various forms of voting abuse and excess payments require that users down vote content when they feel that payouts are excessive or in general contrary to the good of the system.

This is contradicted by the implementation of #186, which was states only the following reasons for flagging:

Fraud or Plagiarism
Hate Speech or Internet Trolling
Intentional miss-categorized content or Spam

This conflict should be resolved by one of the following:
1. The white paper and stated expectations of the blockchain designers should be revised to indicate that downvoting for excess payouts is not expected behavior
2. The flag text should be removed or revised to agree with the blockchain design
3. A separate downvote UI option should be added to allow downvoting for payout control without expressing a view on the content being fraud, plagiarism, hate speech, etc.

**Comment by roadscape** [comment]
Is there any way to phrase this reason in such a way that it doesn't become a blanket?

**Comment by iamsmooth** [comment]
Maybe suggested reasons not to flag (disagree with the ideas expressed in the post, etc.) instead of trying to enumerate reasons to flag?

**Comment by roadscape** [comment]
We are also considering an approach which allows the user to leave a reason for flagging.

There could be several canned response options plus a field for "Other", and you would have to select one, or enter in a custom message for "Other" (i.e. mandatory comment on downvote)

Alternatively, we could keep the current list of reasons, and add an "Other" field. No comment would be published unless you entered something into the optional text field. This would leave some room for flexibility while allowing the community to maintain its own standards.

**Comment by iamsmooth** [comment]
"This would leave some room for flexibility while allowing the community to maintain its own standards"

The idea of the community maintaining its own standards is not supported by a canned list maintained by a user interface developer that is suggestive of a certain standard (and one which, as I suggested above, is apparently inconsistent with the white paper and public statements from platform designers). That said, the user interface is at least open source, so in that sense the community does indeed have control over the list.

**Comment by roadscape** [comment]
If we're going to implement multiple choice, I propose this wording:

> Flagging a post can remove rewards and make this material less visible. 
> Please indicate the reason for flagging:

> - Fraud or Plagiarism
> - Hate Speech or Internet Trolling
> - Intentional miscategorized content or Spam
> - Other ____________________________

**Comment by wmbutler** [comment]
Dan's reasoning for his downvote was written clearly in a follow up post. He stated that he felt the post was 'overvalued'. I'd suggest that the whitepaper be amended and that this reason be added to your list above if this is truly a legitimate reason for downvoting.

Otherwise, it should be discussed and either endorsed or thrown out.

**Comment by roadscape** [comment]
I think we all agree it's a legitimate reason.

> Is there any way to phrase this reason in such a way that it doesn't become a blanket?

How about a minimum threshold? e.g. "excessive payout" should only be used for posts above $100

**Comment by Gandalf-the-Grey** [comment]
Single picture (not even original content) and "LOL!" as a comment is a kind of post for which even $1 could be treated as an "excessive payout"

**Comment by roadscape** [comment]
"Excessive payout" is the single most subjective reason for flagging. Anything can be called excessive. It can be easily abused unless there's accountability.. which is why the ideal solution will be to automatically add a comment upon flagging. A custom message could be optional.

**Comment by roadscape** [comment]
e.g.

> Flagging a post can remove rewards and make this material less visible. 

> Please select the reason for flagging: (it will be public)

> [ ] Fraud or Plagiarism
> [ ] Hate Speech or Internet Trolling
> [ ] Intentional miscategorized content or Spam
> [ ] Excessive payout

> Comment: _________________________________________________ (optional)

>   [ OK ]   -   [ cancel ]

**Comment by iamsmooth** [comment]
> "Excessive payout" is the single most subjective reason for flagging. Anything can be called excessive. It can be easily abused unless there's accountability.. which is why the ideal solution will be to automatically add a comment upon flagging. A custom message could be optional.

I think if this is the case we are back to updating the white paper and asking your founders why they use that reason. It is an inherent part of the design as I understand it that value is subjective and therefore excessive payouts (i.e. in excess of value added to the platform) is also subjective.

The list included in your reply previous to this one satisfies my original concern in creating this issue.

**Comment by faddat** [comment]
I always leave a reason when downvoting, and I like the idea of a downvote "reason".  If nothing else, it's common courtesy to the noobs who don't yet know community standards.

**Comment by pfunks** [comment]
Thank you for creating this issue smooth. The baggage of a "flag" definitely has caused confusion and a narrowing of the concept of downvoting from its original width in the minds of the majority of users.

**Comment by TimCliff** [comment]
Would it be possible to split flagging and down-voting into two separate things? Flagging would be any of the negative/abusive things in the list (Fraud, Plagiarism, Spam, Hate Speech, Trolling, etc.). Down-voting would just be along the lines of a thumbs down. (I didn't like it, the author did a bad job, the post is paying too much, etc.). It could be setup such that any flag automatically down-voted, but a down-vote does not automatically flag.

**Comment by sneak** [comment]
That's just UI then, is it not? Or do you propose removing a downvote's teeth?

**Comment by CraigWilliams** [comment]
Flagging effects a users reputation. This is a good thing when a user is posting content that should be flagged but when it is content that someone disagrees with or believes the post is earning too much money, it effects the user as a whole and not just the post in question.

Flagging and down voting are two distinct operations. We need an actual down vote button that only effects the post or comment being down voted.

I have experienced this directly. Someone thought I was spamming and flagged two of my comments. My reputation went to zero. It is not easy to recover from that.

**Comment by wmbutler** [comment]
If there is a need to regulate the moral implications of an "overpaid post" I'm afraid that will need to be handled in the algorithm. That particular aspect of Steemit should not be left to vigilantes.

**Comment by iamsmooth** [comment]
@CraigWilliams Reducing a high payout with a flag/downvote will virtually never negatively affect reputation. It will just reduce the amount of reputation increase. (There are some strange edge cases where it could in theory, but this is not really worth considering, and certainly not worth designing around.)

This is a different case from someone thinking that your post is entirely worthless/abuse and should be downvoted below zero payout (which could indeed reduce reputation).

@wmbutler Everything in Steem is subjective. There are no moral implications aside from what participants create in their own minds, nor is there any central authority to impose any particular morality. If there is a function in the system that allows people to down vote, the interpretation of that function can not and should not be decided by a UI designer.

**Comment by TimCliff** [comment]
In reference to sneak's comment: That's just UI then, is it not? Or do you propose removing a downvote's teeth?

I agree this is more than a UI change. I opened a Steem issue: https://github.com/steemit/steem/issues/500. Does this seem like the right thing to do?

**Comment by TimCliff** [comment]
Linking two related pull requests to the issue:

https://github.com/steemit/steemit.com/pull/952
Changed "The flag should be used for the following" to "Some common reasons to flag"

https://github.com/steemit/steemit.com/pull/957
Added "Inappropriate rewards distribution" to the list of reasons

**Comment by TimCliff** [comment]
@iamsmooth - based on the latest changes that were deployed to production today, is the original issue that this was created for resolved? (Should we close the issue?)

@roadscape - your suggestion to add a reason for downvoting is still a good idea (IMO). This would probably be considered more of an enhancement item at this point though.

All - There is also https://github.com/steemit/steem/issues/500 open to 'split' downvoting vs. flagging, such that being flagged is reserved for various forms of abuse. I don't know if this proposal is the final/best solution, but I do think we need to make _some_ change to not call what people are doing today (downvoting to reduce rewards) "flagging".

A simpler change (like what is being proposed in https://github.com/steemit/steemit.com/issues/938) to just get rid of 'flag' and go back to upvote/downvote would be another good option.

**Comment by roadscape** [comment]
Now that "Disagreement on rewards" is in the dialog, we can close this issue.

In the future, it would be good to have flagging be a non-voting operation which would simply put the post into a form of public review queue. The priority/weight of the flag could be based on the flagger's reputation. Users could downvote without flagging, and the review queue would just serve as a useful signal.

**Comment by iamsmooth** [comment]
@TimCliff yes I agree this particular issue is resolved

@roadscape I like the idea of a flagged-post queue. It could also be made part of a feed or feed-like function so those interested in serving as a sort of moderator could subscribe and see those posts to consider downvoting them.

**Comment by abitmore** [comment]
So we'll need to use other tools e.g. cli if really want to downvote a post?

**Comment by TimCliff** [comment]
@abitmore - If this change were to be made, I think that both flagging and downvoting would probably both be supported though the UI. It would basically make the downvote (which reduces post rewards, and does not necessarily indicate abuse) something separate from flagging. If posts were flagged (due to abuse) then the community would be able to review the flagged posts, and downvote accordingly.

**Comment by CraigWilliams** [comment]
This account is the perfect example of why there should be NO down vote option. This account has no posts or comments but down votes ad nauseam. https://steemd.com/@asshole

**Comment by TimCliff** [comment]
@CraigWilliams - Removing the option to downvote entirely would be a really bad idea, because there would be no way to combat users who were abusing the system.

This pull request should help with the specific issue you are reporting regarding the @asshole account.

https://github.com/steemit/steemit.com/pull/1039

**Comment by abitmore** [comment]
>It would basically make the downvote (which reduces post rewards, and does not necessarily indicate abuse) something separate from flagging.

@TimCliff @roadscape I like it. Implement flagging with `custom_json_op`, it can even have a reason attached. By the way, using similar mechanism, labeling can be implemented -- labels added by curators to posts, just like tags added by authors, which imo would be interesting, at least, better than only a upvote button.

**Comment by develCuy** [comment]
@abitmore do you know if labeling is implemented already?
