### ISSUE TITLE
Strange issue when I tried quoting another post

### ISSUE THREAD

**Issue by aaroncox** [steemit/steemit.com#216]
Look at the first response I made to this comment. The first one is the one that's a little bit crazy.

https://steemit.com/tag/@shenanigator/re-jesta-proposal-a-potential-alternative-to-voting-power-voting-tokens-20160903t033104254z

I responded to this comment, and ended up copy/pasting from the OP into my reply. Each snippet of text that I copied, I added `>` in front of to act like a quote to respond to. As I was creating the post, everything looked fine in preview, but when I hit submit, it looks like it added in a diff. 

I left the post with the broken format alone specifically to report this, and wrote the 2nd comment so that the author I was responding to could have a response.

Any idea why copying out of a comment into a response would cause something like this?

**Comment by aaroncox** [comment]
Just happened in another comment that I brought in from an external plan text editor. I think there's a combination of characters triggering it, I've been testing but haven't been able to reproduce it consistently.

**Comment by aaroncox** [comment]
Was happening to sigmajin too, and he was also having problems reproducing it.

https://steemit.com/tag/@jesta/re-sigmajin-re-jesta-re-shenanigator-re-jesta-proposal-a-potential-alternative-to-voting-power-voting-tokens-20160903t043851866z

**Comment by roadscape** [comment]
This has happened before.. IIRC, it looked as though the quotes were interfering with the diff/patch syntax, but in reality it was related to forking. #234 may help us narrow this down.

**Comment by roadscape** [comment]
Potentially related to #37

**Comment by aaroncox** [comment]
I haven't experienced this (or seen it's end result) in a few weeks. Assuming it's been resolved in one of the other various editor changes.
