### ISSUE TITLE
Mobile voting - unable to cast vote with weight slider

### ISSUE THREAD

**Issue by aaroncox** [steemit/steemit.com#219]
Got a report via steemit.chat from a user who is having problems voting on a mobile device.

> I use Iphone 6 and when I up vote, I see the meter come up, and I click to up vote, but the up vote doesn't get posted it just stays there and nothing happens. I have restarted my phone and the browser and it still does it

It sounds like the touch event isn't hitting the vote button or something.

> No errors nothing comes up.... it just shows the up vote arrow darker when clicked and it just stays there with the bar until you hit the x to close it

But oddly enough the close button does work.

**Comment by Tadasu85** [comment]
How is this not fixed yet! Seriously guys its flipping UI Again!

**Comment by valzav** [comment]
I can replicate it now - looks like it only happens in Chrome.

**Comment by Tadasu85** [comment]
Cool thank you, can you guys fix it?

**Comment by valzav** [comment]
Very strange issue - after I refreshed the page I can no longer replicate this, maybe it was fixed by recent deploy. Could you ask this forum guy if it's still an issue and in what browser this happens?

**Comment by aaroncox** [comment]
@valzav Got an update from rocket.chat for ya from the user:

> I am on iphone 6 and am using Safari browser. When I go to vote, if not logged in, it sends me to logon page, I logon on and the Vote works, BUT if I try to up vote a different article now, the vote slider pops up, and I can click on the vote button, and it goes dark but NO VOTE goes through, and the slider bar just stays there. It still happens, at least to me. I just checked.

Seems as of today, still experiencing problems.

**Comment by roadscape** [comment]
Any new reports?

**Comment by aaroncox** [comment]
I haven't heard anything and TBH don't remember who it was. Closing and will reopen if I hear more.
