### ISSUE TITLE
Mixed content bug (retrieving images from HTTP allowed)

### ISSUE THREAD

**Issue by arhag** [steemit/steemit.com#22]
[This bug](https://steemit.com/steemit/@ranko-k/steemit-is-not-secure) still exists.

For some reason, despite the fact that the image link to the Reddit alien image in that thread is supposed to be HTTPS, the browser downloads it via HTTP. This causes the web page to have mixed content and so the green lock icon disappears.

Ideally, it should not be possible to request images over HTTP. Apparently, replacing "http://" in all image links with "https://" or "//" is not enough to solve the problem.

**Comment by arhag** [comment]
Possible solutions can be found here: 
https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content?hl=en

See the "Upgrade insecure requests" section or if necessary the "Blocking all mixed content" section.

**Comment by jcalfee** [comment]
What is the exact problem?  I'm guessing it is the reddit image.. We did converted http to https then use this as the image src link:
 https://www.product-reviews.net/wp-content/uploads/reddit-maintenance.jpg

Look at your address bar when you try to load that under https, it re-directs to the http version..

Reddit response with this: 
> Location:http://www.product-reviews.net/wp-content/uploads/reddit-maintenance.jpg

**Comment by jcalfee** [comment]
I'll test the CSP meta tag on the next release.. thanks

**Comment by abitmore** [comment]
I guess redirecting from https to http is allowed by the browser? Don't know if it causes security issues..

**Comment by jcalfee** [comment]
Allowed by default .. The CSP will turn that off but only for browsers that support it.

**Comment by arhag** [comment]
I don't know about your browser, but for me apparently despite the new
```
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```
the issue still hasn't been solved.


One thing I am wondering is if React is later dynamically adding it and that is why the browser isn't respecting it? I think it would be better if the steemit.com server itself included
```
Content-Security-Policy: upgrade-insecure-requests
```
in the response headers of the served web page.

**Comment by jcalfee** [comment]
test link: https://steemit.com/test/@john-kimmel/ipfs-image-link-test

**Comment by jcalfee** [comment]
The Content-Security-Policy:upgrade-insecure-requests in the request headers.. Firefox correctly blocks the images in the test link comment but chrome does not.

**Comment by arhag** [comment]
What about trying

**Comment by roadscape** [comment]
These issues should all be resolved, please reopen if this is not the case. We are using CSP header whitelists and there should be no more HTTP requests for anything.
