### ISSUE TITLE
Ugly scary looking late voting error message

### ISSUE THREAD

**Issue by kurtr** [steemit/steemit.com#222]
## Hi,

I just tried to comment on an old post for the first time and this error message appears both as a notification and under the editor.

     db().calculate_discussion_payout_time( *parent ) != fc::time_point_sec::maximum(): discussion is frozen

Heres a screenshot...

![steemiterror](https://cloud.githubusercontent.com/assets/1468721/18282850/25f2a42e-7463-11e6-837e-f99d0870f40d.png)

I really think this really needs to be replaced with a friendly error message stating why you can't comment. I realised what it was immediatley but I think it will intimidate new users who arn't technical.

Thanks

**Comment by jcalfee** [comment]
@mvandeberg

**Comment by jcalfee** [comment]
@mvandeberg please make sure this is included in your project to update assert messages... tq

**Comment by jcalfee** [comment]
Here is the full error from the websocket: `{"id":14,"error":{"code":1,"message":"10 assert_exception: Assert Exception\ndb().calculate_discussion_payout_time( *parent ) != fc::time_point_sec::maximum(): discussion is frozen\n    {}\n    th_a  steem_evaluator.cpp:283 do_apply\n\n...`

I could find the last `: ` in the first line and grab the text after it.  In this case only `discussion is frozen` would be displayed.  I think that is probably the best thing to do, I had requested a separate variable in steemd for that error but that did not go anywhere (https://github.com/steemit/steem/issues/86).

**Comment by kurtr** [comment]
Thats a good idea - minimal effort and it won't freak out any users. Worst case one or two people search for `"discussion is frozen"`.

**Comment by mvandeberg** [comment]
The problem on the backend is the message FC_ASSERT produces includes the failed expression. We would have to modify FC_ASSERT and how fc exceptions are handled to support both the debug message and a more user friendly message. The debug message is invaluable for backend development.
