### ISSUE TITLE
Add ability to transfer to savings account

### ISSUE THREAD

**Issue by valzav** [steemit/steemit.com#223]

**Comment by jcalfee** [comment]
https://github.com/steemit/steem/issues/350

**Comment by jcalfee** [comment]
Saving ops need to be added to transaction history: https://github.com/steemit/steem/issues/377

**Comment by sneak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [transfer to savings](https://trello.com/c/mIyEhiGO/55-transfer-to-savings)
