### ISSUE TITLE
Allow a users reply list entries to link to an anchor that scrolls to their reply.

### ISSUE THREAD

**Issue by hizzvizz** [steemit/steemit.com#227]
Current Behavior: Clicking on one of my replies takes me the post I replied to. I would need to search or scroll to get to my specific reply.

Expectation: When I click on a reply from my profile page, I would like the link to take me to my reply message at the bottom of the post so I can see who commented.

**Comment by jcalfee** [comment]
Our anchor links were correct but had an extra `#` so I fixed that.. That does not fix the issue.  The other issue appears to be that the react-router is trying to use the `#` for state in its urls.  A suggestion is to use `Router.HistoryLocation` and clean urls instead.

@val @roadscape can you review this please:

http://stackoverflow.com/questions/28893855/how-to-use-normal-anchor-links-with-react-router

**Comment by roadscape** [comment]
Had to add the `#` back in 3436cbad0eddcc52591fecd9d9d410ecbecd44cf because of #124 

@hizzvizz could you please include details (and URLs) so we can reproduce this bug?

When I click a specific reply or comment in someone's profile, it takes me to that page and scrolls down to the post.. I don't see the issue

**Comment by jcalfee** [comment]
Try clicking on replies here: https://steemit.com/@dantheman/recent-replies
* you should see that it does not scroll down
* reload: same thing, still will not scroll down
* type over the last z in the address url and press enter: it scrolls!

Load a reply link in a new tab.. it scrolls

**Comment by roadscape** [comment]
This has to do with comments not being loaded when `componentDidMount` in Post.jsx fires. I confirmed that it cannot find the element to scroll to.

However, if you hit the back button then click on the same reply, it will work as expected.
