### ISSUE TITLE
npm err!!

### ISSUE THREAD

**Issue by name55** [steemit/steemit.com#230]
When i input `npm start`，

`root@iZ284rh8u3eZ:~/workspace/steemit.com# npm start

> Steemit.com@1.0.0 start /root/workspace/steemit.com
> babel-node ./webpack/dev-server.js

`webpack-dev-server` listening on port 3001
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/root/workspace/steemit.com/tmp/webpack-stats-dev.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Compiler.exports.default (write-stats.js:44:8)
    at Compiler.applyPlugins (/root/workspace/steemit.com/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/root/workspace/steemit.com/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/root/workspace/steemit.com/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/root/workspace/steemit.com/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/root/workspace/steemit.com/node_modules/webpack/lib/Compiler.js:58:19)
    at /root/workspace/steemit.com/node_modules/webpack/lib/Compiler.js:275:11

npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "/root/.nvm/versions/node/v6.5.0/bin/node" "/root/.nvm/versions/node/v6.5.0/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! Steemit.com@1.0.0 start: `babel-node ./webpack/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Steemit.com@1.0.0 start script 'babel-node ./webpack/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Steemit.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./webpack/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Steemit.com
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Steemit.com
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/workspace/steemit.com/npm-debug.log
root@iZ284rh8u3eZ:~/workspace/steemit.com# `

**Comment by name55** [comment]
I'm sure node.js and npm is the latest version.

**Comment by f3rnando** [comment]
1- You shouldn't run it as root.
2- You have to create the tmp dir and make it writeable by the user running the app. (avoid using root)

**Comment by roadscape** [comment]
@name55 were you able to resolve this issue?

**Comment by name55** [comment]
@roadscape no,problem is still not resolved. i've run it correctly before,
I do not know whether it is the problem of  a new version

**Comment by roadscape** [comment]
Have you updated the repository recently? Some changes were made to where `webpack-stats-dev.json` resides.

Otherwise as @f3rnando said it looks like a permissions issue.

**Comment by name55** [comment]
@roadscape This is my dev-server.js,is it correcet?
`process.env.BABEL_ENV = 'browser';
process.env.NODE_ENV = 'development';

import Koa from 'koa';
import webpack from 'webpack';

import config from './dev.config';

const app = new Koa();
const compiler = webpack(config.webpack);

app.use(require('koa-webpack-dev-middleware')(compiler, config.server.options));
app.use(require('koa-webpack-hot-middleware')(compiler));

app.listen(config.server.port, '0.0.0.0', () => {
    console.log('`webpack-dev-server` listening on port %s', config.server.port);
});
`

**Comment by bigbhowell** [comment]
I was having this issue also and recent updates to the repo have solved the problem. In my opinion this **_issue can be closed_**.

**Comment by mcifani** [comment]
Closing this issue appears to be addressed/no longer present.
