### ISSUE TITLE
Error when commenting on a post

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#231]
I just got this error when trying to comment on a post. 
trx.ref_block_prefix == tapos_block_summary.block_id._hash[1]: 

This was the post that I tried to comment on:
https://steemit.com/steemit/@imarealboy777/5qr5nw-the-one-feature-steemit-needs-more-than-any-other

**Comment by roadscape** [comment]
The assert relates to TaPoS:

     const auto& tapos_block_summary = block_summary_id_type( trx.ref_block_num )(*this);
     //Verify TaPoS block summary has correct ID prefix, and that this block's time is not past the expiration
     FC_ASSERT( trx.ref_block_prefix == tapos_block_summary.block_id._hash[1],
                "", ("trx.ref_block_prefix", trx.ref_block_prefix)
                ("tapos_block_summary",tapos_block_summary.block_id._hash[1]));

This means one of our nodes was on a fork.. I've created a separate issue to try to catch problems like this earlier: #234
