### ISSUE TITLE
API calls needed to fetch next "comments" and "replies" (similar to the get_discussion_by_xxx).

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#236]
>The Feed page, the Blog page, [--], all have an auto-scroll to update the content and increase the page length. But, the Comments page does not. 
https://github.com/steemit/steemit.com/issues/232

**Comment by jcalfee** [comment]
>The Feed page, the Blog page, the Replies page, all have an auto-scroll to update the content and increase the page length. But, the Comments page does not.

**Comment by roadscape** [comment]
Seems like this was meant for the `steem` repository; I have left some notes here: #232
