### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#238]
> getting this error when trying to reply in comments: TypeError: Cannot read property 'get' of undefined
> 
> these are the console errors, I just posted, however when I went to update the comment it gave the same error as previously. Here are the console errors: 
> 
> app.eaa683fdf674f1fdc8f4.js:19 c: uncaught TypeError: Cannot read property 'get' of undefined(…)e @ app.eaa683fdf674f1fdc8f4.js:19n @ app.eaa683fdf674f1fdc8f4.js:19n @ app.eaa683fdf674f1fdc8f4.js:19D @ app.eaa683fdf674f1fdc8f4.js:19i @ app.eaa683fdf674f1fdc8f4.js:19n @ app.eaa683fdf674f1fdc8f4.js:19n @ app.eaa683fdf674f1fdc8f4.js:19D @ app.eaa683fdf674f1fdc8f4.js:19i @ app.eaa683fdf674f1fdc8f4.js:19n @ app.eaa683fdf674f1fdc8f4.js:19s @ app.eaa683fdf674f1fdc8f4.js:19d @ app.eaa683fdf674f1fdc8f4.js:19E @ app.eaa683fdf674f1fdc8f4.js:19i @ app.eaa683fdf674f1fdc8f4.js:19n @ app.eaa683fdf674f1fdc8f4.js:19s @ app.eaa683fdf674f1fdc8f4.js:19S @ app.eaa683fdf674f1fdc8f4.js:19i @ app.eaa683fdf674f1fdc8f4.js:19n @ app.eaa683fdf674f1fdc8f4.js:19n @ app.eaa683fdf674f1fdc8f4.js:19resolve @ app.eaa683fdf674f1fdc8f4.js:19(anonymous function) @ app.eaa683fdf674f1fdc8f4.js:19(anonymous function) @ app.eaa683fdf674f1fdc8f4.js:26e @ app.eaa683fdf674f1fdc8f4.js:26(anonymous function) @ app.eaa683fdf674f1fdc8f4.js:63reply @ app.eaa683fdf674f1fdc8f4.js:13(anonymous function) @ app.eaa683fdf674f1fdc8f4.js:13v @ app.eaa683fdf674f1fdc8f4.js:62u @ app.eaa683fdf674f1fdc8f4.js:62(anonymous function) @ app.eaa683fdf674f1fdc8f4.js:62(anonymous function) @ app.eaa683fdf674f1fdc8f4.js:62r @ app.eaa683fdf674f1fdc8f4.js:8a @ app.eaa683fdf674f1fdc8f4.js:8s @ app.eaa683fdf674f1fdc8f4.js:8f @ app.eaa683fdf674f1fdc8f4.js:5h @ app.eaa683fdf674f1fdc8f4.js:5n @ app.eaa683fdf674f1fdc8f4.js:11processEventQueue @ app.eaa683fdf674f1fdc8f4.js:5r @ app.eaa683fdf674f1fdc8f4.js:17handleTopLevel @ app.eaa683fdf674f1fdc8f4.js:17o @ app.eaa683fdf674f1fdc8f4.js:17perform @ app.eaa683fdf674f1fdc8f4.js:5batchedUpdates @ app.eaa683fdf674f1fdc8f4.js:12o @ app.eaa683fdf674f1fdc8f4.js:3dispatchEvent @ app.eaa683fdf674f1fdc8f4.js:17
> app.eaa683fdf674f1fdc8f4.js:36 **TransactionSage** TypeError: Cannot read property 'get' of undefined(…)

I've seen other reports of the "Cannot read property 'get' of undefined" issue, with the suggestion to log out/in or try incognito mode.

I could only find one reference to **TransactionSage**(sic): app/redux/TransactionSaga.js, function `broadcastOperation`, line 118, where it appears to have been trying to find a signing key.

**Comment by jcalfee** [comment]
Sounds like they get stuck and have to log out and log back in?  The .get methods in findSigningKey look very safe to me, as long as we have state.user.get('current').  If current is null it will prompt you to login.  Can they recreate this and give me some instructions so I can re-create the issue?

**Comment by roadscape** [comment]
> cryptogee:
> app.eaa683fdf674f1fdc8f4.js:36 TransactionSage TypeError: Cannot read property 'get' of undefined
at https://steemit.com/assets/app.eaa683fdf674f1fdc8f4.js:14:8061
at i (https://steemit.com/assets/app.eaa683fdf674f1fdc8f4.js:26:6573)
at s._invoke (https://steemit.com/assets/app.eaa683fdf674f1fdc8f4.js:26:7975)
at s.t.(anonymous function) [as next] (https://steemit.com/assets/app.eaa683fdf674f1fdc8f4.js:26:6752)
at n (https://steemit.com/assets/app.eaa683fdf674f1fdc8f4.js:19:412)
at n (https://steemit.com/assets/app.eaa683fdf674f1fdc8f4.js:19:757)
at D (https://steemit.com/assets/app.eaa683fdf674f1fdc8f4.js:19:3689)
at i (https://steemit.com/assets/app.eaa683fdf674f1fdc8f4.js:19:1499)
at n (https://steemit.com/assets/app.eaa683fdf674f1fdc8f4.js:19:438)
at n (https://steemit.com/assets/app.eaa683fdf674f1fdc8f4.js:19:757)

> only seems to be doing it when I try and update a comment now...also am being asked for username and posting key every time I want to vote/comment

> Having to login and sign for every single action

> pfunk: even after logging in via the upper-right link?
> afaik those individual transaction logins no longer give you the option to stay signed in

> cryptogee: Ah, ok, I'll try that login. Thanks.

**Comment by roadscape** [comment]
> FYI, the top right hand sign in, is not keeping me signed in...

**Comment by roadscape** [comment]
I was able to replicate this...

1) Open an incognito window
2) Navigate to a [test post](http://localhost:3002/test/@test-safari/test-spam) and submit a reply (a login dialog will pop up)
3) Edit your reply and click 'Update Post'. You will receive an error

![image](https://cloud.githubusercontent.com/assets/5168676/19895452/3a1db3b8-a027-11e6-858b-f899108a95f0.png)

```
findSigningKey: uncaught TypeError: Cannot read property 'get' of undefined
    at findSigningKey$ (assets/app.ed33ba689c0c02649fa8.js:44139:52)
    at tryCatch (assets/app.ed33ba689c0c02649fa8.js:87029:41)
    at Generator.invoke [as _invoke] (assets/app.ed33ba689c0c02649fa8.js:87303:23)
    at Generator.prototype.(anonymous function) [as next] (assets/app.ed33ba689c0c02649fa8.js:87062:22)
    at next (assets/app.ed33ba689c0c02649fa8.js:54551:62)
    at currCb (assets/app.ed33ba689c0c02649fa8.js:54606:8)
    at runSelectEffect (assets/app.ed33ba689c0c02649fa8.js:54924:8)
    at runEffect (assets/app.ed33ba689c0c02649fa8.js:54654:849)
    at next (assets/app.ed33ba689c0c02649fa8.js:54553:10)
    at currCb (assets/app.ed33ba689c0c02649fa8.js:54606:8)
```
