### ISSUE TITLE
Block Button Feature

### ISSUE THREAD

**Issue by KingArbin** [steemit/steemit.com#239]
I suggest adding a Block Button to Steemit to prevent abusive users from flagging the content of users they don't like. It wouldn't remove already obtained flags as people would abuse that as well, but it would prevent someone that is deliberately flagging all content a user writes. Myself, like many others, are experiencing this with a certain user. I am sure your aware of him by now.

I would just like to block him to stop him from responding to my content, voting on it, seeing it, and most important, flagging it. This would be helpful to many people.

Block Button

What it can do: Restrict a users access from seeing another users posts or taking action on them.

What it Can't do: Remove any current action already taken

**Comment by roadscape** [comment]
See also relevant comments in https://github.com/steemit/steem/issues/382

**Comment by roadscape** [comment]
We cannot prevent users (on the blockchain level) from flagging specific posts as this could itself could be abused. Same goes for commenting. However, we do have plans for optional moderation-type features as well as more powerful ignore functionality.
