### ISSUE TITLE
IPad and new txt editor

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#24]
I've got this MSG from the Facebook page of Steemit. 

"Ever since the new post editor was introduced, I have been unable to post anything or reply to anyone. Unlike the old editor, which worked fine with iPad2, the new editor does not work at all. It will not let me enter or cut and paste any text. 

As far as I am concerned Steemit is now almost completely useless (only thing it lets me do is up or downvote posts).

Still it is early days and maybe somebody will fix this and actually allow iPad users to join in once more?"

**Comment by bmann** [comment]
Works for me on Safari on iPad as of today.
