### ISSUE TITLE
Notifications / Alerts for Replies

### ISSUE THREAD

**Issue by KrNel** [steemit/steemit.com#241]
Can this be added? That way we know when we have feedback to our own content, and other comments we have left.

Thank you. Peace.

**Comment by valzav** [comment]
Yes this is on our roadmap, this requires a lot of development efforts - this is way it gets postponed for so long, but eventually we will be there.
I will close this issue because it duplicates this one https://github.com/steemit/steemit.com/issues/72

**Comment by sneak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notifications](https://trello.com/c/jDODakyR/19-notifications)
