### ISSUE TITLE
Steem.io broken links

### ISSUE THREAD

**Issue by goatandsheep** [steemit/steemit.com#248]
Legal Pages for:
- privacy agreement
- user agreement

**Comment by nedsteem** [comment]
Hello!  Please find these available on the steemit.com website under the top right drop down menu

**Comment by goatandsheep** [comment]
Good point! They're there, but terms of service is called "Buy Steem" and the footer links lead to the home page.

**Comment by sneak** [comment]
Both bottom links (Privacy Policy and TOS) work fine for me in Chrome 53.0.2785.101 on OSX.

**Comment by nedsteem** [comment]
goatandsheep what browser are you in?

**Comment by goatandsheep** [comment]
Chrome

![code](https://i.imgur.com/Jd2noF6.png)

**Comment by valzav** [comment]
I see, you are talking about steem.io not steemit.com. 
I'm not sure steem.io needs to have those documents. Maybe just remove the links?

**Comment by goatandsheep** [comment]
@valzav true, my mistake. That would work for the steem.io error, but would not fix the terms of service / User agreement link missing from the sidebar.

**Comment by goatandsheep** [comment]
I looked at the page a bit more: since there is no scroll on the sidebar, the Terms of Service option is not accessible.

**Comment by goatandsheep** [comment]
Put this in the scss: 
`overflow-y: scroll;`

**Comment by valzav** [comment]
@goatandsheep thanks, will do

**Comment by roadscape** [comment]
Fixing the broken links in steem.io repo.
