### ISSUE TITLE
Raw html does not embed videos correctly

### ISSUE THREAD

**Issue by juanfranblanco** [steemit/steemit.com#25]
When writing a post with the newest html editor, the content was auto converted to raw html. Whilts this is not a major issue, Youtube embedded videos are not parsed correctly in raw html, they are just ignored.

The workaround is to convert everything back to markdown ;)

**Comment by jcalfee** [comment]
Markdown is the default now.  Videos will not work in the Rich Text editor for the moment.  However, the editor is going to be changed out entirely with a different library in the future.  It will have image and video support and be well tested .. I'm going to close for now..  Thank you..
