### ISSUE TITLE
Wallet page should indicate in-progress conversions

### ISSUE THREAD

**Issue by iamsmooth** [steemit/steemit.com#260]
Showing at least the total amount of SBD conversions in progress (if not the entire list detail), and adding it to total estimated value, would address the current issue where in-progress conversions appear to simply disappear from the balance and then suddenly reappear when the conversion is complete. This is confusing and has caused some concern by users.

**Comment by roadscape** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wallet balance needs to reflect conversions in progress and open orders #260, #51](https://trello.com/c/21P3w0dU/111-wallet-balance-needs-to-reflect-conversions-in-progress-and-open-orders-260-51)
