### ISSUE TITLE
Highlight posts which receive 100% SP

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#261]
Distinguish posts which are powering up their entire reward.

Either through a badge/icon, background color, etc

**Comment by roadscape** [comment]
May need to use a different icon..

After title

![image](https://cloud.githubusercontent.com/assets/5168676/18886969/361a7602-84c0-11e6-89ae-a9b689ab38c8.png)

Before title

![image](https://cloud.githubusercontent.com/assets/5168676/18886997/54bebfdc-84c0-11e6-9799-552ee5b89b4d.png)

**Comment by aaroncox** [comment]
I'm a fan of it being before, because it will cause them to line up vertically.

**Comment by cassiopaia** [comment]
will work in this next days!

**Comment by NateBrune** [comment]
Good idea @roadscape

**Comment by hazinstore** [comment]
I agree that this is an excellent idea!

**Comment by liondani** [comment]
Something like this for example ...

![100percent_power](https://cloud.githubusercontent.com/assets/6908400/18945112/9e5815cc-8631-11e6-8871-c23ea4c8614d.png)

**Comment by merej99** [comment]
I love the idea of a badge next to 100%SP posts.
@liondani - your example is great!  It's subtle but it still stands out.

**Comment by mcifani** [comment]
It certainly will give incentive and most likely see a surge in 100% SP posts -- will stand out and entice a click

**Comment by roadscape** [comment]
Going live today
