### ISSUE TITLE
Decline payout reward option

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#262]
Certain posts (e.g. platform announcements) do not need to collect a payout.

We should have an optional checkbox when creating a post to "decline rewards". It would set the `max_accepted_payout` to 0.000 SBD.

Posts which are not receiving a payout still collect rshares and get ranked on the trending page.

**Comment by randomSteemit** [comment]
Another alternative to this would be something like, If you decline payment it could go into a temporary account for the day and then at the end of the day it would be split between all active users for the day. This would give incentive to be active every day.

**Comment by faddat** [comment]
@randomSteemit I think this would need to be worked out on both the back end and the front end, but I think it's got merit.  DAU matters overall as a metric, and besides, upvoting is our content filtering system-- if activity stops, the site breaks.  

I like this concept.

**Comment by randomSteemit** [comment]
@faddat of course, and very true that activity is one of the most important metrics. The best way to keep that metric up is to give the users something to keep them coming back every day. The content on steem is good, the interest on SP and SBD is great, why not throw in another incentive to remain active everyday and give people the chance to "Give Back" to the community by spreading their wealth amongst the active ones trying to grow the platform.

**Comment by faddat** [comment]
Alright people, I think that Steemit, Inc. and the steem community deserve a pat on the back for being the spark for such discussions.  I just had one of those moments of clarity where I... "wait this is like inverse Facebook!  It's a social network that intentionally enriches and empowers its users!" 

Totally OT.  Felt it was worthy of mention anyway.

**Comment by theoreticalbts** [comment]
I think [this post](https://steemit.com/spam/@test-safari/m8vdx-test) is not right.  `max_accepted_payouts` is not a field in `comment_operation`, rather it is in a separate `comment_options_operation` in the tx.

**Comment by roadscape** [comment]
@theoreticalbts It does need more testing, but it appears to be reflected as expected:
![image](https://cloud.githubusercontent.com/assets/5168676/18885899/9ef95aa8-84bb-11e6-9c27-8799995095a6.png)
https://steemd.com/spam/@test-safari/m8vdx-test

**Comment by roadscape** [comment]
I have confirmed it's using `comment_options_operation` to set this value

**Comment by theoreticalbts** [comment]
Why doesn't it show up in the block?

I do `get_block 5341475` and see:

    {
      "ref_block_num": 33041,
      "ref_block_prefix": 1379079997,
      "expiration": "2016-09-27T17:34:21",
      "operations": [[
          "comment",{
            "parent_author": "",
            "parent_permlink": "spam",
            "author": "test-safari",
            "permlink": "m8vdx-test",
            "title": "Test",
            "body": "This is a test of the decline payout option. This post should receive no rewards, regardless of the votes it receives.",
            "json_metadata": "{\"tags\":[\"spam\",\"test\"]}"
          }
        ]
      ],
      "extensions": [],
      "signatures": [
        "1f47e5b4a49a1d2b23353e55daac91fbd09e12f378f4c328bd2e08305e7ce00bd7353d670ef3a350bb80ae57c0b123e8120b22e626f2b468b2ea0f468ec2b4bbb7"
      ]
    }

**Comment by roadscape** [comment]
What I didn't expect to see was that `total_pending_payout_value` is not 0. It's useful information but the fact that it's showing makes me wonder if it's a bug, or possibly lowering pending post payouts.

You may have been looking at one of the edits, here is the original tx in block 5341416:
https://steemd.com/tx/3f6f8904aeaf38ca1674c09f516dc80c8e14daa1

**Comment by Gutalean** [comment]
What about payout of such a post go to account @null?
