### ISSUE TITLE
Wallet Page Estimated Value is incorrect

### ISSUE THREAD

**Issue by wmbutler** [steemit/steemit.com#27]
Discussion here:

https://steemit.com/steem/@taoteh1221/wallet-page-estimated-dollar-value-is-36-64-higher-than-bittrex-trade-value-atm

**Comment by taoteh1221** [comment]
Looks like a Steemit.com bug, NOT a network bug. The network seems to be calculating the median dollar value just fine, Steemit on the other hand is waaay off.

**Comment by jcalfee** [comment]
I found the reason .. The price per steem is hard-coded!  I'll replace it with the price feed...

**Comment by jcalfee** [comment]
fyi, some notes, this might come in handy...
```
Steem = account.balance
"9452.333 STEEM"

Steem_Power = info.total_vesting_fund_steem * (account.vesting_shares / info.total_vesting_shares);
2859.4046022886205 = 78407993.384 * (15636871.956265 / 428780086564.8627)


.35
Estimated_Value = (Steem_Power + Steem) * price_per_steem
```

**Comment by jcalfee** [comment]
The API changed and the code had a hard-coded value.  It is fixed to pickup the price_feed in the new location, if it ever breaks again `$NaN` will be displayed for the Estimated Value (instead of an incorrect value).

**Comment by taoteh1221** [comment]
Cool. :+1:
