### ISSUE TITLE
Additional iframe source whitelisting

### ISSUE THREAD

**Issue by hizzvizz** [steemit/steemit.com#271]
Here is the code I was trying to embed.

'<iframe width="625" height="652" frameborder="0" allowfullscreen allowtransparency src="//www.shapeways.com/fragments/product?spin=XJQQ7CRGP"></iframe>'

Here is what the steemit post preview showed me.

http://i.imgur.com/uM5Gv9v.png

**Comment by hizzvizz** [comment]
<iframe width="625" height="652" frameborder="0" allowfullscreen allowtransparency src="//www.shapeways.com/fragments/product?spin=XJQQ7CRGP"></iframe>

**Comment by hizzvizz** [comment]
"<iframe width="625" height="652" frameborder="0" allowfullscreen allowtransparency src="//www.shapeways.com/fragments/product?spin=XJQQ7CRGP"></iframe>"

**Comment by hizzvizz** [comment]
iframe width="625" height="652" frameborder="0" allowfullscreen allowtransparency src="//www.shapeways.com/fragments/product?spin=XJQQ7CRGP"></iframe

**Comment by novium** [comment]
Allowing iframes is potentially a huge security risk. Basically that's allowing another website to serve content on yours, and you have no way of knowing that it's clean.

You can read more on [StackOverflow](http://stackoverflow.com/questions/7289139/why-are-iframes-considered-dangerous-and-a-security-risk)

**Comment by roadscape** [comment]
Related requests:

#208

> I tried adding an iframe embed from flat.io and I got an unsupported message. It would be nice to see support for flat.io embeds.

> `<iframe src="https://flat.io/score/57c84c518be7d0122effdf95-giant-steps-redux?embed" height="400" width="100%" frameBorder="0" style="border-radius:10px;box-shadow:0px 4px 8px 0px rgba(0,0,0,0.16);"></iframe>`

> [unsupported message](http://i.imgur.com/hHnbCHW.png)

#196 

> I am writing a post that references code I've written in processing. I wanted to embed a syntax highlighted code snipped in steemit, but it says the iframe code isn't supported.

> http://i.imgur.com/E4NIxsi.png (message shown in post preview)

> Here's the embed code I am trying to use.

> `<iframe src="//pastebin.com/embed_iframe/BnRQgJtu" style="border:none;width:100%"></iframe>`

**Comment by pfunks** [comment]
I'd like to throw a request in for bandcamp iframes as well. Soundcloud is already whitelisted. Here's an example: 

`<iframe style="border: 0; width: 100%; height: 42px;" src="http://bandcamp.com/EmbeddedPlayer/album=4058595266/size=small/bgcol=ffffff/linkcol=0687f5/track=3956790839/transparent=true/" seamless><a href="http://strangerelations.bandcamp.com/album/going-out">Going Out by Strange Relations</a></iframe>`

**Comment by valzav** [comment]
I think we would be able to allow more iframe embeds later when we get the wallet to another domain, probably in a couple of months.

**Comment by tzarebczan** [comment]
@valzav has there been any progress on whitelisting other sites for iframes on steemit? We'd really love to be able to embed spee.ch URLs: 

```<iframe src="https://spee.ch/video-embed/@JordanBPeterson:c/responsibility-conscience-and-meaning" allowfullscreen="true" style="border:0"></iframe>```
