### ISSUE TITLE
SEO tweaks

### ISSUE THREAD

**Issue by valzav** [steemit/steemit.com#275]

**Comment by roadscape** [comment]
- [ ] add missing hatom's author, entry-title, updated fields
- [ ] add missing hentry's author and updated fields
- [ ] add "by [author]" at the end of meta description tag

**Comment by roadscape** [comment]
https://moz.com/learn/seo/hreflang-tag:
> The hreflang attribute adds a signal to search engines that a user querying in language "x" will want this result instead of a page with similar content in language "y".

Not sure if this is relevant
