### ISSUE TITLE
Vote Slider not working in IE

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#279]
A user commented to me today that the vote slider was not working for them in IE. They said they have to switch to Chrome whenever they want to vote. Is this a known issue? Can it be reproduced?

[Edit] I asked for more details, and this was provided:
IE 11.0.9600.18449
Windows 7 Home Premium
The upvote slider pops up but disappears as soon as I click on it and does not register the upvote.

**Comment by roadscape** [comment]
Was able to reproduce this, looking into it.

**Comment by roadscape** [comment]
The fix is live!
