### ISSUE TITLE
Viewing a post changes the filtered category

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#280]
If I go to the main "trending" tab, I see all of the trending posts. If I click on one of the posts, it now sets the category I am viewing to whatever the main category of the post was. When I click back on the "trending" page, it only shows posts that are in the category of that post. 

To me this seems like a glitch. Just because I clicked on an article to read it, does not mean that I now only want to filter for posts in this category.

**Comment by mcifani** [comment]
Agree on this edge case - will look into updating behavior for this flow.

**Comment by roadscape** [comment]
This may be resolved by #282

**Comment by mcifani** [comment]
Yep it does. Closing this ticket.
