### ISSUE TITLE
Feed does not load

### ISSUE THREAD

**Issue by physicsdude** [steemit/steemit.com#284]
Today I noticed that my feed and follow links won't load. 
This happens when I view https://steemit.com/@nonlinearone
I am able to view other people's feeds, e.g. https://steemit.com/@fyrstikken and https://steemit.com/@jpiper20

Two other people, https://steemit.com/@klye and https://steemit.com/@claudiop63 have independently confirmed that they can't load my feed.

I know you guys are busy today so am not expecting a quick fix, just wanted to get this report posted.

Thanks for all you do.

https://steemit.com/@nonlinearone

**Comment by physicsdude** [comment]
![4nonlinearone_ _steemit](https://cloud.githubusercontent.com/assets/798806/18647532/49bfb498-7e6b-11e6-829f-3d5915a0a3a6.jpg)

This screenshot was taken after the page had taken minutes to load. I started the 'recording' after it was already 'stuck'.

**Comment by klye** [comment]
I believe you've tagged the wrong person - I am unaffiliated with this
project. Good luck with your bug, though...

**Comment by physicsdude** [comment]
My bad @klye - I meant to reference the @klye on SteemIt - didn't realize it would alert @klye on github. Thanks for the well wishes :)

**Comment by physicsdude** [comment]
![5](https://cloud.githubusercontent.com/assets/798806/18647748/5b399698-7e6c-11e6-8971-9af5778fb0c4.jpg)

The console shows several get_following commands, after that get_dynamic_global_properties commands are repeated ad-infinitium.

**Comment by roadscape** [comment]
Thanks for the report, it appears to be a backend issue and we are taking a look: https://github.com/steemit/steem/issues/440

**Comment by physicsdude** [comment]
Thanks!

**Comment by roadscape** [comment]
This issue has been resolved!

**Comment by physicsdude** [comment]
Thanks @roadscape - that was fast 👍

**Comment by physicsdude** [comment]
Thanks again! https://steemit.com/development/@nonlinearone/thank-you-steemit-and-steem-devs-for-fixing-a-tricky-bug-quickly-how-to-report-a-bug
