### ISSUE TITLE
Post Title Preview Encoding: quotes, apostrophes and other characters

### ISSUE THREAD

**Issue by KrNel** [steemit/steemit.com#285]
Hello,

When posting quotes ", or apostrophes ', and maybe other characters like question mark ? and exclamation ! (untested), the title when sharing the links in the RocketChat does not show up as the encoding of normal text, but with hex unicode I think it's called:

' = &#x27;

Also, maybe I need to open a new ticket for it, but when edits are made to the Title, first sentence, or Primary image in the post, the new posts of the link as the preview info in RocketChat does not update and stays as the original Title, first sentence, or first image originally posted. Can this be corrected to reflect the updated changes when we post the link anew after corrections are made to the post?

Thank you. Peace.

**Comment by roadscape** [comment]
Please contact the steemit.chat admin (riverhead), this GitHub repo is only for steemit.com issues.
