### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mostar** [steemit/steemit.com#29]
Steemit.com is lucking RTL support. RTL languages are: Hebrew, Arabic, Persian and more and it represents tens of millions of internet users.

**Comment by jcalfee** [comment]
Perhaps cssjanus can do this: https://discuss.reactjs.org/t/right-to-left-rtl-support-in-react/2978
@valzav what do you think?

**Comment by jcalfee** [comment]
test link: https://steemit.com/test/@john-kimmel/ipfs-image-link-test

**Comment by roadscape** [comment]
With that last commit you will now be able to use the following syntax for RTL:

    <div class="text-rtl">
    
        (your post, table, etc)
    
    </div>

Just wrap your post (or whichever parts you want to be rtl) with the syntax above. A blank line before and after each <div> tag is recommended.

**Comment by mostar** [comment]
Hi,

It alien to the left but also display the tags and make all steemit RTL, it RTL post is in a page.
For example:
https://steemit.com/hebrew/@noaommerrr/5pa1cm

**Comment by roadscape** [comment]
Please note this feature is not live yet! I can test it locally and post a screenshot though.

One issue I see is that you are using the HTML (RichText) editor.

You may have better results in Markdown mode.
