### ISSUE TITLE
Bug about 'Reply' link

### ISSUE THREAD

**Issue by abitmore** [steemit/steemit.com#298]
This post https://steemit.com/steem/@piedpiper/thinking-bigger-why-the-low-price-of-steem-is-a-good-thing#@sigmajin/re-sigmajin-re-piedpiper-re-snowflake-re-piedpiper-re-snowflake-re-piedpiper-thinking-bigger-why-the-low-price-of-steem-is-a-good-thing-20160921t045916529z has a "reply" link but I can't reply, on the contrast its parent has no reply link.

**Comment by roadscape** [comment]
Thanks for the report, fix will be deployed shortly.
