### ISSUE TITLE
Feature Request: Clicking on the time of comment should give context-surrounded permalink to comment and other link sharing options

### ISSUE THREAD

**Issue by arhag** [steemit/steemit.com#3]
I would like to see the time of comments be a link just like root posts that provides a link to the comment in the context of the discussion tree. This would be the same link you get when you click to see the comment from the "Posts" or "Replies" tab of your account page.

I also think there should be an alternative way to get such a link. The share dropdown should provide a "Link" option. The share dropdown would be available to comments as well as root posts. For root posts, it would provide the same link as that of clicking the time of the root post. For comments, the "Link" share option would instead provide a directly link to the comment (not context-surrounded). 

In this case, comment's viewed directly (as if they were roots of the discussion) should be rendered differently to indicate they are not the actual root post and to provide links to allow them to navigate to the greater discussion tree not shown. At a minimum this means a direct link to the parent of the comment. But it would ideally also have a link to show the comment in the context of the whole discussion tree that it exists within, not just the subtree currently shown. However, clicking on the time of a comment within the displayed subtree would link to that comment in the context of that subtree, not of all the whole discussion tree it actually exists within.

**Comment by arhag** [comment]
Thanks for making the time on comments be (context-surrounded) permalinks. One very slight annoyance I notice is that clicking on the time link doesn't automatically center the page around the comment as it would if you were to load URL in the browser directly and press enter.

I'm still going to leave this issue open because I am still hoping for an alternative way to get similar permalinks (using the Share dropdown) as described in the OP.

**Comment by roadscape** [comment]
These points have been addressed:

 - time of comment is a link to the comment
 - comments viewed directly have links to (a) parent content, and (b) root context  
    (although iirc nowhere in the interface do we link to comments outside of the root context)

Not addressed:

 - clicking time of comment to center the page around the comment
 - share dropdown on every comment w/ Link option

Imo, centering the page is minor, and a share dropdown on every comment is a bit much, so I'm closing this ticket. Please open a new issue if you'd like to explore either of them in more detail.
