### ISSUE TITLE
html align right not work

### ISSUE THREAD

**Issue by mostar** [steemit/steemit.com#30]
HTML align right stop not work in steemit.com
It use to work two mouth a go, for example this post:
https://steemit.com/hebrew/@noaommerrr/4pddrp--
Was display align right and now without and change in the post content it align left.
The alignment in this post was done using markdown table align tag

**Comment by jcalfee** [comment]
Are you trying to use a 2nd cell of a table to move it to the right?  I see only row after row with only 1 cell in it.  
<table>
<thead>
<tr><th>עימוד לימין</th></tr>
</thead>
<tbody>
<tr><td>אחרות RTL בשלב זה יש בעיה בפורומים בעניין עימוד לעברית ושפות</td></tr>
<tr><td>בשרשור קישור לגליון עזר של גוגל</td></tr>
<tr><td>יש לעקוב אחרי ההוראות בגליון</td></tr>
</tbody>
</table>

Are you trying to use this technique? 
http://stackoverflow.com/a/14508301/766233

**Comment by mostar** [comment]
> Are you trying to use a 2nd cell of a table to move it to the right?

Yes. but it not working any more.

https://steemit.com/hebrew/@noaommerrr/4pddrp--

> Are you trying to use this technique?
> http://stackoverflow.com/a/14508301/766233

Its not work neither, you can see my last reply in 
https://steemit.com/hebrew/@noaommerrr/4pddrp--

**Comment by jcalfee** [comment]
I see the issue.  We can whitelist `style="text-align..."` in `<td style="text-align:right">` ..

The style tag can be used in XSS attacks so are removing it, however, I think we are safe with this text-align tag.  So, we need a new feature in one of our libraries to do this and perhaps a work-around in the meantime.

**Comment by mostar** [comment]
Using the style="text-align:right" in td (table) was work around the align issue.  Beter sulotion will be to allow:
`<p dir="rtl">this test is right align</p> `
or
`<span dir="rtl">this test is right align</span>`
or
`<style type="text/css">  .rtl {    direction: rtl;  }</style>`
etc

**Comment by jcalfee** [comment]
related: https://github.com/steemit/steemit.com/issues/29

**Comment by jcalfee** [comment]
fixed
