### ISSUE TITLE
Support TeleSign as identity provider

### ISSUE THREAD

**Issue by valzav** [steemit/steemit.com#304]
see for api details https://developer.telesign.com/docs

**Comment by sneak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Telesign Integration for Signups](https://trello.com/c/Ga6Bxsux/11-telesign-integration-for-signups)

**Comment by TimCliff** [comment]
Again, sorry for the 'stupid question' but can someone please explain what this feature will add? Is it going to be a new form of signup (in addition to Facebook + Reddit), or is it something different? How will users be able to use it once it is added?

**Comment by sneak** [comment]
Please don't ask these sorts of questions here, this isn't the appropriate forum for explaining features. This repo is for use by developers, it is not for discussion of product roadmap or support.

**Comment by TimCliff** [comment]
K, sorry. I didn't know. Won't happen again :)
