### ISSUE TITLE
No business development contact info

### ISSUE THREAD

**Issue by hazinstore** [steemit/steemit.com#308]
We have a project that will be using steem & steemit, and would like to keep you in the loop.  
Opening an issue doesn't seem like the right way of getting in touch, but there doesn't appear to be any way to contact steemit for business development purposes.
Can you at least add a "contact us" form or something like it, to the site, so that in the future, investors and business people can find some way to reach out to you?

This is @willbanks but I'm operating in my official capacity with the hazin roject.
You can verify this contact here.
https://steemit.com/verifiedcontact/@williambanks/verification-post-do-not-upvote-do-not-resteem
Thanks!

**Comment by jcalfee** [comment]
We should probably have a mail to link in the side bar and list this email.

Feel free to email us at:  `Contact Steemit <contact@steemit.com>`

**Comment by willbanks** [comment]
Thank you, sending the email now!

**Comment by hazinstore** [comment]
Sent!
