### ISSUE TITLE
Frozen Discussions Shouldn't show an input box

### ISSUE THREAD

**Issue by faddat** [steemit/steemit.com#311]
Current user workflow is like this:

Reads article, 
scrolls down and sees:
![image](https://cloud.githubusercontent.com/assets/7142025/18728500/92f37ab0-8077-11e6-988c-e392558bec81.png)

Types comment:

![image](https://cloud.githubusercontent.com/assets/7142025/18728560/df117bea-8077-11e6-97cb-4170e19a3ed1.png)

Clicks "post":

![image](https://cloud.githubusercontent.com/assets/7142025/18728583/f9fbd0a4-8077-11e6-92a7-89e44f4c1ca0.png)

Oh, noes!  It is frozen!  

Better workflow:

![image](https://cloud.githubusercontent.com/assets/7142025/18728640/5941233e-8078-11e6-9f30-e0994ce223c7.png)

**Comment by roadscape** [comment]
Thanks, fixed in https://github.com/steemit/steemit.com/pull/321
