### ISSUE TITLE
Won't Load All Posts

### ISSUE THREAD

**Issue by matthewniemerg** [steemit/steemit.com#313]
On both Firefox and Chrome on my Mac, I can not go to an author's page and load all of their posts anymore.

It stalls around 22 posts.

One solution, instead of continuous scrolling, is a fixed number of posts per page -- like 20.

**Comment by mcifani** [comment]
What version of FF/Chrome are you using?  Seems fine tested here.

**Comment by matthewniemerg** [comment]
Chrome : Version 53.0.2785.116 (64-bit)


Firefox : 48.0.1

But FF is updating.

I had a different user tell me they experienced the same thing.

**Comment by thecryptodrive** [comment]
Can't scroll down on blog to see older posts, using Chrome Version 53.0.2785.116 m (64-bit) and Microsoft Edge 38.14393.0.0 and IE 11.187.14393.0

**Comment by matthewniemerg** [comment]
This is on my homepage (www.steemit.com/@complexring) where the scrolling is failing.  Main page works fine.

Updated FF to 49.0.

Same issues.

**Comment by mcifani** [comment]
Looks also potentially isolated to certain users, not all users are failing.

**Comment by physicsdude** [comment]
Seems similar to this https://github.com/steemit/steemit.com/issues/284

**Comment by thecryptodrive** [comment]
@complexring has same issue as me

**Comment by roadscape** [comment]
I found the cause of the problem, it will affect any user's blog where the last item on the page is a reblog.. fix incoming

**Comment by thecryptodrive** [comment]
Nice, well done!

**Comment by matthewniemerg** [comment]
Was this pushed?  I am still seeing it on my end.

**Comment by matthewniemerg** [comment]
Oh nevermind.  Hopefully they'll update the site soon on this.
