### ISSUE TITLE
Cursor cannot be moved in write comment/article window on IPad/IPhone

### ISSUE THREAD

**Issue by riensen** [steemit/steemit.com#32]
Dear steemit maintainers,

When using an IPad or IPhone to edit or write a text in a multi-line text field on steemit.com, then moving the cursor is not possible. Instead of the cursor being moved, the text box scrolls and the cursor will stay at its current position. 

Used Browsers: 51.0.2704.104
OS: IOS 9.3.2

Regards,
riensen

**Comment by roadscape** [comment]
Is this still an issue?

**Comment by mcifani** [comment]
@roadscape Can't seem to replicate. Tested on BrowserStack with OS version indicated and FF. Closing out.
