### ISSUE TITLE
Migrate problem

### ISSUE THREAD

**Issue by alexant123** [steemit/steemit.com#320]
I trying to get front develop passing the instruction, but when i command:
`Run sequelize db:migrate in db/ directory`

I have answer: 
`Loaded configuration file "config/config.json".
{ SequelizeDatabaseError: ER_NO_DB_ERROR: No database selected
    at Query.formatError (/Users/anmuravjev/.nvm/versions/node/v6.6.0/lib/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/Users/anmuravjev/.nvm/versions/node/v6.6.0/lib/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/Users/anmuravjev/.nvm/versions/node/v6.6.0/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Query.ErrorPacket (/Users/anmuravjev/.nvm/versions/node/v6.6.0/lib/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/Users/anmuravjev/.nvm/versions/node/v6.6.0/lib/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/anmuravjev/.nvm/versions/node/v6.6.0/lib/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/Users/anmuravjev/.nvm/versions/node/v6.6.0/lib/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/anmuravjev/.nvm/versions/node/v6.6.0/lib/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
  name: 'SequelizeDatabaseError',
  message: 'ER_NO_DB_ERROR: No database selected',`

Database steemit_dev has been created successful before, without any errors. 

My config.json seems like that: 
{
  "db": {
    "username": "root",
    "password": null,
    "database": "steemit_dev",
    "host": "127.0.0.1",
    "dialect": "mysql"
  },
  "session_key": "steemses",
  "grant": {
    "server": {
      "protocol": "http",
      "host": "localhost:3002"
    },
    "facebook": {
      "key": "",
      "secret": "",
      "callback": "/handle_facebook_callback",
      "scope": [
        "email",
        "user_location"
      ]
    },
    "reddit": {
      "key": "",
      "secret": "",
      "callback": "/handle_reddit_callback",
      "custom_params": {"state": "void", "duration": "temporary"},
      "scope": [
        "identity"
      ]
    }
  },
  "helmet": {},
  "registrar": {
    "account": "-",
    "signing_key": "-",
    "fee": "5.000 STEEM"
  },
  "requestAccountRecovery": {
    "signing_key": "5J.....",
    "recovery_account": "steem"
  },
  "ws_connection_client": "wss://node.steem.ws",
  "ws_connection_server": [
    "wss://node.steem.ws"
  ],
  "sendgrid": {
    "key": "SG.xxx_yyyy",
    "from": "noreply@example.com",
    "templates": {
      "confirm_email": "some_template_id"
    }
  },
  "recaptcha": {
    "site_key": "",
    "secret_key": ""
  },
  "img_proxy_prefix": "",
  "ipfs_prefix": "",
  "google_analytics_id": "",
  "disable_signups": false,
  "read_only_mode": false,
  "uploadImage": "https://..."
}

........

I wrote my current login and password here too, but nothing not changed. Please, help me fix it.

**Comment by valzav** [comment]
Please note that config.json in db/config has the following format:
{
  "development": {
    "username": "root",
    "password": null,
    "database": "steemit_dev",
    "host": "127.0.0.1",
    "dialect": "mysql"
  }
}

**Comment by alexant123** [comment]
Yes, it step forward, but.. 

`Loaded configuration file "config/config.json".
Using environment "development".
Unable to connect to database: SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)`

Should i use password from my account here? I try, but got same answer with it.

**Comment by jcalfee** [comment]
Having the same issue on Ubuntu 16.04.. This is probably because `mysql -u root` can't login under your version of mysql.  `sudo mysql -u root` will probably work.

Be careful though, I messed up my database trying to fix it then messed up my install trying to reset the database.  I can't even run mysql now.

**Comment by alexant123** [comment]
I connect to mysql, can create database, edit it.
But `sequelize db:migrate` can't, access denied...

**Comment by jcalfee** [comment]
What about nodejs (`npm start`), does it have this database connection error in it?

**Comment by mcifani** [comment]
@alexant123 To confirm, if you try in your console ```mysql -u root``` are you able to see the mysql prompt without entering a password?

**Comment by jcalfee** [comment]
A work-around for me was to add `--skip-grant-tables` after the mysqld command in `/lib/systemd/system/mysql.service`.  This is only for development where absolutely no security is required so this is a very bad work-around.  It looks mysql (5.7 maybe before) locked something down breaking the usual login.

**Comment by alexant123** [comment]
`mysql -u root` - opened without any password. I have mysql prompt and able to do any command. 
`mysql> `


`npm start ` - start without mysql error, but localhost:3002 is not available for now. 

>Steemit.com@1.0.0 start /Users/anmuravjev/steemit.com 
>babel-node ./webpack/dev-server.js

>webpack-dev-server listening on port 3001
>Error: ENOENT: no such file or directory, open '/Users/anmuravjev/steemit.com/tmp/webpack-stats-dev.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Compiler.exports.default (/Users/anmuravjev/steemit.com/webpack/utils/write-stats.js:44:8)
    at Compiler.applyPlugins (/Users/anmuravjev/steemit.com/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/anmuravjev/steemit.com/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/anmuravjev/steemit.com/node_modules/webpack/lib/Compiler.js:51:17)
    at /Users/anmuravjev/steemit.com/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/anmuravjev/steemit.com/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/anmuravjev/steemit.com/node_modules/webpack/lib/CachePlugin.js:40:4)
`

**Comment by jcalfee** [comment]
How did you resolve `ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)` ?

My tmp/webpack-stats-dev.json file was re-created when I ran `npm start`.  @valzav please have a look above...  A possible work-around is to run `npm run build` which should create your webpack-stats-dev.json file..

**Comment by valzav** [comment]
tmp/webpack-stats-dev.json is being created by `npm start`, if it doesn't create it then there is some other issue

**Comment by alexant123** [comment]
Problem resolved by changes in config.json: 

>"username": "root",
"password": null,


to
>"username": "root",
"password": "",
`

**Comment by alexant123** [comment]
But still have a problem after 
`npm start`

Steemit.com@1.0.0 start /Users/anmuravjev/steemit.com
babel-node ./webpack/dev-server.js

webpack-dev-server listening on port 3001
Error: ENOENT: no such file or directory, open '/Users/anmuravjev/steemit.com/tmp/webpack-stats-dev.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Compiler.exports.default (write-stats.js:44:8)
    at Compiler.applyPlugins (/Users/anmuravjev/steemit.com/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/anmuravjev/steemit.com/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/anmuravjev/steemit.com/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/Users/anmuravjev/steemit.com/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/Users/anmuravjev/steemit.com/node_modules/webpack/lib/Compiler.js:58:19)
    at /Users/anmuravjev/steemit.com/node_modules/webpack/lib/Compiler.js:275:11

**Comment by alexant123** [comment]
I have 3 same troubles in 3 different machines (mac ox + Ubuntu 16 (cloud, vps))
When i `npm start` i have answer as above. 
Directory /tmp in project folder does not created. Same with npm-debug.log - cannot be founded. Any suggestions, how solve it?

**Comment by alexant123** [comment]
Command `npm run build` answer as below:
0 info it worked if it ends with ok
1 verbose cli [ '/Users/anmuravjev/.nvm/versions/node/v6.6.0/bin/node',
1 verbose cli   '/Users/anmuravjev/.nvm/versions/node/v6.6.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.8
3 info using node@v6.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Steemit.com@1.0.0~prebuild: Steemit.com@1.0.0
6 silly lifecycle Steemit.com@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle Steemit.com@1.0.0~build: Steemit.com@1.0.0
8 verbose lifecycle Steemit.com@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle Steemit.com@1.0.0~build: PATH: /Users/anmuravjev/.nvm/versions/node/v6.6.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/anmuravjev/steemit.com/node_modules/.bin:/Users/anmuravjev/.nvm/versions/node/v6.6.0/bin:/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin
10 verbose lifecycle Steemit.com@1.0.0~build: CWD: /Users/anmuravjev/steemit.com
11 silly lifecycle Steemit.com@1.0.0~build: Args: [ '-c',
11 silly lifecycle   'NODE_ENV=production babel-node ./node_modules/.bin/webpack --stats --config ./webpack/prod.config.js' ]
12 silly lifecycle Steemit.com@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle Steemit.com@1.0.0~build: Failed to exec build script
14 verbose stack Error: Steemit.com@1.0.0 build: `NODE_ENV=production babel-node ./node_modules/.bin/webpack --stats --config ./webpack/prod.config.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/anmuravjev/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/anmuravjev/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Steemit.com@1.0.0
16 verbose cwd /Users/anmuravjev/steemit.com
17 error Darwin 15.6.0
18 error argv "/Users/anmuravjev/.nvm/versions/node/v6.6.0/bin/node" "/Users/anmuravjev/.nvm/versions/node/v6.6.0/bin/npm" "run" "build"
19 error node v6.6.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error Steemit.com@1.0.0 build: `NODE_ENV=production babel-node ./node_modules/.bin/webpack --stats --config ./webpack/prod.config.js`
22 error Exit status 1
23 error Failed at the Steemit.com@1.0.0 build script 'NODE_ENV=production babel-node ./node_modules/.bin/webpack --stats --config ./webpack/prod.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Steemit.com package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=production babel-node ./node_modules/.bin/webpack --stats --config ./webpack/prod.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Steemit.com
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Steemit.com
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by valzav** [comment]
Maybe you just need to create ./tmp directory manually before you run `npm start`?

**Comment by alexant123** [comment]
Right!
I create directory tmp and with empty file inside webpack-stats-dev.json
And all done. Thanks for contribute!

**Comment by valzav** [comment]
There was no need to add empty webpack-stats-dev.json.
Could somebody mention creation tmp dir in README?
