### ISSUE TITLE
Quick and easy way to add avatars

### ISSUE THREAD

**Issue by hazinstore** [steemit/steemit.com#322]
Hey I found a quick and easy way to add avatars.  I looks like a lot of people are interested in this and the method works remarkably well.  Should only be a single dependency to add.
https://steemit.com/steemit/@williambanks/8bit-avatar-this-is-fun-and-brilliant

Hope it's helpful!

**Comment by randomSteemit** [comment]
This should be easy and this is awesome! Just need to import the "username"and gender into steemit.com/app/components/elements/Userpic.jsx I guess and change the 
```export default () => <div className="Userpic"><img src={require('app/assets/images/user.png')} width="48px" height="48px" /></div>;```
to something like 
```export default () => <div className="Userpic"><img src={http://eightbitavatar.herokuapp.com/?id=username&s=gender&size=200} width="48px" height="48px" /></div>;```

Unfortunately I have no experience with react or I would do it right now. Maybe i will give it a shot though unless someone else can do it quickly?

**Comment by hazinstore** [comment]
Might want to make that a bit more user selectable, such as changing case. 
Some of these are umm really wierd. :)  But I agree, this is totally cool!

**Comment by randomSteemit** [comment]
Weird: Yes. 
haha Im guessing we would need permission from the owner of the api though?

**Comment by hazinstore** [comment]
We could just require it and use it clientside, instead of calling out server side...
https://www.npmjs.com/package/avatar-generator

Pretty sure the build process is already calling browserify and it should be a trivial import.

**Comment by randomSteemit** [comment]
actually its using webpack, but whatevs ;) I'm attempting to get a dev branch set up now.

**Comment by roadscape** [comment]
Thanks @hazinstore, we've gone with URL-based avatars for now.
