### ISSUE TITLE
Report on liquid STEEM post rewards

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#326]
Recently, steemd reached a threshold where posts started being rewarded with some portion of SD rewards being granted as liquid STEEM. The UI needs to show this information.

Requires backend API change.

**Comment by thecryptodrive** [comment]
Also I believe the Steem:SBD payout ratio varies according to market cap, I think the GUI wallet should show under the author rewards for that post what the split was in an easy percentage manner like 50% Steem Power 20% SBD 30% Steem for example in addition to the numerical values,

**Comment by roadscape** [comment]
From #329:

> ![image](https://cloud.githubusercontent.com/assets/22358264/18784045/c705dabe-818f-11e6-8a5f-0275ee84438d.png)

> Please note payout is now in SBD, Steem and SP after the recent fork, however the author rewards GUI on Steemit.com is showing only SBD and SP payout, difficult to audit if running competitions, business account etc.

> Steemd and steemdb may need to be updated as well.

**Comment by roadscape** [comment]
It appears required backend changes are complete: https://github.com/steemit/steem/commit/1927ce7bb43f57fab9502b4ce4d50b23fcd0604c

**Comment by roadscape** [comment]
> Also I believe the Steem:SBD payout ratio varies according to market cap, I think the GUI wallet should show under the author rewards for that post what the split was in an easy percentage manner like 50% Steem Power 20% SBD 30% Steem for example in addition to the numerical values,

> **So something like:**
> Author reward of 10 SD (25%), 10 STEEM (25%) and 20 STEEM POWER (50%)

It's a good idea but hard to do because the value of each one fluctuates. What's 50%-50% SD-SP one day may be 20%-80% the next.
