### ISSUE TITLE
Author Rewards Page only shows 2 of the 3 Tokens now given after payout

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#329]
![image](https://cloud.githubusercontent.com/assets/22358264/18784045/c705dabe-818f-11e6-8a5f-0275ee84438d.png)

Please note payout is now in SBD, Steem and SP after the recent fork, however the author rewards GUI on Steemit.com is showing only SBD and SP payout, difficult to audit if running competitions, business account etc.

Steemd and steemdb may need to be updated as well.

**Comment by thecryptodrive** [comment]
Seems roadscape reported this 14 hours ago, must I close this comment or leave it open?

**Comment by thecryptodrive** [comment]
Also I believe the Steem:SBD payout ratio varies according to market cap, I think the GUI wallet should show under the author rewards for that post what the split was in an easy percentage manner like 50% Steem Power 20% SBD 30% Steem for example in addition to the numerical values,

So something like:
Author reward of 10 SD (25%), 10 STEEM (25%) and 20 STEEM POWER (50%)

**Comment by roadscape** [comment]
Thank you, let's close this and keep the convo in #326
