### ISSUE TITLE
Not all image urls work

### ISSUE THREAD

**Issue by Beervangeer** [steemit/steemit.com#33]
Some image work when I add a image by url.
But a lot of image dont show up.

**Comment by jcalfee** [comment]
Images that look like images (end with png or jpeg for example) will show up.  But if you use the "Editor" be sure to use the image button to add your link.  This will cause it to show up even if it does not "look" like an image.  Always look for some confirmation that your image shows up.  If you don't see it when you hit post then don't expect to see it after you post..  Give it a try, let us know how it goes.

**Comment by jcalfee** [comment]
And if your using markdown you can always tell the site any link is an image `![](url)`.
