### ISSUE TITLE
LinkedIn Share is broken

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#340]
Hi Guys, the LinkedIn share is broken, tried on Chrome. See screenshot:

![image](https://cloud.githubusercontent.com/assets/22358264/18827949/c0333f72-83d5-11e6-99cf-d93b292f57fc.png)

**Comment by roadscape** [comment]
Could you try again? I cannot reproduce this issue.

**Comment by thecryptodrive** [comment]
it seems to work now, maybe LinkedIn was down at the time :)
