### ISSUE TITLE
Account Password

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steemit.com#343]
Hi,

I have an account (@cryptoctopus_ and I have no way to change my active keys. I am trying to setup something were I need to have different passwords for posting keys and active keys. 

How do I do this?

**Comment by roadscape** [comment]
Currently, accounts usually log in with their master password (it begins with `P5..`).

From this password, the posting, active, owner, and memo keys are derived.

The individual keys can be found on the 'Permissions' tab in your wallet. 
There you will be able to access the WIF keys for posting / active.

If you need to change all your keys, then reset your master password and all the individual keys will be updated.
