### ISSUE TITLE
FB Support - Facebook Signup Issues

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#344]
From Mr. Ben Bass Nazzi Owens on Facebook

> the sign up with facebook link on your website is currently broken. i would like to start creating content with your site, but cant sign up.

I've sent him the link to this ticket so that he can see the progress of this issue.

**Comment by roadscape** [comment]
Is it a different error than the one reported in #345?

**Comment by SteemitFbAdmin** [comment]
yes, most likely

**Comment by roadscape** [comment]
We will need more details -- either steps to reproduce, or an error message the user received.

**Comment by jcalfee** [comment]
Please reopen if you have more info...
