### ISSUE TITLE
Facebook Signup Issue #2

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#345]
Someone on Facebook sent me this message and I will be linking to this page for this person to follow up with the development on it:

> Hi, Today I convinced my girlfriend to sign up at steem, unfortunately it is not possible 😞 She always receives this message: "facebook: 2 error: Error: We are sorry, currently we unable to sign up new users from your domain zone due to spam and system abuse." Is there any solution ?Thx

**Comment by valzav** [comment]
We had to restrict valid email addresses, in particular all .ru emails are blocked due to a lot of bots registering using them.

**Comment by roadscape** [comment]
We are using mobile verifications now, this should not be an issue
