### ISSUE TITLE
System-Generated Password Issue for Sign Up - Facebook Customer Support 

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#347]
This lady is having issue with the system-generated password in order to sign up.

>I tried to sign-up; but, the system-generated password wouldn't accept itself when re-entered. Yes, I cut and pasted. Yes, I then tried manually re-entering it, carefully. Yes, I tried starting from scratch, and a second system-generated password. So what can be done?

I am giving her this link in order for her to follow up with the issue and hopefully solve it soon.

![image](https://cloud.githubusercontent.com/assets/5168676/18880028/820299b2-84a4-11e6-9ff8-64fe1f357af8.png)

**Comment by roadscape** [comment]
I'm guessing this was reported a week or two ago, the issue should be resolved. Please reopen if this is not the case.

**Comment by SteemitFbAdmin** [comment]
how do I reopen a ticket?
