### ISSUE TITLE
Post edits issue - Facebook Support for Amy Masiker

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#348]
Amy Masiker said on our Facebook Page:

"I hope that I can get to someone here. I need a little help. I have a couple posts that I need to edit. I stupidly posted my private email and I need to remove it but everytime I've tried to edit the posts, there's an error. I've tried on mobile, web, different browsers, ect. Please let me know what I can do. Thanks.

I am giving him the link to this issue in order for him to follow up on it.

**Comment by roadscape** [comment]
How old is the post? Posts older than 30 days cannot be edited.
