### ISSUE TITLE
Password issue - Facebook Support

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#349]
> no i have the proof that i saved/screenshot the password before i registered and it still doesn't let me sign in...after that i submitted the information than nothing happened, than i tried log in and it says error

[image removed]

I am giving him the link to this ticket for him to follow up with this issue.

**Comment by roadscape** [comment]
I have sent you a message on steemit.chat for follow up.

**Comment by jcalfee** [comment]
@roadscape can this be closed?
