### ISSUE TITLE
Twitter user-growth tactics work on steemit

### ISSUE THREAD

**Issue by faddat** [steemit/steemit.com#350]
This is a BAD thing.  

I'm talking about automating "follows" and waiting for people to "follow back" and then automating an un-follow, as well.  It's jerk-tastic, and it works on steemit now.  

I'm not a fan of the followers or the reblogs, TBH.  It was better as a firehose.

**Comment by sneak** [comment]
What's bad about it? Followers are free to also unfollow you back if they so choose.

**Comment by valzav** [comment]
@faddat are you suggesting us to block automated following? Probably I don't understand what the issue is.

**Comment by faddat** [comment]
@sneak 
Really?

1. This puts algos in front of people.  
2. This disadvantages users who don't write scripts to add every freakin user on the chain.
3. This increases the learning curve on our network, just as it does on Twitter.
4.  (most important) It's obnoxious and disingenuous and says nothing at all about the actual relationships between users.  

@valzav ah, no, automated following is just API usage.  I'm suggesting that we get rid of the follow feature and return to being a firehose.  It was better that way.

**Comment by valzav** [comment]
hmm.. maybe "friend" relationship that requires both sides to agree would work better?

**Comment by faddat** [comment]
possibly?  Probably, even.  Anything that gives the advantage back to organic relationships.

**Comment by sneak** [comment]
I don't want people I follow to have to confirm that I am their "friend" or something for me to follow their feed.

Social networks choose directed graphs (twitter, g+, livejournal, et c) or undirected graphs (facebook, myspace, et c).  The former is much more appropriate for publishing, the latter for private sharing.

**Comment by sneak** [comment]
There is no "return to being a firehose" that you describe - that functionality is still there, both on the blockchain and on the web interface (click "new" or "hot" in the top nav).

**Comment by valzav** [comment]
I agree with @sneak here.

**Comment by sneak** [comment]
@faddat you are encouraged to make a tool for users to unfollow people who don't follow them back, as many have done for twitter. :D

**Comment by faddat** [comment]
Dear me.... we shall be a twitter-ocracy.....

I do get your reasoning, even if I'm not a very big fan of it.  Re: tooling, maybe down the line.  Got other tooling to built ATM.

**Comment by faddat** [comment]
https://steemit.com/blog/@remlaps/a-far-fetched-prediction

Is this what you want?

**Comment by sneak** [comment]
personally, yes. bots are a logical outgrowth of an open platform. anything you can do manually, on an open platform you can instruct your bot to do.

if the bots shouldn't be allowed to do it, humans must also be prohibited, as botting is everyone's right. i don't think we should prohibit humans from following and later unfollowing people, so i don't see how you would like to prevent the logical consequence of bots following and unfollowing people. i also don't see the harm in such a setup; is it that you think users of bots don't deserve their follower counts or something?

i suggest you ignore it. :)
