### ISSUE TITLE
"Pay me 100% in Steem Power" should be checked by default

### ISSUE THREAD

**Issue by hazinstore** [steemit/steemit.com#358]
Having everyone cash out their posts at the end of the day is depressing the price of the coin, but more importantly it's slowing people from powering up.  If the default were 100% SP and the user had to take active action in order to receive SBD or Steem I believe that the redistribution would proceed much quicker.  Just image if the average upvote on the platform was $1.00 or even $100.00  

Eitherway if you made this the default, the price would rise because there would be far less sellers.

Combined with some sort of highlight bonus for pure SP posts it would encourage hoarding by smaller fish and powering down by existing whales (since the price would rise they should naturally want to sell to take advantage of it)

I'm going to blog about this and invite everyone over here to discuss it.

**Comment by pfunks** [comment]
Because I don't think you can take back that action, I'd be really annoyed by not catching that and I think a few others would be too.

**Comment by iamsmooth** [comment]
I think this is better as an account setting. If you explicltly decide you want all of your posts paid that way, I don't see an issue. But the default you didn't intend but forgot to change would indeed by quite frustrating as @pfunks pointed out.

**Comment by hazinstore** [comment]
Agreed but with the stipulation that the default account setting should be on.  Especially for new users.  The more people this is set for, the faster power up occurs and the less liquidity is in the market, but more importantly people can enhance their power without thinking about it.  They just get more powerful over time.

**Comment by dgiors** [comment]
I think it would be a mistake to set 100% payout by default. I'm in favor of a user setting that would toggle your default 100% steempower on/off with the default set to off initially.

**Comment by iamsmooth** [comment]
I agree with @dgiors (as I likewise replied on your post). Trying to push the market a little is less important than the PR aspect and frustrated new users who didn't understand the setting and now have lost access to the earnings the earnings they thought they had. This system is complex and intimidating enough for new users; introducing a "gotcha" like that is a bad move both in terms of retention/morale and bad PR.

**Comment by RubelliteFae** [comment]
It should default to on, but when you click Post, it should say,

> You have selected to receive your entire payout in Steem Power. This is not a liquid asset. Would you like to post anyway?

This would prompt those who forget to uncheck it to turn it off and also explain the system a bit to newbies.

**Comment by hazinstore** [comment]
Yes I 100% agree with @RubelliteFae

**Comment by faddat** [comment]
I think this one is more or less fine as it is.  @hazinstore -- doing as you describe would be just one more way for haters to attack the platform while ignoring the fact that all other social media extracts value from its users instead of creating value with its users.

**Comment by thecryptodrive** [comment]
I think people should be able to set their defaults and the system remembers, I run community initiatives that payout funds to the community and to purchase billboards. If the default is 100% SP then I may forget and lock up the billboard money, lol! Would rather each user have the option to set his default.

**Comment by aaroncox** [comment]
Turning it on by default isn't a good initial experience for the user. 

Let the users earn all 3 currencies to begin with, experiment with them, and then decide if they want to receive their entire payment in SP at a later date. 

Forcing it upon them, while I agree would probably reduce liquid rewards, is also pretty shady.

**Comment by TimCliff** [comment]
I move that we close this issue.

**Comment by hazinstore** [comment]
Agreed, it's pointless now.
