### ISSUE TITLE
Permissions Printing Page Doesn't show entire Key if in portrait mode

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#360]
Please can someone have a look at the permissions printing page, if printed in A4 portrait mode only part of the key is shown, will ... at the end.

Only when using landscape mode is the full key printed.

Most users may not notice and print and store and later get locked out of their accounts because they don't have their full keys.

Thanks,

**Comment by jcalfee** [comment]
This screen has a printer version boolean, so they layout can be adjusted just for the print mode.  For example the show / hide button does not belong on the printout .. that would fix A4.. Maybe the key type label could appear above the key instead of column format too.

**Comment by thecryptodrive** [comment]
Sounds great James, I can't help with the coding though :)
