### ISSUE TITLE
The unneeded input box strikes again:

### ISSUE THREAD

**Issue by faddat** [steemit/steemit.com#365]
![image](https://cloud.githubusercontent.com/assets/7142025/18976870/a7116b74-86df-11e6-8d1b-e6ceb7da638c.png)

Instead of that, users should see:

![image](https://cloud.githubusercontent.com/assets/7142025/18976928/444749ea-86e0-11e6-97b6-8d054b9d8702.png)

And in the longer-term, we should probably allow for nearly-indefinite nesting from the back end, because nests create a clear framework for a conversation and I don't know of better alternatives (though the Medium.com format isn't half bad)

**Comment by pfunks** [comment]
>And in the longer-term, we should probably allow for nearly-indefinite nesting from the back end, because nests create a clear framework for a conversation and I don't know of better alternatives

Agreed 100X. The original reason for a nested comment restriction is no longer in the Steem code. Dan said it was too computationally expensive to keep track of parent comment rewards when replies under them gave 50% of their value to the parent. This never happened, but we still have comments that go only 6-deep. If it can't or won't be done in Steem, it can be done with a metadata hack on Steemit.

**Comment by faddat** [comment]
@pfunks 

Have you looked into anything like this yet?

https://github.com/charlieschwabacher/ultrawave
https://github.com/philholden/redux-swarmlog

The trouble, of course, would be bridging state between the chain and the swarm.  But I think that is likely to remain the trouble, no matter what we are looking into, and that we'll do best by finding new solutions to that issue suited to our needs.

**Comment by aaroncox** [comment]
I am for the removal of the limitation and handling it much like reddit does. After 5 or so depth, simply add a link below the 5th like so:

![image](https://cloud.githubusercontent.com/assets/677686/19019570/7212142e-8841-11e6-9f74-982b94c78005.png)

This would then take you deeper into the comment thread itself allowing the conversation to continue. 

We already have a navigation element now when you recurse into a comment thread, which would also make it easy to return to the original context of the conversation, [like so](https://steemit.com/witness-category/@jesta/re-onthewayout-re-jesta-jesta-witness-update-2016-09-30-20161001t055007716z)

![image](https://cloud.githubusercontent.com/assets/677686/19019584/b9eb6c78-8841-11e6-9895-a548cca6f9db.png)
