### ISSUE TITLE
Broadcast error can't post

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#366]
User @annieb is having posting issues, either with her main password or her posting key. She gets a broadcast error. However I don't seem to have a posting problem and we share the same office LAN. Anyone know what's with that?

![image](https://cloud.githubusercontent.com/assets/22358264/18985116/9f4f3f9e-86f6-11e6-9544-9b7adce5a5cc.png)

**Comment by roadscape** [comment]
Is anyone still experiencing this issue?

**Comment by thecryptodrive** [comment]
I will ask annieb and get back to you, thanks for following up.

**Comment by thecryptodrive** [comment]
Hi Tim, the user @annieb says she cannot log into her account at all.

**Comment by thecryptodrive** [comment]
Hi Tim

On further investigation, it turns out she can't access steemit.com at all, but what is weird is that she and I share the same office LAN, her's is network cable and mine is wireless connected to same router.

She gets this error:

![image](https://cloud.githubusercontent.com/assets/22358264/20638866/c32bc1c0-b3bb-11e6-8688-844c7626a2fd.png)

**Comment by Gandalf-the-Grey** [comment]
You have all your answers in screenshot above:
Check her DNS settings, but first of all, remove that browser hijacker "mysocialshortcut" ("...to a lot of troubles").

**Comment by thecryptodrive** [comment]
Thanks Gandalf, I will try on Monday, what I don't understand however is that she can access any other site except Steemit.com.

**Comment by roadscape** [comment]
Any news on this? Have not been able to reproduce it

**Comment by thecryptodrive** [comment]
Hey Tim

I haven't been able to work on that PC yet to troubleshoot, however this weekend I had a similar issue on my laptop, I googled and found this fix and it worked. Seems to be a DNS issue, but only affects steemit.com https://www.youtube.com/watch?v=ZCIEH_xZreg

**Comment by roadscape** [comment]
Be careful -- this sounds very much like it could be caused by malware. Both on your and her PC. 

I don't believe this to be an issue on the steemit.com side.
