### ISSUE TITLE
Add ability to mark some user's record in the database as bot

### ISSUE THREAD

**Issue by valzav** [steemit/steemit.com#371]

**Comment by aaroncox** [comment]
Would this be a voluntary flag? If so, would we just establish a standard using the `json_metadata` field and possibly just use `{"bot": true}` on the account?

**Comment by adcpm** [comment]
I agree but i would prefer to call it "app" rather than "bot" has it's involving more use cases.
We could use Steem Script standard for that (https://github.com/adcpm/steemscript).

**Comment by valzav** [comment]
This field is intended for internal use only - we are going to mark some of the users registered via faucet as bots if we think there is probability they are not real users.

**Comment by aaroncox** [comment]
Ahh, so you're adding tracking on your side for this. My apologies.
