### ISSUE TITLE
Add FAQ page to "hamburger" menu

### ISSUE THREAD

**Issue by nedsteem** [steemit/steemit.com#372]
See ned for page content

**Comment by nedsteem** [comment]
assigned to @valzav 

https://docs.google.com/document/d/1z6Lx28UtQed6FV3BIprQp_DzhAv6ZzH12f8QEYeW6v0/edit?ts=57ed7e36#

**Comment by valzav** [comment]
Done in this pull request https://github.com/steemit/steemit.com/pull/494
