### ISSUE TITLE
New Issue Opening an Account 

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#377]
Here is a new user having issue opening an account. What does he need to do?
(Adam Orłov)

>Couldn't create account. Server returned the following error:
10 assert_exception: Assert Exception creator.balance >= o.fee: Insufficient balance to create account {"creator.balance":"5.310 STEEM","required":"10.000 STEEM"} th_a steem_evaluator.cpp:107 do_apply {"op"😞"account_create",{"fee":"10.000 STEEM","creator":"steem","new_account_name":"delgato","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM58JYs7YKscgmbbscW6TSHx2W6kZjdhnjAePCktRmEiJJAcx3iu",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8bXxYJdCSVfuYoTUa9k784WfwMcw4Yt9ULYgZ4cPTGQdQsi6KU",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7EccGV9KptA6CNcAntSZckM1KVGjxFkThQxTWYCfMCy9rvSGwS",1]]},"memo_key":"STM8UnGqx7rK4MLBN45JcUdemfVxr7m9gboPbweQkpYLTbQjXKM9Q","json_metadata":""}]} th_a database.cpp:3033 _apply_transaction {"trx":{"ref_block_num":21136,"ref_block_prefix":3461440547,"expiration":"2016-10-01T20:56:48","operations":[["account_create",{"fee":"10.000 STEEM","creator":"steem","new_account_name":"delgato","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM58JYs7YKscgmbbscW6TSHx2W6kZjdhnjAePCktRmEiJJAcx3iu",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8bXxYJdCSVfuYoTUa9k784WfwMcw4Yt9ULYgZ4cPTGQdQsi6KU",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7EccGV9KptA6CNcAntSZckM1KVGjxFkThQxTWYCfMCy9rvSGwS",1]]},"memo_key":"STM8UnGqx7rK4MLBN45JcUdemfVxr7m9gboPbweQkpYLTbQjXKM9Q","json_metadata":""}]],"extensions":[],"signatures"😞"1f3f588cab63cb1c554cdf3c3d886843f6d99db52ae15d71bfec4cd671723c3b36213421eaae242d10d419f3a0040e1ae921760b7db2881c92723626771d1e377a"]}} th_a database.cpp:3037 _apply_transaction {"trx":{"ref_block_num":21136,"ref_block_prefix":3461440547,"expiration":"2016-10-01T20:56:48","operations":[["account_create",{"fee":"10.000 STEEM","creator":"steem","new_account_name":"delgato","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM58JYs7YKscgmbbscW6TSHx2W6kZjdhnjAePCktRmEiJJAcx3iu",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8bXxYJdCSVfuYoTUa9k784WfwMcw4Yt9ULYgZ4cPTGQdQsi6KU",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7EccGV9KptA6CNcAntSZckM1KVGjxFkThQxTWYCfMCy9rvSGwS",1]]},"memo_key":"STM8UnGqx7rK4MLBN45JcUdemfVxr7m9gboPbweQkpYLTbQjXKM9Q","json_metadata":""}]],"extensions":[],"signatures"😞"1f3f588cab63cb1c554cdf3c3d886843f6d99db52ae15d71bfec4cd671723c3b36213421eaae242d10d419f3a0040e1ae921760b7db2881c92723626771d1e377a"]}} th_a database.cpp:697 push_transaction digest 107a06ebc85d27776142af52f5e7f08313dbc1fc59f74bffd131bf264e26563c transaction 9052236451ce1023f0570109102700000000000003535445454d000005737465656d0764656c6761746f010000000001021f5da340f832a76298a5171e46ae3cd561f673acc58fe7da2fdcfa7587b1af5e010001000000000103e8492882bee9a025ad638bf6fc250946da8e35562729cb97c3b28aad6d6e76c40100010000000001033516b30fbbaf8d1f20e3e6635329336c28eab3309b633e0da778be6d7830e6ef010003d8f3acb88c87eb4f5fdd9aed3350325ace65e608dc5da3dbdedd4dde8a478a9c0000011f3f588cab63cb1c554cdf3c3d886843f6d99db52ae15d71bfec4cd671723c3b36213421eaae242d10d419f3a0040e1ae921760b7db2881c92723626771d1e377a {"ref_block_num":21136,"ref_block_prefix":3461440547,"expiration":"2016-10-01T20:56:48","operations":[["account_create",{"fee":"10.000 STEEM","creator":"steem","new_account_name":"delgato","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM58JYs7YKscgmbbscW6TSHx2W6kZjdhnjAePCktRmEiJJAcx3iu",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8bXxYJdCSVfuYoTUa9k784WfwMcw4Yt9ULYgZ4cPTGQdQsi6KU",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7EccGV9KptA6CNcAntSZckM1KVGjxFkThQxTWYCfMCy9rvSGwS",1]]},"memo_key":"STM8UnGqx7rK4MLBN45JcUdemfVxr7m9gboPbweQkpYLTbQjXKM9Q","json_metadata":""}]],"extensions":[],"signatures"😞"1f3f588cab63cb1c554cdf3c3d886843f6d99db52ae15d71bfec4cd671723c3b36213421eaae242d10d419f3a0040e1ae921760b7db2881c92723626771d1e377a"]}

**Comment by thebitcoiner** [comment]
According to the exception, the creator balance of 5.310 STEEM is not enough to create the new account, which is 10 STEEM. Looking at the steem account wallet, there is plenty of balance to create a new account. I suggest trying again.

**Comment by jcalfee** [comment]
The creator account has received funds since this error happened: `"expiration":"2016-10-01T20:56:48",`

**Comment by adamorlowskipoland** [comment]
So what should I do?
Try create new account?

**Comment by jcalfee** [comment]
Sorry.. yes, the account was re-filled.  That will fix this error.  Let us know if anything comes up.

**Comment by dllud** [comment]
I am facing the same issue right now. Please top up your creator account.
