### ISSUE TITLE
Confirmation Link not working

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#378]
I've had 3 people already telling me that the confirmation code they got by email brings to a page telling them: 

> confirmation code not found.

What can they do to remedy this?

**Comment by jcalfee** [comment]
'confirmation code not found' means it did not expire, it really was not found.  This could be a temp system issue if that table was reset or it could be an old email link.  In any case the confirmation link can be resent.  So has this resolved itself?

**Comment by roadscape** [comment]
Please comment/reopen if there are any updates.
