### ISSUE TITLE
Vote Slider not working in IE

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#381]
The vote slider was not working in IE, which was fixed in https://github.com/steemit/steemit.com/issues/279. The issue seems to be happening again.

**Comment by roadscape** [comment]
We had a release yesterday, is this still an issue?

**Comment by TimCliff** [comment]
Yes.

**Comment by roadscape** [comment]
I can't reproduce this in IE11 or Edge.

**Comment by TimCliff** [comment]
Sorry, user error :P I had an account with less SP than my main account (243.161 STEEM), and it used to be above the threshold for the slider. (That's the account I always use IE with.) It looks like the threshold changed though, because that account is no longer provided with the slider. I logged out and tried it with my main account, and the slider showed up. (Closing the issue, sorry to have wasted your time.)
