### ISSUE TITLE
markdown rendering bug: single newline is rendered as a hard break

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#383]
Per the markdown spec, a single newline is equivalent to a space for wrapping - for paragraph breaks, `\n\n` is required.

This allows ragged hardwrapping in markdown, e.g.:

```
This is a paragraph that
continues on multiple lines of varying
length.

This is the second
paragraph.
```

This should render as two paragraphs, with one paragraph break between them.

Currently, this is rendering as the ragged paragraphs as reflected in the raw markdown, which is wrong.

**Comment by roadscape** [comment]
https://github.com/steemit/steemit.com/issues/12
