### ISSUE TITLE
Workaround for Youtube gaming streams - Sry if this is in wrong place, first time in here.

### ISSUE THREAD

**Issue by sykochica** [steemit/steemit.com#385]
Pixellated mention to post on the workaround from gaming.youtube.com streaming.

The workaround was to have the streamer change the gaming.youtube to www.youtube, where they could then get the embed code. Pixellated mentioned since all 'it requires is allowing that secondary source url gaming.youtube.com' that is might be an easy fix. 

I should note that gaming.youtube only gives a share option of a direct link (and not an embed code.) While I assume the link would work since youtube is already supported, it was worth mentioning in case there is some issue there.

I don't personally place this with any high priority, but is could be an interesting group to market to.

**Comment by roadscape** [comment]
We would like to include as many embed options as possible but we will not adding any more until we find a more secure way to do so.
