### ISSUE TITLE
Facebook and Twitter share caching old broken image links even if new link restored

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#391]
Strange issue, so I created a post which had the main image as a postimage.org link, But I deleted the image on postimage by mistake, I then reuploaded it and inserted the new link back in the post. 

It displays properly on Steemit but when trying to share out to Facebook and Twitter all is see is the below, I even changed the link to be hosted with Steemimg but it still was caching the postimage image link that was broken. The linkedin share works fine, only FB and twitter does not.

![image](https://cloud.githubusercontent.com/assets/22358264/19055096/a2be949e-89c2-11e6-8dad-fe79fe2a505a.png)

**Comment by jcalfee** [comment]
This is your image directly in Facebook: 
![image](https://cloud.githubusercontent.com/assets/204121/19056003/d608f192-8994-11e6-9cba-870939b9f34b.png)

**Comment by jcalfee** [comment]
Correction: in Facebook, I did see your image appear after I typed space.  So the Facebook image is fine.

They should be looking at this from the html in your post:
```
<meta property="og:image" content="https://s19.postimg.org/q8nbol8r7/thumb.jpg" data-reactid="10"/>
<meta name="twitter:image" content="https://s19.postimg.org/q8nbol8r7/thumb.jpg" data-reactid="20"/>
```

Does it happen every time with postimg?

**Comment by jcalfee** [comment]
I emailed postimage..

**Comment by thecryptodrive** [comment]
Hi James

No it doesn't happen every time, only if I delete the original image and replace it with a new image link, it still references the original deleted image. But I also created a steemimg account and tried putting that image in but the broken postimage one was still being referenced, so that's why I thought it was on Steemit's side where the issue lies.

**Comment by jcalfee** [comment]
Are you saying you replaced the original image in the post?  What do you mean "still references the original deleted image"?  Are you saying it did not help because FB still shows it as broken?

**Comment by thecryptodrive** [comment]
Hi James let me break it down in steps for ease of understanding:
1) I inserted the image and posted
2) I wasn't happy that the image was too big for the thumbnail so I changed the image and deleted the original one on postimage.
3) When I tried to share on FB and Twitter it was still referencing the now broken link.
4) even when I paste the link in steemit.chat it shows as broken as per screenshot below done right now:
![image](https://cloud.githubusercontent.com/assets/22358264/19082323/f3233ed0-8a5d-11e6-8a11-74521bf76393.png)

So if it is broken on steemit chat too, it must be something with how Steemit is broadcasting the link.

**Comment by jcalfee** [comment]
Looks like we are severing the new image.  I looked at the `.jpg` files in the html source and none of them are broken.

For refernce, here is the link to the post: ,https://steemit.com/witness-category/@thecryptodrive/ricardo-goncalves-thecryptodrive-first-steem-witness-in-africa-a-witness-for-the-people

It looks like we are not sending any cache control headers from steemit.  I wonder if that might help.

**Comment by roadscape** [comment]
Is anyone still experiencing this behavior?

**Comment by roadscape** [comment]
Please open a new ticket if this issue arises.
