### ISSUE TITLE
Add the ability to save a post

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#398]
Add the ability to save a post. It could either be saved on Steemit, or prompt the user to save a file on their harddrive, which could be "opened" later.

**Comment by Someguy123** [comment]
For now, any post you're typing is saved to localstorage, so if you leave the page you shouldn't lose your post.

**Comment by TimCliff** [comment]
True, but I don't completely trust it. I have fallen back on it a few times (thankfully) but it would be a horrible user experience to type up a huge post and have it lost somehow. A saved 'hard copy' would really be preferred. 

Also, ideally a user could save drafts of multiple posts that they are working on. A possibility too would be to pay to expand the number of drafts that can be saved, or provide more 'free' once a user reaches a certain amount of SP.

**Comment by sneak** [comment]
For now, type your post in a text editor locally and save it as required.  Copy and paste it into the browser window when you're ready to publish.

Drafts/saving are on the roadmap, but no timeline yet.  (There are also about a million other things on the roadmap, too. :)
