### ISSUE TITLE
Support Auto-Upvote via Steemit.com

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#399]
This may be considered a controversial feature, but users can already do this with Streemian/bots. Providing this to all users would be a way to level the playing field. (Open for discussion)

    Auto upvote anything a specific user posts after X amount of time
    Auto upvote anything a specific user resteems after X amount of time
    Auto upvote anything a specific user upvotes after X amount of time

**Comment by roadscape** [comment]
This would require a daemon to be running on the client's machine, which is out of scope for steemit.com for now.
