### ISSUE TITLE
Some context-surrounded permalinks show the comment with an upper portion of the comment cut off

### ISSUE THREAD

**Issue by arhag** [steemit/steemit.com#4]
See for example: [this](https://steemit.com/test/@arhag/another-attempt-of-breaking-the-steemit-commenting-system-this-time-i-have-to-avoid-using#@arhag/re-arhag-another-attempt-of-breaking-the-steemit-commenting-system-this-time-i-have-to-avoid-using-20160515t204211156z) and [this](https://steemit.com/bitshares/@jbradford/why-doesnt-bitshares-dominate-ethereum#@arhag/re-xeroc-re-nikolai-re-nikolai-re-jbradford-why-doesnt-bitshares-dominate-ethereum-20160515t174621177z-20160515t174836188z-20160515t192959807z-20160517t041311063z).

**Comment by jcalfee** [comment]
I added 2 replies to your first link where I adjusted the code to ensure the permalinks will not get too long.  

Is there something else I need to do here?

**Comment by arhag** [comment]
@jcalfee: Although that is a different bug than the one in this issue (I guess I forgot to add that bug to this github?), yes I suppose that solves that particular problem of not being able to reply when you should. 

I still prefer a nicer way of generating permlinks. See discussion [here](https://steem.slack.com/archives/potential-bugs/p1463364385001052) as well as Dan's alternative suggestion just below it.

I'll repost the text here because who knows how long it will last on the Slack before it disappears:
```
----- May 15th -----
arhag [10:06] 
I think the nesting of permlinks is a bad idea. I suggest the following format for generating the permlink of a post (top-level) and for a comment.

For a post:
<sanitized_short_title>-<random_value>
where:
<sanitized_short_title> = A sanitized (to be a valid permlink) and shortened version of the title that is at most 244 characters long. Nearly the same algorithm used to generate the permlink of posts on Steemit now can be used for this.
<random_value> = A randomly generated value that is encoded into Base58 and then truncated to 10 characters.

For a comment:
re-<parent_account_name>-<sanitized_shorter_top_level_title>-<random_value>
where:
<parent_account_name> = The account name of the author of the post/comment that this comment is replying to (we know that this can at most be 16 characters long).
<sanitized_shorter_top_level_title> = A sanitized (to be a valid permlink) and shortened version (even more so than <sanitized_short_title>) of the title of the top-level post of the discussion thread that is at most 225 characters long. The same algorithm that was used to generate <sanitized_short_title> will be used here except that it will pass the smaller character limit to the function.
<random_value> = A randomly generated value that is encoded into Base58 and then truncated to 10 characters. (edited)

arhag [10:15 PM] 
Actually if you allow two consecutive dashes in permlinks (currently allowed), then I would amend the previous format for the comment to:
re-<parent_account_name>--<sanitized_shorter_top_level_title>-<random_value>
where now the character limit for <sanitized_shorter_top_level_title> is 224.

[10:16] 
That way you get the nice little benefit that it is unambiguous which is the account name and which is the title just by looking at the permlink. But it's not important, so if you want to disallow consecutive dashes than the original proposal is fine with me.


----- May 16th -----
dan [8:41 AM] 
Actually, I think it would be better to do:  "re-parent_post_id-time"

[8:41] 
much shorter, avoids duplicates, etc.
```

**Comment by jcalfee** [comment]
What we have now is this:
 "re-parent_post_id-time" ..

Now, each parent mentions its `re-parent`.. so you will see `re-parent-re-parent-re-parent-post-time` all the way up to the root.

On the other hand, if parent is defined at root parent that would shorten the permlink more.  So any reply can simply not add its own `re-parent` prefix and use its parent (the root will ultimately be used) and replace the timestamp with its own timestamp.

**Comment by roadscape** [comment]
Can this be closed?

**Comment by arhag** [comment]
@roadscape: Yes.
