### ISSUE TITLE
Allow users to sign up if they don't have a Facebook or Reddit account by paying their admission fee

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#403]
This could possibly be accomplished with a link to AnonSteem from @someguy123

**Comment by Someguy123** [comment]
Thanks for the mention @TimCliff :)

I wouldn't complain about the extra attention, many people already use it as the go-to solution for new accounts without social media.

**Comment by TimCliff** [comment]
Yes, agreed. A lot of new users who are just finding out about the site through other means though probably don't know about it. I suspect a lot of potential new users just leave when they see there isn't a way for them to sign up.

**Comment by sneak** [comment]
For now, we are working on other methods. Most users that want to sign up don't have any cryptocurrencies. Stay tuned.
