### ISSUE TITLE
Create a "Welcome to Steemit" page

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#404]
There should be an informative landing page for new users when they sign up

**Comment by sneak** [comment]
Want to write one and send in a Pull Request? :)

**Comment by TimCliff** [comment]
Sure. I'll probably solicit quite a bit of help, but I'll take it on :)

**Comment by jcalfee** [comment]
Great, call me out in github (@jcalfee) if you have any questions..

**Comment by TimCliff** [comment]
Thanks!

**Comment by TimCliff** [comment]
If anyone is interested in contributing content for the welcome page, I created a post to gather input from the community:
https://steemit.com/help/@timcliff/help-us-create-the-official-welcome-to-steemit-landing-page-community-input-needed-part-1

**Comment by TimCliff** [comment]
Hi @sneak and @jcalfee - We have the content for the page pretty much ready. What is the process as far as having someone from Steemit review it? Should someone take a look at it before we start to code it into the page, or would the best way be to just submit a pull request with our first draft? I've asked Ned to take a look at it too, but I don't know if he will have time.

The content is here:
https://steemit.com/help/@timcliff/an-onboarding-solution-in-the-works-creating-the-official-welcome-to-steemit-landing-page-community-draft-content-review

**Comment by sneak** [comment]
Send a PR with a WIP title with just a draft... we can pull it into a branch. Does github let you make a PR to a new in-repo branch? That would be best.

**Comment by TimCliff** [comment]
I don't think we are able to create a new branch. Is there one that already exists that we could use?

Also, can we submit a text file or word document with the content, or would it be better to convert it into code first? (We will have an actual page / code file for the final pull request, but right now we are just looking for content review.)

**Comment by sneak** [comment]
branch created: https://github.com/steemit/steemit.com/tree/404-welcome-page

Ultimately you're going to have to drive this - don't use word, but if you actually want to *ship* this, it's going to have to be in the same format as the existing pages.  You could do a draft in plain text or markdown but you're going to need to integrate it, too, so you might as well put the draft into the right format for integration.

**Comment by TimCliff** [comment]
Sounds good, thanks!

**Comment by roadscape** [comment]
Added in #585
