### ISSUE TITLE
Create a Fiat <-> Steem Exchange

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#405]
Is it possible to integrate something into Steemit.com that would allow users to exchange 'regular' money for Steem/SBD and vice versa?

**Comment by Someguy123** [comment]
It would require collaboration from an exchange which has money transmitter licences, such as BitStamp, or CoinBase, since exchanges like Poloniex don't even touch real fiat, only things like Tether USD

**Comment by abitmore** [comment]
[BlockTrades](https://blocktrades.us) supports OPEN.USD which is a fiat IOU token issued by [OpenLedger](https://bitshares.openledger.info). However there is currently no direct pair between STEEM/OPEN.USD or SBD/OPEN.USD on blocktrades, perhaps we can ask blocktrades to add one?

**Comment by abitmore** [comment]
I noticed that these direct trading pairs have been added to https://blocktrades.us/:
* Steem Dollar -> OPEN.USD
* OPEN.USD -> Steem
* OPEN.USD -> Steem Dollar
* OPEN.USD -> Steem Power

Perhaps it would be better if we promote it on Steemit.com, for example add a "pay with USD" option on the "Buy Steem" page?

**Comment by faddat** [comment]
@TimCliff,

Doing this could open one of those boxes, belonging to Pandora, or possible one of those cans, full of worms.  The site and possibly the community would likely find itself under scrutiny from god-knows-who looking to "enforce" (intentionally) vaguely worded crap.  So, while indeed, it's a good idea, and it's something we SHOULD be able to do, it's also probably something that it's best we do not do.

**Comment by sneak** [comment]
This is off-topic for this repository. Please don't open issues on this repo unless it's specifically related to the code inside.
