### ISSUE TITLE
NSFW Updates

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#406]
1. Allow the user to show/hide NSFW content in their settings (suggestion from @thovre)
2. Require a user to acknowledge that they are 18+ before allowing the 'show' setting to be enabled (suggestion from @wisehammer)

**Comment by faddat** [comment]
Porn isn't going to go away, so I'm in favor of dealing with it well.  

This said, right now I'm not even sure that a setting like that could be saved on the back end.  Should be able to do it on the front and save it....."however we're saving things like logins."

**Comment by TimCliff** [comment]
FYI - The community has been seeing an influx in NSFW type content, and it seems like this is likely to continue to increase.

**Comment by faddat** [comment]
Do you have an opinion on this? I see it as positive,  but I know others do
not.

**Comment by TimCliff** [comment]
GitHub probably is not the right place for that part of the conversation :)

From the coding perspective, I think that if we allow it but give users the right tools to chose whether or not to view it - we are striking the right balance.

**Comment by sneak** [comment]
2 we probably aren't going to bother with unless legally required to do so.

1 is a good suggestion and we will implement it eventually, but we have a pile of more pressing stuff to do first so it won't be soon.

**Comment by TimCliff** [comment]
I ran some tests and here is how it seems to currently work:

1. "nsfw" tag as main tag
- Does not show up in followers' feeds
- Does not show up in new/trending/hot (unless specifically browsing nsfw)
- Does not show up in the user's blog
- Does not show up when Resteemed
- Does show up if you specifically browse the nsfw tag

2. "nsfw" tag as a secondary tag
- Does show up in followers' feeds
- Does show up in new/trending/hot
- Does show up in the user's blog
- Does show up when Resteemed
(Behaves like a 'normal' post)

There does seem to be some inconsistency between "nsfw" being the first tag, or one of the secondary tags. I'm not sure if this is by design or not..

For the first way of handling it, the 'problem' is that it makes it very hard for users who are interested in NSFW content to use the traditional Steemit features (followers/feeds, resteem, etc.) for it. (This _may_ be by design.) Most users who are posting NSFW content though, are now purposely not using "nsfw" as the first tag - because then it will never get seen.

For the second way of handling it, it is currently upsetting a lot of users. There is a lot of adult rated material showing up when people are just 'browsing' the site. While I disagree with the people who are against having NSFW content on the site at all - I do agree that users should at least have a way to filter it out if they don't want to see it.

**Comment by TimCliff** [comment]
Closing- discussion moved to 827
