### ISSUE TITLE
Add a Delete Post button

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#409]
Give the users the ability to delete a post. It would not be able to be completely deleted from the blockchain, but the text/title could be deleted and the post could be hidden from feeds and the user's blog.

**Comment by roadscape** [comment]
There is already an option to delete a post; IIRC the requirement is that is has no votes and no replies. If this does not suffice, we can implement something later on which could allow you to hide a post as long as the payout was 0.
