### ISSUE TITLE
Can't scroll far enough to see Linkedin Share button.

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#410]
When you share a post, the Linkedin button on the dropdown menu goes out of view even if the window is fully scrolled down.

![image](https://cloud.githubusercontent.com/assets/22358264/19072830/ba093fee-8a37-11e6-98dd-5c50734847bb.png)

**Comment by mcifani** [comment]
I believe this has been addressed in a recent commit. Will keep an eye on it/adjust otherwise.

**Comment by thecryptodrive** [comment]
ok thank you, feel free to close this if you feel appropriate.

**Comment by mcifani** [comment]
- [ ] Fix UI/CSS Bug for share menu on post modal

**Comment by roadscape** [comment]
Related to #392
