### ISSUE TITLE
Can't change primary tag once posted

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#415]
When one makes a mistake on the first tag and wants to change it after it can't be done:
![image](https://cloud.githubusercontent.com/assets/22358264/19090857/920a69b6-8a80-11e6-8e55-7c7fa1ac99ea.png)

**Comment by roadscape** [comment]
This is a limitation of the node/backend.. we may have suggested categories in the future which would help prevent mistakes
