### ISSUE TITLE
[Suggestion] Floating Editor For Submitting Post Instead of Fixed

### ISSUE THREAD

**Issue by JasonMcz** [steemit/steemit.com#42]
https://steemit.com/suggestions/@jasonmcz/suggestion-floating-editor-for-submitting-post-instead-of-fixed

<html>
<h2>Hi guys!<br>
<br>
<strong>I am here to write up this suggestion for making some improvements to the GUI for post submission. I recently wrote an article under recipe section -- </strong><a href=" https://steemit.com/kitchen-cremefraiche/@jasonmcz/original-recipe-my-30-min-salmon-ramen-hack"><em><strong>Recipe: My 30 min Salmon Ramen Hack. </strong></em></a><strong>While I was writing this post, I've noticed how cumbersome it could be for someone who doesn't know how to write with </strong><em><strong>Markdown</strong></em><strong> or </strong><em><strong>Html </strong></em><strong>when the story is ridiculously long and we will have to scroll UP and DOWN all the time to make text edits or inserting a picture</strong></h2>
<h2><em>Examples found here:</em></h2>
<h3><em>The Current UI for Post Submission :</em></h3>
<h3><em><br>
</em><img src="http://i.imgur.com/phsfYeo.png" width="800" height="590"/></h3>
<p><br></p>
<p><br></p>
<p><br></p>
<p><em>But when your article is too long :</em></p>
<p><img src="http://i.imgur.com/xAi7kno.png"/></p>
<p><br></p>
<p><em>What if we do it this way :</em></p>
<p><img src="http://i.imgur.com/WGo6gP2.png" width="800" height="590"/></p>
<p><br></p>
</html>

**Comment by jcalfee** [comment]
We are planning to use a medium style editor.  This will show a menu inside of your document where your cursor is.  Mostly when you select text the menu will appear.

**Comment by JasonMcz** [comment]
Thanks. Let us know when you implement. Happy to build something on my fork and create pull as well if you haven't worked on it.

**Comment by jcalfee** [comment]
I'll update this ticket https://github.com/steemit/steemit.com/issues/185 .. You can subscribe.
