### ISSUE TITLE
non alphanumeric characters should be stripped from permlink conversions

### ISSUE THREAD

**Issue by abitmore** [steemit/steemit.com#423]
Non-alphanumeric characters should be stripped from permlink conversions, not translated to english.
Example: https://steemit.com/blocktrades/@blocktrades/blocktrades-adds-new-open-usd-less-than-greater-than-steem-steem-dollars-purchase-paths

**Comment by sneak** [comment]
good catch. :)

**Comment by sneak** [comment]
[^a-zA-Z0-9-_] methinks

**Comment by sneak** [comment]
this isn't backend at all, is it? @mvandeberg?

**Comment by mvandeberg** [comment]
The only restriction we have on the permlinks in the backend is they must be UTF-8 and must be less than 256 characters. We could increase the restrictions in a future hardfork if desired. Whatever the front end says is the permlink in an op, so long as if fits the mentioned restriction, is the permlink. We aren't doing any conversions on the backend. We could do some conversions in the backend, but it might cause a collision if applied retroactively. Knowing when to convert and when not to in the API would be challenging.

**Comment by roadscape** [comment]
Most punctuation is handled as expected, `<` and `>` were the only outliers.. they will now be stripped out
