### ISSUE TITLE
need a new 404 page that doesn't invoke images of competitors ;)

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#425]

**Comment by pfunks** [comment]
You mean reddit?

**Comment by pfunks** [comment]
You mean reddit? For illustration: https://www.reddit.com/lks5klsw0iv

**Comment by mcifani** [comment]
I'm currently resolving https://github.com/steemit/steemit.com/issues/844 - Will handle this as well and help resolve a few related items.
