### ISSUE TITLE
Image Cache: svg images are broken

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#43]
broken: https://img0.steemit.com/0x0/https://duckduckgo.com/assets/dax-alt.svg
works: https://duckduckgo.com/assets/dax-alt.svg

**Comment by aaroncox** [comment]
What exactly is the image processor on that subdomain doing? Is it a security measure to ensure no malicious images make it through or a caching solution of some sort? 

I was experimenting with SVGs in my posts and bumped into this problem. I'd love to get this resolved :)

**Comment by roadscape** [comment]
The previous library couldn't handle them, and currently there's a conservative whitelist of allowed image types. I did successfully test SVGs earlier today with the new library we're using. Just need to look into potential security issues w/ this format. Besides that, the main concern is how much utility does it add vs. how much does complexity grow.

**Comment by roadscape** [comment]
SVG is a complex format that would require care to secure. (e.g. SVG allows embedded javascript) If we were to allow SVG uploads we would need to run them through some form of cleaner/sanitizer. At this point in time, it doesn't seem worth implementing.

Reference: https://core.trac.wordpress.org/ticket/24251

**Comment by jcalfee** [comment]
Can you at least issue a forward so the posts are not broken?

**Comment by roadscape** [comment]
Passing through the original SVG is dangerous, we would need to at least rasterize them server-side and serve them as PNG. It's quite a can of worms afaict..

https://bjornjohansen.no/svg-in-wordpress
"What is at issue is that, unless you can find a reliable way to strip out the problematic bits, you should treat SVG from untrusted users the same way that you treat HTML from untrusted users."
