### ISSUE TITLE
When viewing a post, show links to other active posts from the same author

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#432]
The idea was suggested in this post:

https://steemit.com/steemit/@profitgenerator/a-very-good-idea-for-steemit

Also related to the suggestion in this issue: https://github.com/steemit/steemit.com/issues/66

**Comment by mcifani** [comment]
I like this idea and seems well liked from the other thread. I wonder instead of same author it should potentially be from the same category?  That could get a better click rate with related posts.

**Comment by TimCliff** [comment]
_"I wonder instead of same author it should potentially be from the same category?"_

That is what https://github.com/steemit/steemit.com/issues/66 is about :)

**Comment by roadscape** [comment]
Showing active posts from the same author will not be as useful as showing trending/hot posts from the same category. Posts will be much more stale, so it's not a good default. Let's explore this concept starting with #66 and expand on it later.. @mcifani if you'd like to tackle that one feel free!
