### ISSUE TITLE
Write-in witness vote broken in IE?

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#435]
I tried multiple times to submit a witness vote using the "write in" feature on the https://steemit.com/~witnesses page using IE, and the vote didn't register. It works in Firefox and Chrome. Has anyone else experienced this issue?

**Comment by roadscape** [comment]
Which version of IE? I am able to use the write in feature on IE11

**Comment by TimCliff** [comment]
I was using IE 11. I was able to get it to work by retrying a few times. The times it didn't work seemed like they might have been more of a timeout issue, although Firefox and Chrome weren't having any timeout issues when I tried using them at the same time.

**Comment by roadscape** [comment]
Ok, there may have been some network issues at the time. Closing for now, let us know if this issue returns.
