### ISSUE TITLE
Witness page not loading with votes selected

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#437]
When I load the witnesss page, it loads without any of my selected witnesses selected and says I have 30 votes left. When I refresh the page it updates correctly. I was able to consistently reproduce with both Firefox and Chrome.

https://steemit.com/~witnesses

**Comment by roadscape** [comment]
From #453

> I just logged out of steemdrive and steemsports accounts which I was using to vote witnesses, now I logged in as thecryptodrive and it doesn't show the witnesses I'm voting for. I'm using Chrome and tried ctrl+R to refresh also.
> 
> ![image](https://cloud.githubusercontent.com/assets/22358264/19236431/ac3990a2-8ef7-11e6-9928-fcf1cc1c8694.png)
>

**Comment by roadscape** [comment]
I notice the following behavior:

Case 1

1) go to https://steemit.com/created
2) click 'Witnesses' in the menu
3) witness votes show

Case 2

1) go to https://steemit.com/ (while logged in -- you should see your feed)
2) click 'Witnesses' in the menu
3) witness votes do *not* show

Case 2 seems to happen whenever *your own* user account page (any tab) is loaded first.
