### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by mapalanet** [steemit/steemit.com#438]
When i command: 
`npm run prod`

Website displayed clearly, but if i try open any personal blog, i get answer like that: 
PostsList --> Missing content key mapalanet-first-travel-community-in-the-steemit-eco-system
PostsList --> Missing content key the-theory-of-life-lines-applied-to-steemit-science
PostsList --> Missing content key teoriya-linii-zhizni-v-primenenii-k-steemit-i-razvitie-informacionnoi-sistemy-iznutri-science

And articles are not displayed. This trouble for any blog - mine, or any other. May be reason in database? How i can check it and fix?

**Comment by mapalanet** [comment]
Any suggestions? How we can growth eco-system, if have problems with source code like that? %(

**Comment by roadscape** [comment]
Try building steemd from latest develop, there was an API change

**Comment by mapalanet** [comment]
After rebuild problem still. 
FetchDataSaga has a requests, which different with functions in block-explorer. It seems, like nobody not merged changes.

**Comment by roadscape** [comment]
What's the output of `git rev-parse HEAD`?

**Comment by mapalanet** [comment]
`git rev-parse HEAD`
64a20c8492fabad4af043d3f76fe16ddde9144ab

**Comment by roadscape** [comment]
Ah, I was referring to the *steemd node* itself. Are you using a public API or running your own node? It needs to be rebuilt from latest develop

**Comment by mapalanet** [comment]
I use public node, but trouble definitely with API, fetchdatasaga.js and something more, cause there is old API commands. You can check it in console: www.mapala.net/@anmuravjev

SteemApi exec 0 get_discussions_by_blog ( [Object] 0: Object length: 1__proto__: Array[0] )

But API doesn't have `get_discussions_by_blog` anymore

**Comment by roadscape** [comment]
`get_discussions_by_blog` still exists, but its return format may have changed.

The public API you are using is probably out of date.

**Comment by mynameiskeo** [comment]
@mapalanet that's because you use wss://node.steem.ws  i think, and they are not up to date in my opinion. I just tried with another one and it's working. Had the same issue
@ekitcho.

**Comment by mapalanet** [comment]
@mynameiskeo By the way, what node you use?

**Comment by thebitcoiner** [comment]
That would require steem.clawmap.com to be accessible over RPC, over I don't know if they have configured it like that. You could use wss://steemit.com/wspa

**Comment by mapalanet** [comment]
Yes, this is works. Thanks, problem fixed.
