### ISSUE TITLE
"Replies" tab on user profile page should be "Replies to @username"

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#444]
Current text is misleading as it implies they're the replies by the user whose name is writ large directly above...

**Comment by roadscape** [comment]
I believe tabs have been renamed since this issue was created. Does they make more sense now?

**Comment by pfunks** [comment]
I was about to make an issue about this but found this in the search. It's such a tiny, two-byte change...

**Comment by TimCliff** [comment]
I might try to take a stab at this. Am I understanding the issue correctly?

We want to change this:
![image](https://cloud.githubusercontent.com/assets/20735105/21580296/127ae30e-cfb0-11e6-825b-101328e6445d.png)

To this:
![image](https://cloud.githubusercontent.com/assets/20735105/21580298/716158ee-cfb0-11e6-9b23-bb7259f256b1.png)

Also, if a user is looking at their own replies should it still just show "Replies" or should it also show "Replies to @username" there too?

**Comment by pfunks** [comment]
Oh I'm not sure about that, I thought the issue was mainly the word "by" in the page's title. See the title of this page: https://steemit.com/@timcliff/recent-replies

**Comment by TimCliff** [comment]
Ah, ok. That makes a lot more sense actually. So change "by" to "to" here:
![image](https://cloud.githubusercontent.com/assets/20735105/21583456/5a852686-d047-11e6-8162-ba2b5ac0b722.png)
