### ISSUE TITLE
timestamps don't link to entity so timestamped

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#447]
The "&lt;x&gt; &lt;units&gt; ago" should link to the specific comment or post in question that is timestamped.

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [timestamps don't link to entity so timestamped #447](https://trello.com/c/3dIeA7XQ/84-timestamps-don-t-link-to-entity-so-timestamped-447)
