### ISSUE TITLE
Add a "Share" button for post payouts

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#449]
This would help a ton for recruitment! When people get paid for their posts and are excited, lots of them will want to share the good news with their friends on other social media sites :)

**Comment by sneak** [comment]
It might be better if you put all of your feature ideas and requests into a big list and emailed it to me directly at sneak@steemit.com instead of filing them one by one in the bugtracker. :)

**Comment by TimCliff** [comment]
Email sent :)

**Comment by TimCliff** [comment]
Closing for now. If we decide to add this later, we can re-open.
