### ISSUE TITLE
Private Key Does Not Show

### ISSUE THREAD

**Issue by gmkarl** [steemit/steemit.com#450]
When I click "Show Private Key" for my posting key, nothing is displayed except for a print button.  Clicking the button prints only my public keys.

I am using Tor Browser 6.0.5 based on Mozilla Firefox 45.4.0 .  I am using NoScript 2.9.0.14 and have all scripts enabled for the page.  I am on Linux, specifically Whonix based on Debian 8 (jessie).

**Comment by roadscape** [comment]
Could you please check the console and report if there are any errors logged?

**Comment by roadscape** [comment]
Please reopen if this issue persists.
