### ISSUE TITLE
Facebook Account that is verified but Steemit doesn't recognize it 

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#452]
> I have a primary email on Facebook.  It is verified.  Steemit says "×
Facebook login didn't provide any email addresses. Please make sure your Facebook account has a primary email address and try again."  It IS VERIFIED.

Can you please help him? I will tell him to keep track of this ticket

**Comment by valzav** [comment]
Facebook verification is no longer used
