### ISSUE TITLE
Not showing witnesses i'm voting for

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#453]
I just logged out of steemdrive and steemsports accounts which I was using to vote witnesses, now I logged in as thecryptodrive and it doesn't show the witnesses I'm voting for. I'm using Chrome and tried ctrl+R to refresh also.

![image](https://cloud.githubusercontent.com/assets/22358264/19236431/ac3990a2-8ef7-11e6-9928-fcf1cc1c8694.png)

**Comment by roadscape** [comment]
Duplicate of #437
