### ISSUE TITLE
No Email Received (not in spam, multiple attempts)

### ISSUE THREAD

**Issue by jrolfsen** [steemit/steemit.com#465]
Hi Steemit Dev Team,

I'm trying to sign up for an Steemit account. Once I put in my email and it asks me to to check my email, I do - no luck. I click the button that says resend email - no luck. I've searched all mail with the search term 'steemit', checked my spam, and any other folders multiple times. I've been trying/checking now for the last 4 or so days. Part of me would think I signed up for an count before, but I can't find any emails that even mention steemit.

All help appreciated, thank you,
- Jonathan

**Comment by jcalfee** [comment]
works for me.. I see your .edu email in the database.  I emailed you manually.

**Comment by jrolfsen** [comment]
Weird. The link method worked, but no matter what way I tried it here
before, it wouldn't give me anything. Thank you.

**Comment by valzav** [comment]
I've checked your email status on sendgrid - it's reported as delivered. Probably it was some temporary issue with your email provider.

**Comment by jrolfsen** [comment]
Valentine,

I'm doubtful. It's all through Gmail. Other than my messages with your team
on Github, I still haven't received any Steemit related emails.

Regards,
- Jonathan

**Comment by valzav** [comment]
@jrolfsen I appreciate the information you provided. I'll contact sendgrid and asked them to investigate.

**Comment by jrolfsen** [comment]
Gladly, I'll be open to any other questions you me have.
