### ISSUE TITLE
Raw HTML mode removed -- use cases & missing editor features

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#469]
![image](https://cloud.githubusercontent.com/assets/22358264/19306163/ac2c201a-9074-11e6-85ab-3392e7842676.png)

**Comment by jcalfee** [comment]
https://steemit.com/bravenewcoin/@bravenewcoin/bravenewcoin-bill-gross-says-bitcoin-might-lead-to-an-alternative-to-the-current-financial-system

**Comment by roadscape** [comment]
The HTML switch was disabled because it caused unpredictable behavior. What kind of tweaks do you need to make? We may be able to integrate it into the UI.

Alternatively, markdown mode allows you to use HTML as well.

**Comment by thecryptodrive** [comment]
Hey, well I used to used editor mode to capture the text because the links pasted in nicely instead of having to create the links manually each time, then I used to go into html mode and center images with <center>  </center> and add a footer at the end like this below, so I was using both views. 

If you could have a centering function on the editor would be great, but adding a footer may still be an issue.


<hr>
<html>
<p><img src="https://s25.postimg.org/yan0fg8qn/sig_bravenewcoin_sml.jpg" alt="sig_bravenewcoin_sml" width="230" height="51"/><img src="https://s25.postimg.org/6bsuol73z/sig_twitter.png" alt="sig_twitter" width="40" height="40"/><a href="https://twitter.com/bravenewcoin" target="_blank"> </a><img src="https://s25.postimg.org/f83msixq7/sig_linkedin.png" alt="sig_linkedin" width="40" height="40"/><a href="https://www.linkedin.com/company/brave-new-coin" target="_blank"> </a><img src="https://s25.postimg.org/6r8pvcif3/sig_facebook.png" alt="sig_facebook" width="40" height="40"/><a href="https://www.facebook.com/bravenewcoin" target="_blank"> </a><img src="https://s25.postimg.org/s269zm0jj/sig_reddit.png" alt="sig_reddit" width="40" height="40"/><a href="https://www.reddit.com/r/BraveNewCoin" target="_blank"> </a><img src="https://s25.postimg.org/l1ia6tyrj/sig_steemit.png" alt="sig_steemit" width="40" height="41"/></p>

<p><hr></p>
<p><p><strong>This article can be found on our website on <a href="http://bravenewcoin.com/news/decent-a-torrent-blockchain-presale/">this link</a></strong></p></p>
<p></html>
<hr></p>
<p><html></p>
<p><h3>If you enjoyed this article, remember to <a href="http://www.steemit.com/@bravenewcoin">FOLLOW</a><strong>, REPOST</strong> and <strong>SHARE</strong> our daily content!</h3>
</html></p>

**Comment by thecryptodrive** [comment]
It would be cool if the markdown editor could recognize text links that are pasted in directly, like the editor did, then I'm all sorted. The BNC articles can have as much as 20 links in the text, which is crazy to do the markdown for each time.

![image](https://cloud.githubusercontent.com/assets/22358264/19317035/f1837760-90a3-11e6-9e18-239788495acb.png)

**Comment by roadscape** [comment]
Thanks @thecryptodrive -- I'll use this ticket to track reports of raw HTML use cases, which are all essentially workarounds for shortcomings of the current richtext editor.

Users need to be able to:

 - center images
 - add links to images
 - edit text links
 - save/restore raw post data
 - paste HTML (articles w/ links, footers)

**Comment by thecryptodrive** [comment]
Cool thanks Tim, I'm liking GitHub... where has it been all my life, lol. :)

**Comment by roadscape** [comment]
@thecryptodrive: I was testing the footer you pasted here, but it's quite broken (the links don't work, and some of the images are not linked). Here is the cleaned up version which I'm testing:

<hr />
<p>
  <a href="http://bravenewcoin.com/"><img src="https://s25.postimg.org/yan0fg8qn/sig_bravenewcoin_sml.jpg" /></a>
  <a href="https://twitter.com/bravenewcoin"><img src="https://s25.postimg.org/6bsuol73z/sig_twitter.png" /></a>
  <a href="https://www.linkedin.com/company/brave-new-coin"><img src="https://s25.postimg.org/f83msixq7/sig_linkedin.png" /></a>
  <a href="https://www.facebook.com/bravenewcoin"><img src="https://s25.postimg.org/6r8pvcif3/sig_facebook.png" /></a>
  <a href="https://www.reddit.com/r/BraveNewCoin"><img src="https://s25.postimg.org/s269zm0jj/sig_reddit.png" /></a>
  <a href="https://steemit.com/@bravenewcoin"><img src="https://s25.postimg.org/l1ia6tyrj/sig_steemit.png" /></a>
</p>
<hr />
<p><strong>This article can be found on our website on <a href="http://bravenewcoin.com/news/decent-a-torrent-blockchain-presale/">this link</a></strong></p>
<hr />
<h3>If you enjoyed this article, remember to <a href="http://www.steemit.com/@bravenewcoin">FOLLOW</a>, REPOST and SHARE our daily content!</h3>
```
<hr />
<p>
  <a href="http://bravenewcoin.com/"><img src="https://s25.postimg.org/yan0fg8qn/sig_bravenewcoin_sml.jpg" /></a>
  <a href="https://twitter.com/bravenewcoin"><img src="https://s25.postimg.org/6bsuol73z/sig_twitter.png" /></a>
  <a href="https://www.linkedin.com/company/brave-new-coin"><img src="https://s25.postimg.org/f83msixq7/sig_linkedin.png" /></a>
  <a href="https://www.facebook.com/bravenewcoin"><img src="https://s25.postimg.org/6r8pvcif3/sig_facebook.png" /></a>
  <a href="https://www.reddit.com/r/BraveNewCoin"><img src="https://s25.postimg.org/s269zm0jj/sig_reddit.png" /></a>
  <a href="https://steemit.com/@bravenewcoin"><img src="https://s25.postimg.org/l1ia6tyrj/sig_steemit.png" /></a>
</p>
<hr />
<p><strong>This article can be found on our website on <a href="http://bravenewcoin.com/news/decent-a-torrent-blockchain-presale/">this link</a></strong></p>
<hr />
<h3>If you enjoyed this article, remember to <a href="http://www.steemit.com/@bravenewcoin">FOLLOW</a>, REPOST and SHARE our daily content!</h3>
```

**Comment by thecryptodrive** [comment]
Hey Tim, thanks for the cleaned up code, it has been working all this time maybe wasn't the most elegant. Thanks so much. I can now paste this direct in the markdown mode. 

It would be really great if the markdown editor could recognize text links being pasted into it from other sources, as previously mentioned, that's where my issue is at the moment if one can no longer switch between editor and html.

**Comment by roadscape** [comment]
Our upcoming richtext editor will allow you to paste in HTML, including links and images. I've verified that your footer and sample article paste properly.

**Comment by thecryptodrive** [comment]
That's really great Tim, will the editor also have the ability to center text and images?

**Comment by roadscape** [comment]
All the feedback in this topic has been noted and Raw HTML mode is back for now until we have an editor that doesn't require it.

@thecryptodrive yes, eventually ;)
