### ISSUE TITLE
Embedded images occasionally attach a prefix to the src url

### ISSUE THREAD

**Issue by fluffypony** [steemit/steemit.com#47]
I've not been on Steemit long enough to notice whether this started happening recently or not, but I've personally only observed this occurring in the last 24 hours.

Occasionally an embedded image in a post / comment will appear with a ```https://img0.steemit.com/0x0/``` prefix, as in ```<img src="https://img0.steemit.com/0x0/https://s32.postimg.org/j6plt0d7p/Enlight1_10.jpg">```. Refreshing the page often fixes this.

**Comment by fluffypony** [comment]
To elaborate, this is what the front page looks like if I scroll down a bit:

![front page](https://i.imgur.com/bg41DRe.jpg)

Dev tools confirms that the images are failing because of the prefix:

![prefix fail](https://i.imgur.com/UAqPk9v.jpg)

And this page load has 25 of those fails:

![many fails](https://i.imgur.com/pGFAS41.jpg)

**Comment by roadscape** [comment]
The URL prefixes are intentional, but we've been having some issues with thumbnail processing and have had to bypass the proxy service temporarily. The service is enabled again for now and we are monitoring it closely.

**Comment by fluffypony** [comment]
Ok great - closing the issue, then. Thanks!

**Comment by johanwilliam** [comment]
Technumus is the most informative and knowledge increasing webisite. please follow visit and suppot us.<a href="https://technumus.com/0x0-0x0/">WHAT IS ERROR CODE0X0 0X0 CAUSE OF ERROR CODE AND ITS SOLUTION</a>
