### ISSUE TITLE
Memo option available for Powerup but does not work

### ISSUE THREAD

**Issue by thecryptodrive** [steemit/steemit.com#481]
The power up menu has a memo feature, you can insert text therein but nothing gets sent.

![image](https://cloud.githubusercontent.com/assets/22358264/19365599/cab62448-9193-11e6-8188-9b77ae3b50af.png)

**Comment by thebitcoiner** [comment]
duplicate of #474

**Comment by thecryptodrive** [comment]
ok I will close it
