### ISSUE TITLE
Decline Payout UI updates

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#485]

**Comment by jcalfee** [comment]
![image](https://cloud.githubusercontent.com/assets/204121/19393533/11e7b6c8-9203-11e6-8392-83d964395d56.png)

**Comment by jcalfee** [comment]
![image](https://cloud.githubusercontent.com/assets/204121/19393918/d58ddbec-9204-11e6-8324-bb83a9852b38.png)

**Comment by roadscape** [comment]
Is this necessary? Decline payout is never selected by default, and "Rewards: Decline" is pretty clear in its intent imo

**Comment by jcalfee** [comment]
no changes then
