### ISSUE TITLE
Reblog/Resteem - Unreblog/Unresteem

### ISSUE THREAD

**Issue by KrNel** [steemit/steemit.com#496]
Hello,

Great feature. But we need to be able to unreblog if we want to. One reason is if we made a mistake, or if we change our minds.

Thank you kindly,

Kris Nelson

**Comment by TimCliff** [comment]
If the option to remove a resteem is added, there is a way for users to game the system. A user can resteem, then remove, then resteem again to get the item to appear in the top of their followers newsfeeds again.

I don't know if this is worth coding for though. If a user started doing this regularly, they would risk losing their followers. Maybe that is enough to prevent it from happening.

**Comment by TimCliff** [comment]
An alternative solution would be to just add a confirmation box when the user clicks resteem. It would not allow for 'undo', but it would hopefully eliminate the 'mistake' part of the problem.

**Comment by TimCliff** [comment]
I found this issue, which seems to be for the same request:
https://github.com/steemit/steemit.com/issues/374

**Comment by roadscape** [comment]
Let's use #374 for unresteem discussion. 

Confirmation dialog being worked on in #572.
