### ISSUE TITLE
Internal market order disappeared from interface

### ISSUE THREAD

**Issue by RodrigoSerafim** [steemit/steemit.com#50]
After this last site update the market order that I placed on the internal market disappeared from the interface.
My wallet still shows 0 SD and 0 STEEM so the order was not canceled during the update. However, since the interface does not show it, I can't do it manually to recover my balance.

While its just a minor amount, still worrying that this kind of bug/upgrade issue can happen with ANY amount.

**Comment by RodrigoSerafim** [comment]
Issue is better described as an interface failure. Basically what happens is that despite the interface showing you as logged in, the open orders information regards you as logged out.
After forcing a login directly on the market page (even though the login is already established) causes the interface to refresh correctly.
This is however very deceptive and may lead to wrong conclusions as per my initial issue report.
This seems to be an interface/authentication state issue, not a market backend issue.

**Comment by roadscape** [comment]
Is this still an issue? Parts of the market and login functionality have changed quite a bit since this was filed.
