### ISSUE TITLE
UI inconsistency for permalinks

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#509]
There is an inconsistent UI for posts at a permalink.  When navigating to a post from the frontpage, a modal popover is displayed and the post's permalink is in the location bar.

However, when the post's permalink is loaded directly, it is of course not in a modal but full-page.

I think the latter is the correct behavior, as the modal interaction requires the user to keep state, and breaks expectations for the web (as someone else viewing the same URL that is e.g. copy-and-pasted won't see the same layout).

Let's do away with full-page modals entirely, shall we?  They're okay for specific, tiny actions like "login" et c but posts are the lifeblood of the blockchain and they should always be displayed like a million bucks, front-and-center, on a fantastic layout, not with distracting lists behind them or relegated to a modal popup like an ad or a survey.

**Comment by TimCliff** [comment]
Before they introduced the modal view for posts, I had an annoying time when browsing the "new" and "hot" pages. Every time I got done reading a post, it would go "back" and the position of all the posts would change. I would have to do a lot of scrolling to find my place again to pick up where I left off. With the new modal implementation, after I close a post, the list of articles is right where I left it. I do really like this feature. If you are going to get rid of the modal view, I suggest that the "preserving your place" functionality still be preserved.

**Comment by valzav** [comment]
@sneak, yes there is inconsistency in layout and this really bugs me, but as @TimCliff pointed out the modal solves a lot of issues. I think we can revamp this later as a part of a bigger UI refactoring.

**Comment by sneak** [comment]
@valzav i agree 100%, sounds good
