### ISSUE TITLE
Wallet balance should reflect open market orders

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#51]
https://steemit.com/market/@logicwins/a-bug-in-the-steem-market

> When I put out an order, the dollar value of my steem and steem dollars does not show up in my wallet. The amount of steem dollars or steem used for the order should still be counted in my total, especially for interest calculations.

**Comment by roadscape** [comment]
Related: #260 (conversion requests not reflected in wallet balance)

**Comment by roadscape** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wallet balance needs to reflect conversions in progress and open orders #260, #51](https://trello.com/c/21P3w0dU/111-wallet-balance-needs-to-reflect-conversions-in-progress-and-open-orders-260-51)
