### ISSUE TITLE
permalinks do not reflect entity hierarchy accurately

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#510]
Current article permalinks are

`/<primary-tag>/@<username>/<slug>`.  AFAIK the primary-tag part is redundant, as the username and slug is sufficient to uniquely identify the user (correct me if I'm wrong)?

Consequently, navigating to `/<primary-tag>/@<username>` does not show all of a user's postings under that tag.

Let's establish a clear hierarchy for elements (users, posts, comments, metadata) and construct a consistent URL scheme around it. This is perhaps the last time we'll have the opportunity to do so. :)

**Comment by sneak** [comment]
@steemit/steem-develop-committers feedback requested

**Comment by roadscape** [comment]
Discussion continues in #807
