### ISSUE TITLE
resteemed icon falls out of metadata portion on right-hand-side

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#511]
<img width="985" alt="screen shot 2016-10-20 at 00 03 10" src="https://cloud.githubusercontent.com/assets/408977/19545909/7e7c7b8a-9658-11e6-856f-6f1bd2f6f38d.png">

The little reverse/repeat arrow icon is falling too far left, intruding on the thumbnail part.  The icon and the label text for the icon should be contained in the right-hand side; that is, left-aligned to the same left edge as the the title, subhead, and upvote button.

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [resteemed icon falls out of metadata portion on right-hand-side #511](https://trello.com/c/xW9clwOn/83-resteemed-icon-falls-out-of-metadata-portion-on-right-hand-side-511)
