### ISSUE TITLE
DMCA Claim for Copyright infringement. 

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#525]
I haven't found another place to put this. Can you please follow up please?

Hi there, I am writing on behalf of Constant Content, a content platform that offers unique content to online businesses via a pool of freelance writers. We’ve had a recent situation happen involving one of your Steemit writers named Carlidos. We have found a fair bit of content on your site posted by Carlidos that is identical to content on our site that has not yet been sold. The original authors of this content are very concerned and have reached out to us to bring this to our attention. 

There are 30 instances of copyright infringement, 15 of which are completely stolen content (right down to the title of the article), and 14 where the client bought usage rights to the article from our site, but did not comply with the terms. We have two types of licenses for our customers: full rights, an exclusive license where the customer owns the content and can customize (including removing the author’s byline); the other is usage, a one-time rights license, where the author byline must be attached to the article. In the instances where Carlidos purchased usage rights, he posted the articles with his own byline.

Is there someone at Steemit who could look into this and get back to us ASAP? We can send you more information (such as the articles that appear on our site vs. Steemit) via email - please provide a contact address. If we don’t hear back from you by the end of this week, we will have to take next steps to rectify the situation, such as filing a a DMCA complaint with Google. We’re in the business of protecting people’s content, which is something I’m sure you can relate to. Thank you.

Appreciate you getting back to me. Could you please forward my email to your CEO: creid@constant-content.com. Thank you.

**Comment by iamsmooth** [comment]
I am a community member not a representative of Steemit, however I am aware of the following section of the Terms of Service document (accessible via the hamburger menu on the web site):

https://steemit.com/tos.html

20. Copyright Complaints

Steemit respects the intellectual property of others by not reading infringed content from the Steem blockchain. If you believe that your work has been copied in a way that constitutes copyright infringement, you may notify Steemit’ s Designated Agent by contacting:

contact@steemit.com

Please see 17 U.S.C. §512(c)(3) for the requirements of a proper notification. You should note that if you knowingly misrepresent in your notification that the material or activity is infringing, you may be liable for any damages, including costs and attorneys’ fees, incurred by Steemit or the alleged infringer, as the result of Steemit’s relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing.

**Comment by SteemitFbAdmin** [comment]
I believe they tried contacting without ever receiving a response. Can we make sure the matter is escalated to the person in charge please?

**Comment by nedsteem** [comment]
Renaud, they'll need to follow the DMCA process by emailing contact@steemit.com

Hello,

We take copyright infringement very seriously.  If you believe you have a valid DMCA claim. Please send all of the necessary details to contact@steemit.com and we will look into your claim as quickly as possible.

Thanks
