### ISSUE TITLE
Comment Payout says 47 years ago

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#532]
When I click to view the potential payout on comments that are still active, it says the payout is "47 years ago".

http://i.imgsafe.org/007fec33a6.png

**Comment by roadscape** [comment]
Is there any pattern to this behavior? Do you have a live URL which exhibits it?

**Comment by TimCliff** [comment]
It seems to happen if the comment is within the first 24 hour payout, and has a nonzero payment

Bernie currently has one a few comments down 
https://steemit.com/@berniesanders/comments

**Comment by roadscape** [comment]
Thanks for reporting this, it appears to be a backend API bug. Issue filed: https://github.com/steemit/steem/issues/546
