### ISSUE TITLE
request night mode feature 

### ISSUE THREAD

**Issue by wilmaballsdrop** [steemit/steemit.com#537]
I would like the option to view steemit in "night-mode". Thank you.

**Comment by sneak** [comment]
Good suggestion, but this is probably best accomplished clientside for the foreseeable future.  I'd look into browser extensions that allow you to add arbitrary styles for a given site.  We'll support themes one day, but not any time soon.

**Comment by sneak** [comment]
(Thank you, though, for your suggestion - and please keep them coming.)
