### ISSUE TITLE
Error during commenting while using apostrophes (@logic)

### ISSUE THREAD

**Issue by BitcoinOperatedBoy** [steemit/steemit.com#538]
There is an issue with the apostrophes while commenting under posts. 
After submitting comment they turn into a mess. 
When I edit the comment later and correct it, the error does not seem to repeat.

@logic

![bug](https://cloud.githubusercontent.com/assets/10457447/19752572/4fc6de18-9bf6-11e6-8aa0-685b1cb295c4.jpg)

**Comment by jcalfee** [comment]
duplicate so i'm closing .. thanks BitcoinOperatedBoy gives me an idea, please follow #37 ..

**Comment by jcalfee** [comment]
>When I edit the comment later and correct it, the error does not seem to repeat.

Did you correct it by copying and pasting the same content or did you correct it by some other means?

**Comment by BitcoinOperatedBoy** [comment]
On one occasion I corrected it by deleting errnonous content and writing
again. On the other occasion I copied the whole comment before submitting,
and then pasted it again while editing to correct the error.

**Comment by roadscape** [comment]
Did you get this error immediately upon submitting a new comment, or after editing it?
