### ISSUE TITLE
Steemit Hack - Please get someone to answer email

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#54]
I manage the Facebook page and I know no body is answering email and slack is disabled. This is the only place I have left to bring this message in order to be heard.

From Marcel Hattingh:
"Unfortunately, my account was one of those that were hacked on the 14th of July. I have emailed contact@steemit.com multiple times, without reply. Please advise me, on how I can recover access to my account en update my security levels. Many thanks 🙂
My account name is @marcelhattingh"

**Comment by marcelhattingh** [comment]
Ahh thank you very much! You can add my username to that list :)
@marcelhattingh

**Comment by jcalfee** [comment]
We are working on re-authentication and account recovery now.. should be today.

**Comment by dev00100000** [comment]
My account was hacked early this morning, will this fix apply to me as well? @dev00100000

**Comment by marcelhattingh** [comment]
Do we have any update on the re-authentication and account recovery?

**Comment by jcalfee** [comment]
Did you recover you account?

**Comment by marcelhattingh** [comment]
My account is fully recovered.

**Comment by dejoel** [comment]
Unfortunately already tried account recovery and account recovery but it has been more 1 month steemit no response at all
