### ISSUE TITLE
Internal linking and Steem apps

### ISSUE THREAD

**Issue by feruzm** [steemit/steemit.com#540]
I wonder if steemit.com can parse internal link in a way that would allow other apps to use better.

If I am linking my own post in my other post, or if I link any post from Steem. Front-end would parse it as follows:
## Currently

`[link](https://steemit.com/steemit/@good-karma/in-search-of-markdown-editor-in-javascript-for-web-apps-steemit-esteem-others)` or `https://steemit.com/steemit/@good-karma/in-search-of-markdown-editor-in-javascript-for-web-apps-steemit-esteem-others` etc.

Which is direct link for the post/comment
## Proposed

`[link](@good-karma/in-search-of-markdown-editor-in-javascript-for-web-apps-steemit-esteem-others)` or `@good-karma/in-search-of-markdown-editor-in-javascript-for-web-apps-steemit-esteem-others`

Which only has `author` and `permlink` of the post/comment. Front-end would create linking internally.

---

This way, any app on top of Steem can get `author` and `permlink` of the post to makeup their own internal linking.

It would also save up some space on blockchain.

Similar requests.... https://github.com/steemit/steemit.com/issues/336

Only question though, 

Would that affect SEO?

**Comment by roadscape** [comment]
Valid URL links on the blockchain are convenient but less portable, especially if other frontends opt to use a schema other than the one provided by `get_state`. Right now it's very easy to parse steemit.com post urls and rewrite as needed.

We already detect `@mentions` and linkify them. The link URL becomes `/@name` and the link text is `@name`. 

The same could be done with posts, but what do we use for link titles? The naked `@name/permlink` would not be ideal. We *could* request the post from the API and use its title as the link text, but this takes formatting control away from the linking author.

One solution could be an app protocol, e.g. `<a href="steem://good-karma/in-search-of-markdown-editor-in-javascript-for-web-apps-steemit-esteem-others">editor comparison</a>`. Frontends can rewrite the URLs to their domain.

**Comment by feruzm** [comment]
Yes, eSteem also has `@mentions` linked to user profile page within app. 

Right now, app extracting links if it is  `steemit.com` links then changing them to internal linking structure when  markdown parsing is called, just like, youtube, imgs, etc. 

by
`@name/permlink` I was referring as code side of it. If user using steemit.com to make a new post, copy paste would still put whole link, but when that post gets submitted to blockchain, steemit.com part is stripped out. When reading, it would add internal linking link, `title` won't be affected.

This way, we would avoid multiple separate linking of the post. I am reading post on steemit.com but post was made with eSteem/Busy, linking would be different. But if it is stripped out and added back during parsing/HTMLReady/Markdown parse, that would solve potential future confusion.

In next couple version, app will give possibility to copy posts link to include to new posts. But if app adds steemit.com in linking process and then again stripping it off for internal usage, that wouldn't be optimal in terms of cross app usage.

**Comment by sneak** [comment]
App protocol links are a poor solution here, I think. We need to firm up a permalink strategy going forward that 3p apps can rely on.

**Comment by roadscape** [comment]
I agree, app protocol links are cumbersome... IMO the best approach will be to use plain relative URLs along with standardized routes.

Just a small change to your proposed `[this is title](user/permlink)` --
I suggest: `[this is title](/user/permlink)`

This way, if you use the standard routes, no rewriting is even needed.

If this makes sense, let's continue the discussion in #807.
