### ISSUE TITLE
Upload Images on Test Server does not work

### ISSUE THREAD

**Issue by bytemaster** [steemit/steemit.com#555]
![image](https://cloud.githubusercontent.com/assets/347290/19822364/05eb752e-9d31-11e6-8a7b-e267900cd9f8.png)

![image](https://cloud.githubusercontent.com/assets/347290/19822398/3e8d3a98-9d31-11e6-99e7-489b62f3da7e.png)

![image](https://cloud.githubusercontent.com/assets/347290/19822471/a20dc6a0-9d31-11e6-8ce5-a9948e22a07b.png)

Uploading image here instead ;)

**Comment by roadscape** [comment]
Tracking the issue in https://github.com/steemit/steemit.com/issues/396
