### ISSUE TITLE
Internal market: bad axis labelling

### ISSUE THREAD

**Issue by hrosspet** [steemit/steemit.com#563]
The labelling of y-axis is wrong. The marks on it read $0, $5000, $10000, $1.50k, whereas they should be $0, $500, $1000, $1.50k

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Internal market: bad axis labelling](https://trello.com/c/rc6WW0KU/100-internal-market-bad-axis-labelling)
