### ISSUE TITLE
Move wallet to the sidebar nav...

### ISSUE THREAD

**Issue by rasheedmoore** [steemit/steemit.com#568]
Just a little UX feedback, might be a little more intuitive if you move wallet to the sidebar nav...

**Comment by TimCliff** [comment]
@sneak / @roadscape - do we want this? Personally, I kind of like having it in my profile, but IDK which way is 'best'. I can make the change if it is wanted.

**Comment by sneak** [comment]
I don't think we want to do this right now.  We're going to be overhauling the conceptual hierarchy of the site eventually, and we will find the best place for the wallet at that time.  For now, we're going to leave it where it is.
