### ISSUE TITLE
Registration Disabled. Please let me know whenever back on. (For Facebook Support)

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#57]
having a reason to explain why it happened would also be helpful

**Comment by jcalfee** [comment]
It is for security upgrades.. Watch here: 
https://steemit.com/@steemitblog
Specifically: https://steemit.com/steemit/@steemitblog/steemit-to-update-password-policy

**Comment by roadscape** [comment]
Registrations have been enabled for a while now, closing
