### ISSUE TITLE
Font display issue in title bar when creating new post

### ISSUE THREAD

**Issue by ausbitbank** [steemit/steemit.com#578]
When creating a new post in Firefox v49 on Debian linux there is a css issue with the title input box. 

I had a fiddle with firefox developer tools and narrowed it down to the padding attribute of the .ReplyEditor__title class in [this css file](https://steemit.com/assets/app-7dcfe781f68f44015249.css)

I created a thread with screenshots of the bug, its fix and other users complaining of the same problem here https://steemit.com/steemit/@ausbitbank/bug-report-font-display-issue-in-title-bar-when-creating-new-post

**Comment by mcifani** [comment]
Thanks, looking into it and will push a fix.

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Firefox bug malforming title post in some versions when posting](https://trello.com/c/95wKrNc6/107-firefox-bug-malforming-title-post-in-some-versions-when-posting)

**Comment by nwright876** [comment]
Sorry for dupe issue

**Comment by roadscape** [comment]
Fixed in https://github.com/steemit/steemit.com/pull/570, pending release

**Comment by mcifani** [comment]
Closing ticket.  Thanks @roadscape
