### ISSUE TITLE
Small css issue, padding obstructing title on submit story

### ISSUE THREAD

**Issue by nwright876** [steemit/steemit.com#579]
<img src="http://i.imgsafe.org/b0ab9c284c.jpg"/>

<img src="http://i.imgsafe.org/b0b2b7b507.jpg"/>

Title in images is the same as the title of this issue.

<img src="http://i.imgsafe.org/b0b9bc00af.jpg"/>

**Comment by nwright876** [comment]
I'm using Firefox and am capable of making the change if needed

**Comment by mcifani** [comment]
Thanks, this is the same as issue from ticket https://github.com/steemit/steemit.com/issues/578.  Closing this and putting it all in one.
