### ISSUE TITLE
Issue Loading Promoted Posts Content

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#586]
Often when viewing the "Promoted" post tab, it shows the first 4-5 posts and then stops. If I try to scroll down to load more content, nothing loads. I have to refresh to see them, and even then it doesn't always work.

Observed in Firefox and Safari, and multiple users have experienced it.

**Comment by roadscape** [comment]
I believe this is caused by the issue reported here: https://github.com/steemit/steem/issues/549

**Comment by jimmco** [comment]
Promote button is also missing and no post can be promoted right now.

**Comment by TimCliff** [comment]
They removed it on purpose due to this glitch, so that people would not spend money promoting when it didn't work 100%.

**Comment by TimCliff** [comment]
It looks like the steemit/steem issue related to this has been closed. Is this back to being a UI issue now?

**Comment by roadscape** [comment]
The feature will be back online within about 24 hours.

**Comment by TimCliff** [comment]
Awesome, thanks for the update!

**Comment by roadscape** [comment]
Restored earlier this week.
