### ISSUE TITLE
Recovery Fail - Help out my friend @bobdownlov

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#59]
Okay this is happening to a very patient guy who is trying to recover his account @bobdownlov 
He will be following this issue, so please let us know what is going on here.

When he tries to recover, this is what appears in red:

> Error: 10 assert_exception: Assert Exception found: Recent authority not found in authority history {} th_a steem_evaluator.cpp:1417 do_apply {} th_a evaluator.cpp:18 start_evaluate {} th_a database.cpp:2815 apply_operation {"op":["recover_account",{"account_to_recover":"bobdownlov","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8Maxwi6jq6ubGYPukjCz7bBE5hq3eukNs1csfQi9c4s9X98shU",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6jXUYtfA28W7nAcZy6YzTVPNTX473nCcpYduw2ZEYdPn3AXhf1",1]]},"extensions":[]}]} th_a database.cpp:2795 _apply_transaction {"trx":{"ref_block_num":2053,"ref_block_prefix":1221503928,"expiration":"2016-07-19T23:46:09","operations":[["recover_account",{"account_to_recover":"bobdownlov","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8Maxwi6jq6ubGYPukjCz7bBE5hq3eukNs1csfQi9c4s9X98shU",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6jXUYtfA28W7nAcZy6YzTVPNTX473nCcpYduw2ZEYdPn3AXhf1",1]]},"extensions":[]}]],"extensions":[],"signatures":["1f7058325dec5e2eb2fe6943a04b601852ea783031592cfb385e6e747597706dde0836f17f98fe57f4996e049d0677cb97baeee762479fc3f8efe1377a49956c35","2075e0cb7e86799e2f73d8d7ac26423a41abcc05c92f4710f263bf2071bfeb40a45c6d861dcd48444269f4bd23a85421758714f88e672f34773ac346e100087fe1"]}} th_a database.cpp:2799 _apply_transaction {"trx":{"ref_block_num":2053,"ref_block_prefix":1221503928,"expiration":"2016-07-19T23:46:09","operations":[["recover_account",{"account_to_recover":"bobdownlov","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8Maxwi6jq6ubGYPukjCz7bBE5hq3eukNs1csfQi9c4s9X98shU",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6jXUYtfA28W7nAcZy6YzTVPNTX473nCcpYduw2ZEYdPn3AXhf1",1]]},"extensions":[]}]],"extensions":[],"signatures":["1f7058325dec5e2eb2fe6943a04b601852ea783031592cfb385e6e747597706dde0836f17f98fe57f4996e049d0677cb97baeee762479fc3f8efe1377a49956c35","2075e0cb7e86799e2f73d8d7ac26423a41abcc05c92f4710f263bf2071bfeb40a45c6d861dcd48444269f4bd23a85421758714f88e672f34773ac346e100087fe1"]}} th_a database.cpp:658 push_transaction digest 1d1404f8dba44f3268f3ce822c767b103512567cd75e38ee643c1dbb6066aa2d transaction 0508b8abce48c1bb8e5701190a626f62646f776e6c6f7601000000000103c89d623a552dedf03f473486812db4f8f6e27f11913e737c88a0f91f0676c7e4010001000000000102f30a27ce820ee04a6f8ee3954af6a9df312bccedff46e6a7fabfae0504aa6c5401000000021f7058325dec5e2eb2fe6943a04b601852ea783031592cfb385e6e747597706dde0836f17f98fe57f4996e049d0677cb97baeee762479fc3f8efe1377a49956c352075e0cb7e86799e2f73d8d7ac26423a41abcc05c92f4710f263bf2071bfeb40a45c6d861dcd48444269f4bd23a85421758714f88e672f34773ac346e100087fe1 {"ref_block_num":2053,"ref_block_prefix":1221503928,"expiration":"2016-07-19T23:46:09","operations":[["recover_account",{"account_to_recover":"bobdownlov","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM8Maxwi6jq6ubGYPukjCz7bBE5hq3eukNs1csfQi9c4s9X98shU",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6jXUYtfA28W7nAcZy6YzTVPNTX473nCcpYduw2ZEYdPn3AXhf1",1]]},"extensions":[]}]],"extensions":[],"signatures":["1f7058325dec5e2eb2fe6943a04b601852ea783031592cfb385e6e747597706dde0836f17f98fe57f4996e049d0677cb97baeee762479fc3f8efe1377a49956c35","2075e0cb7e86799e2f73d8d7ac26423a41abcc05c92f4710f263bf2071bfeb40a45c6d861dcd48444269f4bd23a85421758714f88e672f34773ac346e1

**Comment by SteemitFbAdmin** [comment]
Same thing for my own account:

Error: 10 assert_exception: Assert Exception request != recovery_request_idx.end(): {} th_a steem_evaluator.cpp:1403 do_apply {} th_a evaluator.cpp:18 start_evaluate {} th_a database.cpp:2815 apply_operation {"op":["recover_account",{"account_to_recover":"cryptoctopus","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6qdQNpazcEh9Wvp3UL6uUSBRwRxxSv39NHjvGoC8SSEgfnmcCf",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5YKWerxejUR3n1WDgyeYCNSXdXTJ2z1AktRN191ghQUnKZyf1X",1]]},"extensions":[]}]} th_a database.cpp:2795 _apply_transaction {"trx":{"ref_block_num":30067,"ref_block_prefix":2902951252,"expiration":"2016-07-20T23:14:42","operations":[["recover_account",{"account_to_recover":"cryptoctopus","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6qdQNpazcEh9Wvp3UL6uUSBRwRxxSv39NHjvGoC8SSEgfnmcCf",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5YKWerxejUR3n1WDgyeYCNSXdXTJ2z1AktRN191ghQUnKZyf1X",1]]},"extensions":[]}]],"extensions":[],"signatures":["1f2eb56f6be408c9e9cd98780daa9785f90972c29bc59f4dd2baa8bb950d49fc807415a175a0bb138d1c86c6cf8807e4de6e59e053b58e4be270cf2c1d3a4e40f6","206b1a28d2cdd2864631b256e871dd43f470a7a9abf46ee0848f7615b251c0f5637bd06f0a60623310304e8338b1185c7c08fbdc9dd61b9e0994477c1686166913"]}} th_a database.cpp:2799 _apply_transaction {"trx":{"ref_block_num":30067,"ref_block_prefix":2902951252,"expiration":"2016-07-20T23:14:42","operations":[["recover_account",{"account_to_recover":"cryptoctopus","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6qdQNpazcEh9Wvp3UL6uUSBRwRxxSv39NHjvGoC8SSEgfnmcCf",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5YKWerxejUR3n1WDgyeYCNSXdXTJ2z1AktRN191ghQUnKZyf1X",1]]},"extensions":[]}]],"extensions":[],"signatures":["1f2eb56f6be408c9e9cd98780daa9785f90972c29bc59f4dd2baa8bb950d49fc807415a175a0bb138d1c86c6cf8807e4de6e59e053b58e4be270cf2c1d3a4e40f6","206b1a28d2cdd2864631b256e871dd43f470a7a9abf46ee0848f7615b251c0f5637bd06f0a60623310304e8338b1185c7c08fbdc9dd61b9e0994477c1686166913"]}} th_a database.cpp:658 push_transaction digest 7ee12b11c42657b59043c1b4333da28423122d4fc0e45b62732b740693b9e415 transaction 7375548507ade205905701190c63727970746f63746f7075730100000000010300e53e18ab83edabfaf36ad9098bf5311352e673fef9b890eee67dd75398d8b301000100000000010255e5fb36133aa85c3b733bc927616abb7e1fa1ebb6ca1b9600ead3af81c044af01000000021f2eb56f6be408c9e9cd98780daa9785f90972c29bc59f4dd2baa8bb950d49fc807415a175a0bb138d1c86c6cf8807e4de6e59e053b58e4be270cf2c1d3a4e40f6206b1a28d2cdd2864631b256e871dd43f470a7a9abf46ee0848f7615b251c0f5637bd06f0a60623310304e8338b1185c7c08fbdc9dd61b9e0994477c1686166913 {"ref_block_num":30067,"ref_block_prefix":2902951252,"expiration":"2016-07-20T23:14:42","operations":[["recover_account",{"account_to_recover":"cryptoctopus","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6qdQNpazcEh9Wvp3UL6uUSBRwRxxSv39NHjvGoC8SSEgfnmcCf",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5YKWerxejUR3n1WDgyeYCNSXdXTJ2z1AktRN191ghQUnKZyf1X",1]]},"extensions":[]}]],"extensions":[],"signatures":["1f2eb56f6be408c9e9cd98780daa9785f90972c29bc59f4dd2baa8bb950d49fc807415a175a0bb138d1c86c6cf8807e4de6e59e053b58e4be270cf2c1d3a4e40f6","206b1a28d2cdd2864631b256e871dd43f470a7a9abf46ee0848f7615b251c0f5637bd06f0a60623310304e8338b1185c7c08fbdc9dd61b9e0994477c1686166913"]}

**Comment by jcalfee** [comment]
There have been updates .. can you please try again and let me know.

**Comment by BobDownlove** [comment]
It went for longer this time, then presented me with a Json error. (had screenshot but lost it before photoshop opened) then I retried to process to get this:


Recover account
ACCOUNT NAME
bobdownlov
OLD PASSWORD
••••••••••••••••••••
NEW PASSWORD
••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
CONFIRM PASSWORD
••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Error: 10 assert_exception: Assert Exception found: Recent authority not found in authority history {} th_a steem_evaluator.cpp:1417 do_apply {} th_a evaluator.cpp:18 start_evaluate {} th_a database.cpp:2815 apply_operation {"op":["recover_account",{"account_to_recover":"bobdownlov","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72agG8FEC84qAs57pF8jHYAXRg4T1CskUz7zQiq1b33upwV9mg",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5dFSz3Ehw4n6nBHNL67sTM8zTDYeDfj7m2WznTNNyRyj7fkkq8",1]]},"extensions":[]}]} th_a database.cpp:2795 _apply_transaction {"trx":{"ref_block_num":12559,"ref_block_prefix":3195412771,"expiration":"2016-07-22T15:46:36","operations":[["recover_account",{"account_to_recover":"bobdownlov","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72agG8FEC84qAs57pF8jHYAXRg4T1CskUz7zQiq1b33upwV9mg",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5dFSz3Ehw4n6nBHNL67sTM8zTDYeDfj7m2WznTNNyRyj7fkkq8",1]]},"extensions":[]}]],"extensions":[],"signatures":["1f26be0bc8f9cf405db348eafef4670cd839fdf555db88c375e1889c1a007f07691236a2f286988f7fc92472d1aa9afdd84af0b8a3a8052f12bc2b2341a7bd043b","1f4d7e3788ae1ba4097d33349fa3140000b13083467812d2def210f4a2a889b2ec7f415ccc2bc959bea2fac65f0bbeaf951200d1d1c732eb12975b95a0c843a8d3"]}} th_a database.cpp:2799 _apply_transaction {"trx":{"ref_block_num":12559,"ref_block_prefix":3195412771,"expiration":"2016-07-22T15:46:36","operations":[["recover_account",{"account_to_recover":"bobdownlov","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72agG8FEC84qAs57pF8jHYAXRg4T1CskUz7zQiq1b33upwV9mg",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5dFSz3Ehw4n6nBHNL67sTM8zTDYeDfj7m2WznTNNyRyj7fkkq8",1]]},"extensions":[]}]],"extensions":[],"signatures":["1f26be0bc8f9cf405db348eafef4670cd839fdf555db88c375e1889c1a007f07691236a2f286988f7fc92472d1aa9afdd84af0b8a3a8052f12bc2b2341a7bd043b","1f4d7e3788ae1ba4097d33349fa3140000b13083467812d2def210f4a2a889b2ec7f415ccc2bc959bea2fac65f0bbeaf951200d1d1c732eb12975b95a0c843a8d3"]}} th_a database.cpp:658 push_transaction digest 4257c46285e16acd8ddb2c524582a26d8b94b274aa193bd7aaae784feb89f724 transaction 0f31232176bedc3f925701190a626f62646f776e6c6f760100000000010319c3fe5f34f3318d2c51f3f111edc689d2f4b06121a08e1bebf3e175834791840100010000000001026117a7d5eab66ca403aef5fb54c0619f9909e23654bd52f61ded156cc03061b201000000021f26be0bc8f9cf405db348eafef4670cd839fdf555db88c375e1889c1a007f07691236a2f286988f7fc92472d1aa9afdd84af0b8a3a8052f12bc2b2341a7bd043b1f4d7e3788ae1ba4097d33349fa3140000b13083467812d2def210f4a2a889b2ec7f415ccc2bc959bea2fac65f0bbeaf951200d1d1c732eb12975b95a0c843a8d3 {"ref_block_num":12559,"ref_block_prefix":3195412771,"expiration":"2016-07-22T15:46:36","operations":[["recover_account",{"account_to_recover":"bobdownlov","new_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72agG8FEC84qAs57pF8jHYAXRg4T1CskUz7zQiq1b33upwV9mg",1]]},"recent_owner_authority":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM5dFSz3Ehw4n6nBHNL67sTM8zTDYeDfj7m2WznTNNyRyj7fkkq8",1]]},"extensions":[]}]],"extensions":[],"signatures":["1f26be0bc8f9cf405db348eafef4670cd839fdf555db88c375e1889c1a007f07691236a2f286988f7fc92472d1aa9afdd84af0b8a3a8052f12bc2b2341a7bd043b","1f4d7e3788ae1ba4097d33349fa3140000b13083467812d2def210f4a2a889b2ec7f415ccc2bc959bea2fac65f0bbeaf951200d1d1c732eb12975b95a0c843a8d3"]}

**Comment by BobDownlove** [comment]
kilobit password overkill?

**Comment by SteemitFbAdmin** [comment]
also, for me, there is no longer a button to log into my owners key. I've tried just entering through username/owner but none of my passwords are accepted. Could this be connected?

**Comment by BobDownlove** [comment]
Something weird about it, that's for sure.
I'm happy to wait and work around, do whatever is needed etc to get this happening.
Seeing too much money pass me by, just tryin to recover a $100 loss...
Like, seriously dudes, thats not even half an upvote from one of the big boys...
A few hits from a few good guys and it wont even matter anymore, ja?

Wouldn't it be easier, if I just started a new account with fully advised security options?
A few votes on my into post and we'll all be forgetting about this in our sleep...
As long as we do the same for Mr (or Ms sorry) Awesome Facebook Rep here, They've been doing a great job keeping me up to date as well as liaising here with you to fix what is no doubt a clusterfuck of issues...

I'm cool to do whatever, but to be brutally honest its fucking hurting me seeing all these mad bucks gettin throw around like it's xmas and I've got a genuine story that needs to be told from the soul, and the situation of life I've found myself in because of said story is one to leave much more to be desired... Anyone from Steemit is welcome to add me on facebook: Bob Downlove, or just email me at: justbobdownlove@gmail.com

Look forward to working with you.
Bob.

**Comment by mvandeberg** [comment]
The owner history for the account only contains key "STM7FqL6ikYZDyg9TiFDTCrk8m3PQqxHxphVHGP4QpQPiLLmNukqK" and the transaction contains key "STM5dFSz3Ehw4n6nBHNL67sTM8zTDYeDfj7m2WznTNNyRyj7fkkq8", so it should be failing in the blockchain.

**Comment by BobDownlove** [comment]
What can we do about this? I changed my password as soon as I heard that we
should do so but apparently that didn't register, then as soon as money
came in it got changed on me.

IT'S been a long time now and I've lost a lot of time there that I could
have been making money. It's rather disheartening to be honest...

**Comment by mvandeberg** [comment]
Can you try recovery again? I know the web tool has been updated since the issue was first posted. I can confirm the account recovery requests are being created, but are not completing because of the incorrect owner history. If it fails again with this message, please post it here, otherwise email contact@steemit.com about for further assistance.

**Comment by BobDownlove** [comment]
I think we've done it!

> _Congratulations! Your account has been recovered. Please login using your new password._

**Comment by BobDownlove** [comment]
Okay so it's logging in.
Do I need to change all my passwords/use keys?
Should I be able to see my Active/Owner keys?

**Comment by BobDownlove** [comment]
Okay so I think I've only reset my posting key.
Still wont let me use Active features, just testing.

**Comment by jcalfee** [comment]
Ned says he took care of your 100 SBD..  thanks..
