### ISSUE TITLE
False alarm feed notifications

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#592]
The new notifications are awesome!! I noticed one small glitch though. Twice now I have been browsing the site and got a new "feed" notification. I checked my feed and there weren't any new posts.

**Comment by TimCliff** [comment]
Hi @valzav - just FYI, I am still experiencing this issue fairly frequently.

**Comment by roadscape** [comment]
This may be due to edited posts.

**Comment by roadscape** [comment]
Tracking this issue in #666
