### ISSUE TITLE
Re-clicking on the link to the current page should refresh

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#593]
If I am on my feed page and I get a notification for a new feed event, my default reaction as a user is to click on the "feed" link to see the update. Since I am already on the page, nothing happens, so I have to manually refresh the page to get the update.

**Comment by roadscape** [comment]
Observation: we already do this, except for when the link that is clicked is the same URL as the original server request. So if you load your Blog page in a new tab, you can click the 'Feed' button and it will always pull fresh state. But if you load your Feed page in a new tab, it will never pull fresh state.

**Comment by TimCliff** [comment]
It sounds like it is by design, but as a user - if I see that I have an update, I want to click on the update to see what it is. If I am browsing my feed and the notifications say my feed has updates, what is the expectation for the user to do?

Currently I either hit the refresh button or go to my blog and then back to feed. Neither of these seem ideal though.

**Comment by roadscape** [comment]
@TimCliff I left that note to document what I consider inconsistent behavior :) it does indeed sound like a bug and it needs to be addressed one way or the other

**Comment by roadscape** [comment]
Cross-posting from PR #859 for reference:

> Old logic: do not refetch page when the path is the same as server_location
> 
> This creates inconsistent UX:
> 
>  - If you load your feed page from the server, you can never "refresh" it by clicking it in the menu
>  - If you load your blog page but then go to your feed, you can refresh your feed via menu
>
> As far as I can tell, this logic is only supposed to prevent immediate refetching on initial load, so I've corrected it. Link/navigation behavior is now much more consistent.
> 
> Ref: #593, #516
>
