### ISSUE TITLE
Creation fee is variable, not taken into account in some messages

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steemit.com#594]
Creation fee is variable, not taken into account in some messages
like in:
`components/pages/CreateAccount.jsx`
message shows:
```<p>In order to prevent abuse (each registered account costs 3 STEEM) Steemit can only register one account per verified user.</p>```
As for now, registration fee is `30 STEEM`, moreover, currently Steemit pays `50 STEEM` to new account, so that's the real cost of an account.

**Comment by pfunks** [comment]
A similar issue, on wallet pages, the APR is stated as 10% -- "Tokens worth about $1.00 of STEEM, currently collecting 10% APR." -- when it is currently 15%. `"sbd_interest_rate": 1500`

**Comment by mcifani** [comment]
Thanks @pfunks, I have a separate ticket for this issue: https://github.com/steemit/steemit.com/issues/597

**Comment by mcifani** [comment]
Thanks Gandalf.  I do agree with the creation fee ever changing.. this will require some logic to be constantly reflective. The message has been simplified now and simplified for new users to understand.

**Comment by roadscape** [comment]
This was resolved with #601
