### ISSUE TITLE
Recovery failed . Password not acceptable, no facebook logging visible either

### ISSUE THREAD

**Issue by aizaz79** [steemit/steemit.com#60]
username : aizaz
Cant login using the same password I used to logon with. Forgot password link says "the ownership of this account not changed". Plus, I remember there was a facebook login somewhere, in fact I registered using it, cant seem to find it anymore.

**Comment by jcalfee** [comment]
It has not been changed: ```
 "name": "aizaz",
  "last_owner_update": "1970-01-01T00:00:00",
````
see https://steemd.com/@aizaz

**Comment by jcalfee** [comment]
It has to be your login...

Your password is your private key. Steemit does not keep those for its users protection. Private keys are designed to be kept private. I'm sorry we can't help you. You have to find your password or start over. The best we can do is help you get another account.

We have a recovery option but that only works for recent password changes or compromised accounts. To confirm your account owner was never changed (last owner updated is 1970 - that means never).

When account registration opens up again try to create another account. Make sure to copy and backup your new password. If you can't create the account please let us know.

**Comment by aizaz79** [comment]
does it have any sort of geoIP location or something? Maybe thats why Its not letting me in? The password was backed up as a screenshot right there and then so im 101% sure its the same. Cant facebook login help in some way?

**Comment by jcalfee** [comment]
Facebook login can only help if the password was changed in the last 30 days.  There are no other criteria.  Only the password.  If your re-keying consider that fonts can make an `i` look like an `l` or `1` and a `0` can look like `O`.
