### ISSUE TITLE
Power down error

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/steemit.com#606]
I've tried to power down and have gotten a broadcast error.
I believe I started with 3sp and have exceeded 30sp so I should be eligible to power down?

**Comment by FreeBornAngel** [comment]
The broadcast error was a password error, now it says I need to meet the 10x requirement.

**Comment by FreeBornAngel** [comment]
I'm now at 48sp and still cannot power down.
I get an account created by another account can't power down until 10x is reached.

**Comment by abitmore** [comment]
Duplicate of https://github.com/steemit/steem/issues/562

**Comment by FreeBornAngel** [comment]
So, when can I power down?

**Comment by FreeBornAngel** [comment]
Ok, I got the answer, when I get 10x the current account registration, and not the three steem I got when I signed up.
That is pretty frustrating,....
