### ISSUE TITLE
/@author/permlink redirect route

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#608]
`/@author/permlink` should redirect to `/category/@author/permlink`. 

We can call `get_content author permlink` to get the missing `category` param.

This is useful for cases like linking author/curate reward ops.

**Comment by sneak** [comment]
Or not redirect and just serve the content... the category URLs are unnecessary.

**Comment by sneak** [comment]
kinda dupe of #807

if we do that, then `/author/permalink` will become the authoritative one and all other historical routes will redirect to that...

**Comment by roadscape** [comment]
This issue was resolved w/ #786
