### ISSUE TITLE
typing äüö in answer un-show layer 

### ISSUE THREAD

**Issue by LennStar** [steemit/steemit.com#613]
If you open an article in the layer view (e.g. clicking left on one of the articles in the "new" section, where it open the article but still shows the "new" page in background) then typing öäü in the answer makes the layer disappear. 
If you click again the typed words until this letter are still there, so it seems to be optical problem only, no crash. 

Seems to be an Firefox-Engine only problem. Firefox does it. My browser (that can use several engines) does it in firefox mode but not IE or Chrome mode.

**Comment by svk31** [comment]
Unable to reproduce this, those letters work fine for me in Firefox v50 on Ubuntu. @LennStar is this still an issue for you?

**Comment by LennStar** [comment]
still happens.

**Comment by svk31** [comment]
Which version of Firefox are you using? And which language gives you those letters?

**Comment by LennStar** [comment]
FF 50.0.1
Its German! I thought the German Umlaute are well known ^^
https://steemit.com/bug/@lennstar/bug-test-germans-please-firefox-and-layer-view-ueaeoe
2 feedbacks: One has exactly the same as me, the other said it happens in Safari,too.

**Comment by svk31** [comment]
Ok thanks, I can reproduce it! :)
