### ISSUE TITLE
Split Blog tab into Blog and Resteemed tabs - $50 SBD Bounty Offered (details inside)

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#616]
- In the profile section, there should be a "Blog" and "Resteemed" tab.
- The "Blog" tab should only show the posts that the user authored.
- The "Resteemed" tab should show the posts that the user Resteemed.
- There should be a link to both tabs in the profile menu.
- The order on the profile page and the order in the profile menu should be the same.
- Both tabs should display the correct information when viewing data for the current user, and when browsing other users' profiles.
- The code style and format should match with the existing Steemit.com code-base as much as possible.

This feature request will be tied to a developer bounty which will be posted to Steemit.com

**Comment by TimCliff** [comment]
Here is the link to the bounty:
https://steemit.com/bounty/@timcliff/steemit-com-developer-bounty-split-blog-into-blog-and-resteemed-usd50-sbd-steem-sbd-author-payout-from-this-post

**Comment by thebitcoiner** [comment]
I would like to take this challenge!

**Comment by TimCliff** [comment]
Linking to steem issue: https://github.com/steemit/steem/issues/581

**Comment by TimCliff** [comment]
Closing. Based on the comment from @valzav in the PR: _Rather than splitting Blog into two tabs we decided to add some more filters to Blog page so users would be able to filter posts by author (including blog's owner) and by tag._
