### ISSUE TITLE
I cant log in to steemit.com

### ISSUE THREAD

**Issue by akaninyene-etuk** [steemit/steemit.com#63]
I registered on steemit via facebook, now I cannot find the log in via facebook link.
And I get the message each time I try to log in: We are unable to recover this account, it has not changed ownership recently. 

My account name is akaninyene-etuk. PLEASE HELP

**Comment by jcalfee** [comment]
Your password is your private key.  Steemit does not keep those for its users protection.  Private keys are designed to be kept private.  I'm sorry we can't help you.  You have to find your password or start over.  The best we can do is help you get another account.

We have a recovery option but that only works for recent password changes or compromised accounts.  To confirm your account owner was never changed (last owner updated is 1970 - that means never).

https://steemd.com/@akaninyene-etuk

When account registration opens up again try to create another account.  Make sure to copy and backup your new password.  If you can't create the account please let us know.
