### ISSUE TITLE
Decline Payout Max Posts

### ISSUE THREAD

**Issue by KrNel** [steemit/steemit.com#631]
Not sure if this is an issue or not, but bringing it up.

Do "Declined Payout" posts count towards the total of 4 posts for maximum reward generation? i.e. If I post 4 regular posts, and 1 Decline Payout, or 1 regular, and 5 decline payout, does this diminish the rewards per post as if it was 5 regular posts?

Can "Decline Payout" posts be done infinitely in one day, since there is no payout to worry about?

Thanks. I am wondering if these are issues or not.

**Comment by roadscape** [comment]
Currently, Declined Payout posts do count towards the 'optimal 4 posts'.

I've created a ticket for a backend fix here:
https://github.com/steemit/steem/issues/575
