### ISSUE TITLE
Feature Request: Prefill Transfer Window, callback url after payment complete, and user agnostic 'self' URIs for profile menu.

### ISSUE THREAD

**Issue by roelandp** [steemit/steemit.com#64]
I would love to be able to prefill a transfer window with 'TO, AMOUNT, MEMO', maybe via URL params?

This would fix typos? and make it easier to use the money transfer functionalities for end-users. 
Optionally a 'callback url' would be even greater after a succesfull payment to send a user to the 'paymentsuccesfull.html' page

Additionally it might be smart to turn these user based 'self' URI's to: 
- steemit.com/my/transfers
- steemit.com/my/posts
- steemit.com/my/blog

etc.

Kind regards Roelandp

**Comment by roadscape** [comment]
Discussion continues in #668
