### ISSUE TITLE
mobile: clicking an item in the profile menu (e.g. comments) loads page but does not close menu

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#640]

**Comment by sneak** [comment]
![img_0719](https://cloud.githubusercontent.com/assets/408977/20388760/b6639b8a-acc6-11e6-858e-7e847221440d.PNG)

**Comment by mcifani** [comment]
This is resolved from commit https://github.com/steemit/steemit.com/commit/e451013e4001e3d3643d404888fc123cd52f8f81
