### ISSUE TITLE
middle-clicking (command-clicking) usernames in the list of users who upvoted a post should not close the list

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#641]

**Comment by roadscape** [comment]
@mcifani I had relevant changes stashed away, I pushed them to `641-middle-click-dropdowns` (https://github.com/steemit/steemit.com/commit/bc25170d35c3f1508b630f59b2ddaf5362066382) Would you be willing to review/test that code?

**Comment by mcifani** [comment]
@roadscape Tested and looks good.  Fixes both tickets #641 and #642.  Feel free to do a PR and will get it merged in.
