### ISSUE TITLE
It's impossible to sign up for 99% of Chinese, dan and ned need to fix this ASAP

### ISSUE THREAD

**Issue by gregnie** [steemit/steemit.com#65]
[https://steemit.com/steemit/@laonie/it-s-impossible-to-sign-up-for-99-of-chinese-dan-and-ned-need-to-fix-this-asap](https://steemit.com/steemit/@laonie/it-s-impossible-to-sign-up-for-99-of-chinese-dan-and-ned-need-to-fix-this-asap)

I introduced STEEM to lots of my Chinese friends and strangers, but most of them complained that they cann't sign up.

Let me explain why:

1. 99.99% of Chinese don't have an reddit account, it's impossible to sign up with a newly created reddit account.

2. 99% of Chinese don't have Facebook account, and Facebook was blocked by Chinese Firewall.

But, 99% of Chinese use QQ or Wechat.

You should add a third sign up option, ASAP.

**Comment by asalei** [comment]
: )

**Comment by roadscape** [comment]
Discussion continued in #86
