### ISSUE TITLE
stale comments in state

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#651]
When clicking on a reply to view in context of full discussion it fails if the discussion was cached before the comment was posted. The state should possibly reload when viewing a post.

**Comment by jcalfee** [comment]
How to recreate?

**Comment by roadscape** [comment]
This is how it was described but I'm not able to reproduce it thus far...

1. Write a blog post (or a comment somewhere) with account A (and presumably navigate to your blogs page to ensure the post is loaded into state)
2. In a separate session, reply to the post with account B
3. Wait for the 'Replies' notification for account A, click it to go to Replies tab
4. Click the new reply; it will open in a dialog
5. Click 'View full context' to show the whole post
6. The comment should be present, scrolled-to, and highlighted

**Comment by roadscape** [comment]
Have not been able to recreate this, and have not heard any more reports, closing.
