### ISSUE TITLE
tags must be lowercase

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#654]
- uppercase tags in the input box should cause a validation error
 - when displaying/linking tags in the UI, they should be force-lowercased

**Comment by jcalfee** [comment]
I noticed @User is not linking either.   I think HtmlReady can just be smarter about case ..

If a user types something in the post that is uppercase that is fine but it should convert #Xxx or @Abc to lowercase behind the scenes: when linking and when adding to the Set: usertags and hashtags..

**Comment by jcalfee** [comment]
Upper case categories (tags) in the category line already trigger a validation error.  When typed in the body there is an issue.

**Comment by roadscape** [comment]
This is a good point, I forgot about the #tag detection in the body...

And since usernames are case-sensitive, it may be best to not link "invalid" names (and maybe hashtags too)

**Comment by jcalfee** [comment]
Validation is already implemented I needed to fix when that was displayed.. (prior to the commit I had to tab out of the category screen to see it).

Tags and mentions are linked and saved as lowercase but may be shown and detected in the body with camel case.
