### ISSUE TITLE
do not uppercase usernames in page title

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#655]
Since usernames are case-sensitive (and must be lowercase), we should not capitalize them on page titles

![image](https://cloud.githubusercontent.com/assets/5168676/20403168/c1d89f54-accd-11e6-8696-fe0653fa0a81.png)

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [do not uppercase usernames in page title #655](https://trello.com/c/pQDFBO74/137-do-not-uppercase-usernames-in-page-title-655)
