### ISSUE TITLE
Installing Dev Environment

### ISSUE THREAD

**Issue by CelsoGoya** [steemit/steemit.com#657]
Hi, i'm trying to run a local dev environment and get following error message.

> { SyntaxError: C:/dev/steemit/steemit.com/app/components/modules/BlocktradesDeposit.jsx: Only one default export allowed per module. (26
5:0)
  263 |     url: 'https://api.blocktrades.us/v2/',
  264 | }
> 265 | export default reduxForm(
      | ^
  266 |     {
  267 |         form: 'blocktradesDeposit',
  268 |         fields: ['inputCoin', 'outputCoin', 'amount']

I'm trying to figure out what is happening, thx.

**Comment by jcalfee** [comment]
Try to pull then `git cherry-pick 26ad048` ..

**Comment by CelsoGoya** [comment]
@jcalfee, thank you, first dup solved. I get another and i'm trying to understand class organization of steemit.

> { SyntaxError: C:/dev/steemit/steemit.com/app/components/modules/SignUp.jsx: Only one default export allowed per module. (80:0)
  78 | }
  79 |
> 80 | export default connect(
     | ^
  81 |     state => {
  82 |         return {
  83 |             signup_bonus: state.offchain.get('signup_bonus'),
    at Parser.pp$5.raise (C:\dev\steemit\steemit.com\node_modules\babylon\lib\index.js:4225:13)

**Comment by CelsoGoya** [comment]
@roadscape, this is another problem related to dev environment, dup BlocktradesDeposit is solved, but i get another one at SignUp.jsx.

**Comment by jcalfee** [comment]
try `git cherry-pick 2c957f6`
