### ISSUE TITLE
Handle malformed manually inputed username accounts - still load profile page 

### ISSUE THREAD

**Issue by mcifani** [steemit/steemit.com#663]
As a user if I capitalize one or all letters of a username profile route, I should still be directed to the proper profile page

**Comment by jcalfee** [comment]
Same with the main category.

**Comment by mcifani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Downcase incoming http requests for profile pages & main categories #663](https://trello.com/c/E4rcVqJ9/139-downcase-incoming-http-requests-for-profile-pages-main-categories-663)
