### ISSUE TITLE
Master promoted list is missing

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#664]
Promoted works where there is a category:
![image](https://cloud.githubusercontent.com/assets/204121/20414744/b25de968-acf9-11e6-8a53-3d69f7d343fe.png)

But the full promoted list is `undefined`:
![image](https://cloud.githubusercontent.com/assets/204121/20414737/a2ad9306-acf9-11e6-8371-99eab4f9fca8.png)

**Comment by roadscape** [comment]
I believe this was fixed with https://github.com/steemit/steem/issues/549, but there are still some issues in the way with running latest steem/develop in prod
