### ISSUE TITLE
Inability to power down due to 10x rule needs a better explanation

### ISSUE THREAD

**Issue by valzav** [steemit/steemit.com#665]
![screen shot 2016-11-17 at 1 53 14 pm](https://cloud.githubusercontent.com/assets/28658/20425648/c0fea5fc-ad7b-11e6-9fc1-c31488803837.png)

**Comment by FreeBornAngel** [comment]
Yes, it does,...

**Comment by Transisto** [comment]
Would change it there but not even sure what that's supposed to mean.

https://github.com/steemit/steemit.com/blob/c5bd756da09c62eb1fc9bea085d0684eaff249bc/app/redux/Transaction.js

**Comment by jcalfee** [comment]
Something like this?
>The minimum Steem Power balance before this account can start powering down is N STEEM.

**Comment by Transisto** [comment]
Good but it should also explain the logic behind it.

On Nov 21, 2016 16:03, "James Calfee" <notifications@github.com> wrote:

Something like this?

The minimum Steem Power balance before this account can start powering down
is N STEEM.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/steemit/steemit.com/issues/665#issuecomment-262066348>,
or mute the thread

**Comment by jcalfee** [comment]
>This account requires N STEEM (10x account creation fee) worth of Steem Power before it can be power down.

**Comment by roadscape** [comment]
From 815:

> When attempting to power down an amount which less than 10x of account creation fee, a "Transaction broadcast error" appears which makes the user confused, as it does not explain the real reason of the power down failure.
> 
> There needs to be a proper explanation together with the current minimal amount of SP required for the power down. Ideally, the power down option should be disabled when the requirement is not met, accompanied by an explanation to the user.

**Comment by roadscape** [comment]
We can change the message from

> Account registered by another account requires 10x account creation fee worth of Steem Power before it can be powered down.

to

> Account requires 10x the account creation fee in Steem Power (approximately 300 SP) before it can power down.

Now that SP is more stable the account creation fee should not fluctuate so much. Once https://github.com/steemit/steem/issues/695 is implemented, we will have the exact value in the message.

**Comment by FreeBornAngel** [comment]
What was most frustrating was that I signed on with three steem and was told I could power down with 30, but the way it played out was that I had to have 500 by the time I thought to check.
This change in the arrangement, without notice, was quite disappointing.
