### ISSUE TITLE
html escaping and markdown fails for >

### ISSUE THREAD

**Issue by Pyrolistical** [steemit/steemit.com#67]
I tried to write a tutorial for Javascript, but when I used `>` in preformatted blocks it gets converted to `&amp;`

But since its in a preformatted block, `&amp;` doesn't get converted back to `>` when displayed.

My post: https://steemit.com/javascript/@pyrolistical/how-to-escape-promise-hell

My workaround hack was to replace all the `>` with `＞`

**Comment by jcalfee** [comment]
What is the full text that I can use to recreate the problem?

**Comment by razchiriac** [comment]
Try using &gt; instead of &amp;

**Comment by MacDada** [comment]
```
    foo > bar {
        content: "baz"
    }
    ```

gets rendered as:

    foo &gt; bar {
        content: &quot;baz&quot;
    }

**Comment by jcalfee** [comment]
I see the issue thanks.

**Comment by roadscape** [comment]
Please reopen if this is still a problem.
