### ISSUE TITLE
dev env install issue

### ISSUE THREAD

**Issue by CelsoGoya** [steemit/steemit.com#672]
Found a problem at SignUp.jsx, another dup bug.

> { SyntaxError: C:/dev/steemit/steemit.com/app/components/modules/SignUp.jsx: Only one default export allowed per module. (80:0)
78 | }
79 |
80 | export default connect(
| ^
81 | state => {
82 | return {
83 | signup_bonus: state.offchain.get('signup_bonus'),
at Parser.pp$5.raise (C:\dev\steemit\steemit.com\node_modules\babylon\lib\index.js:4225:13)

Please don't close this issue untill i identify all dev env problems.

**Comment by jcalfee** [comment]
try `git cherry-pick 2c957f6`

**Comment by jcalfee** [comment]
I found two more.. that should be all of them.

Another cherry-pick (until this is merged):
`git cherry-pick d9e8ab4`

**Comment by CelsoGoya** [comment]
Now, i found a different issue. I'm trying to solve it, if you have a quick solution i will appreciate.

> Steemit.com@1.0.0 C:\dev\steemit\steemit.com
`-- react-router-scroll@0.2.1
  +-- UNMET PEER DEPENDENCY history@2.1.2
  | `-- warning@2.1.0
  `-- scroll-behavior@0.7.0

**Comment by CelsoGoya** [comment]
Passed last error! \o/
Last one is:

> [webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/user.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/share.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/chevron-up-circle.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/chevron-down-circle.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/chevron-left.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/chatboxes.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/chatbox.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/facebook.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/twitter.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/linkedin.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/link.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/clock.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/extlink.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/steem.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/halloween.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/ether.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/bitcoin.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/bitshares.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/dropdown-arrow.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/printer.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/search.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/menu.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/voter.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/voters.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/empty.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/flag1.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/flag2.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/reblog.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/photo.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/line.svg
[webpack-isomorphic-tools] [error] asset not found: ./app/assets/icons/video.svg

But if found the files at this folder ...

**Comment by CelsoGoya** [comment]
I update npm an application is running now, but i got another error message, will try to fix it.

**Comment by roadscape** [comment]
@CelsoGoya any more issues?

**Comment by CelsoGoya** [comment]
@roadscape, dev env is working but i get some messages, this weekend i will work on it! :-)

**Comment by roadscape** [comment]
@CelsoGoya everything good?
