### ISSUE TITLE
Potential Payout has a different amount than Past Payouts.

### ISSUE THREAD

**Issue by ShirleyShum** [steemit/steemit.com#675]
One of my mom's steemit post Potential Payout has a different amount than Past Payouts. 
![steemitpayoutbug](https://cloud.githubusercontent.com/assets/4791774/20456810/f956de08-ae4b-11e6-8ba0-7d5a557e12bc.png)

**Comment by roadscape** [comment]
Posts have 2 reward periods -- the first is 24 hours, and the 2nd is 30 days.

So in the first 24 hours of the post, it earned $0.14 and that was paid out. 

After that payout there were more votes, so it will receive some amount of extra rewards in 27 days.
