### ISSUE TITLE
Vimeo embeds not working on Microsoft Edge

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#676]
https://steemit.com/anarchy/@freebornangel/well-alright

User reports that the vimeo embed in the comments of the above page does not load. Microsoft Edge problem is suspected, but the user cannot use a different browser to confirm this.

Microsoft Edge 38.14393.0.0 Microsoft EdgeHTML 14.14393

**Comment by FreeBornAngel** [comment]
It would help if I could get unicornriot.ninja to load as well.

http://www.unicornriot.ninja/?p=10772

**Comment by roadscape** [comment]
`CSP14312: Resource violated directive 'default-src 'self' www.youtube.com staticxx.facebook.com' in Content-Security-Policy: https://player.vimeo.com/video/192097629. Resource will be blocked.`

**Comment by roadscape** [comment]
This issue has been resolved, Vimeo embeds are now working in MS Edge browsers.

**Comment by FreeBornAngel** [comment]
Thank you!!!
