### ISSUE TITLE
Embedded video size issue

### ISSUE THREAD

**Issue by abitmore** [steemit/steemit.com#677]
Please check https://steemit.com/spam/@abit/a-post-for-testing#@acidyo/re-virtualgrowth-re-abit-a-post-for-testing-20161119t204603158z :
![](https://img1.steemit.com/0x0/http://imgur.com/sb9TRMp.jpg)

**Comment by pfunks** [comment]
Related?: Steemit automatically parses out or ignores the size variables when using youtube embed iframe html.
