### ISSUE TITLE
Issue with signing up

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steemit.com#686]
From Mr. Zakari Jaworski:
>I tried to sign up for steemit but i get an error message. then when i tired to sign up through Facebook it wouldn't let me use my cell phone number because it was already in use?

**Comment by jcalfee** [comment]
After the email confirmation link you should see: "Please provide your phone number to continue the registration process" .. 

If your number exists already you should see on that same page in red: "Unable to verify your phone number. Please try a different phone number."

If you saw the Facebook / Reddit login there was some other issue triggering that bug.  That is being fixed soon.  If you can't re-send the SMS message for some other reason please tell us more about that first 'error message' and be sure to let us know when it happens.
