### ISSUE TITLE
steemit.chat fails

### ISSUE THREAD

**Issue by SteemitFbAdmin** [steemit/steemit.com#69]
I tried 5 times to register to steemit.chat 
1- I receive no email confirmation.
2- When I try to login with the email/username and the password, they say : User not found or Wrong Password
3- I tried registering with other email account and I get server error + when I try again it says the email is already use.

**Comment by Riverhead** [comment]
We're working through some SMTP issues. I was hoping they'd be resolved by now but seems not to be. Thanks for reporting.

**Comment by jedau** [comment]
Thought I'd chime in and say that I haven't encountered this, so maybe this issue could be considered as closed?

Also, just a thought, it would be nice if you could link your steemit account to chat. I've seen people have different handles for the two apps, so it should be done by the user if he wants to enable the link though.

**Comment by svk31** [comment]
This seems to have been resolved and isn't really a steemit.com issue anyway.
