### ISSUE TITLE
Feature Request: MathJax integration

### ISSUE THREAD

**Issue by arhag** [steemit/steemit.com#7]
Check it out: https://www.mathjax.org/

I should be able to write math in my post inline like so $a x^2 + b x + c = 0$.

Or I can do it as a display block like this:
$$
x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2 a}
$$

**Comment by arhag** [comment]
Here is another option: https://github.com/Khan/KaTeX

**Comment by jcalfee** [comment]
And another per @theoreticalbts suggestion: https://www.mathjax.org/

**Comment by arhag** [comment]
@jcalfee: :smile: I already suggested mathjax in the OP.

It is the better option in terms of completeness of math rendering. Also it supports MathML and allows on to get the source of the render.

There are two downsides however:

-  Apparently it is much slower than KaTeX to render
- It only works client-side, whereas KaTeX can be used both client-side and server-side, which is nice for pre-rendering pages for search engines or for clients that want to view only without Javascript enabled (or even just as a further speed optimization for regular clients). However, there is a workaround to this, so that MathJax could be used server-side as well: http://pomax.github.io/1451617530567/react-with-latex-without-needing-client-side-mathjax

So there are trade-offs to consider.

**Comment by roadscape** [comment]
Unfortunately it doesn't sound like a simple drop-in:
 - https://github.com/mathjax/MathJax/issues/256
 - https://github.com/gollum/gollum/issues/288
 - https://github.com/github/markup/issues/274  

This sentiment appears to be all too common:

> I know we've supported latex and MathJax in the past, and both caused a lot of headaches. We would be interesting in adding support for something as long as it is not a maintenance burden and doesn't open us up to security vulnerabilities.

and

> latex just has so many feature that it's impossible for us to deploy it securely right now.

----

This could be implemented purely server-side, though it does raise another host of issues. If we render to images, or as "intricate" HTML, each present their own challenges while we are trying to keep our beta paradigms as simple as possible for security and maintenance.

Unless there is a math rendering package that is simple and secure, I think it's too early to invest too deeply into a solution like MathJax. An ideal future solution would be [browser-based](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/math). 

Closing this issue. Feel free to continue using it to track relevant developments, packages, and findings.

**Comment by fizyk20** [comment]
Is this still such a problem? The referenced issues seem to be closed and resolved for years (they have been even at the time of creation of this issue).

I must admit I don't know what the situation with MathJax is security-wise, but I can't really see how it can be a risk, and it would be a really valuable addition to the platform.

**Comment by RoyiAvital** [comment]
This is really needed for modern writing.
Usually including MathJax is pretty easy.

**Comment by ejgallego** [comment]
My humble vote to reopen this feature request; indeed I don't understand what the problem with Mathjax is, it is a purely client-side rendering suite and KaTeX is even lighter.

Without Mathjax many styles of writing are just impossible in steemit.

MathML servers a different purpose [and indeed Mathjax can output to it], in a sense it is comparable to markdown vs html [guess why nobody writes in raw HTML].
