### ISSUE TITLE
Integrate social media - share the post buttons

### ISSUE THREAD

**Issue by JasonMcz** [steemit/steemit.com#70]
ADD SOCIAL SHARE BUTTONS:

WHY?
-Utilize native users activeness on other platform 
-Achieve more referral traffic thus more PVs
-Resulting in higher Alexa Global Ranking
-Influence more users from other platform

**Social Share Button**
http://huacnlee.com/social-share-button/
This is a gem to helper you quick create a share feature in you Rails apps.

Sites list
Facebook
Twitter
Douban
Google+
Weibo
QZone
Google Bookmark
Delicious
Tumblr
Pinterest
Email
LinkedIn
Weichat (Weixin)

**Comment by JasonMcz** [comment]
Just saw the share button -- for facebook/linkedin/twitter --> Issue solved.
Perhaps add support to Wechat (Weixin) as well?

**Comment by roadscape** [comment]
I could not find a Wechat share-URL format, it doesn't seem like they support it. 
Please reopen if this is not the case.
