### ISSUE TITLE
How edits work and why are edits in unicode?

### ISSUE THREAD

**Issue by clayop** [steemit/steemit.com#703]
I am having a hard time to understand editing posts (e.g. https://steemd.com/tx/a4ca01efe13eaeb79caeb02a8d680a4e86d4cfa9).
And also curious why edits are encoded in unicode(?) compared to normal posts.

**Comment by sneak** [comment]
Edits are diff format. They are in ASCII, per the diff file format.

**Comment by sneak** [comment]
Please constrain your issues here to bug reports. This is not a support forum.
