### ISSUE TITLE
Sign Up Error 

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steemit.com#706]
Lady on Facebook received this message while trying to sign up:

`{} th_a generic_index.hpp:63 create {"op"😞"account_create",{"fee":"50.000 STEEM","creator":"steem","new_account_name":"terri","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6oDDpt3B5pkiH92jJCWEuoMTwHdruHNgzELu4J2GCg2VLVtccE",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6ijrCFyMxGzxAb8U7nFzcnxfxXKSgSLLoyFcib69d2qh2BGgJF",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6MhxCuTrDU37roA3fKSCq63PcYSgWA2pj5tq7rPygA45g1LWN3",1]]},"memo_key":"STM5yr7aZHdhYfCgoAae2VAuFukXjBguUPugrF8pPWRfuWMwcgr7U","json_metadata":""}]} th_a database.cpp:3034 _apply_transaction {"trx":{"ref_block_num":26327,"ref_block_prefix":4265916639,"expiration":"2016-11-23T10:45:24","operations":[["account_create",{"fee":"50.000 STEEM","creator":"steem","new_account_name":"terri","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6oDDpt3B5pkiH92jJCWEuoMTwHdruHNgzELu4J2GCg2VLVtccE",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6ijrCFyMxGzxAb8U7nFzcnxfxXKSgSLLoyFcib69d2qh2BGgJF",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6MhxCuTrDU37roA3fKSCq63PcYSgWA2pj5tq7rPygA45g1LWN3",1]]},"memo_key":"STM5yr7aZHdhYfCgoAae2VAuFukXjBguUPugrF8pPWRfuWMwcgr7U","json_metadata":""}]],"extensions":[],"signatures"😞"204b986353ae9f139e5fae138a421619de7d17a374cbdee5708028bd3f63bcc4975a14ff7598c333ba0ce78e2068aa4baa3dce39dfd0368efcc486a0ea22e94518"]}} th_a database.cpp:3038 _apply_transaction {"trx":{"ref_block_num":26327,"ref_block_prefix":4265916639,"expiration":"2016-11-23T10:45:24","operations":[["account_create",{"fee":"50.000 STEEM","creator":"steem","new_account_name":"terri","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6oDDpt3B5pkiH92jJCWEuoMTwHdruHNgzELu4J2GCg2VLVtccE",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6ijrCFyMxGzxAb8U7nFzcnxfxXKSgSLLoyFcib69d2qh2BGgJF",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6MhxCuTrDU37roA3fKSCq63PcYSgWA2pj5tq7rPygA45g1LWN3",1]]},"memo_key":"STM5yr7aZHdhYfCgoAae2VAuFukXjBguUPugrF8pPWRfuWMwcgr7U","json_metadata":""}]],"extensions":[],"signatures"😞"204b986353ae9f139e5fae138a421619de7d17a374cbdee5708028bd3f63bcc4975a14ff7598c333ba0ce78e2068aa4baa3dce39dfd0368efcc486a0ea22e94518"]}} th_a database.cpp:697 push_transaction digest 83ab0c2eaa3be476b512f88bb078db9816cab685de20b7a67a61a13979758ee4 transaction d766dfb844fe44733558010950c300000000000003535445454d000005737465656d05746572726901000000000102fb6854da7675ab0f03b4c65f1cefab1d6b0ca7c83328d61c0fa73062483acaf8010001000000000102f140e180630d4547a1839dea42aaea555ec7237a424a8b69f347a804a989db96010001000000000102c17f0280dc7e680319ca60bd93770dd3394245663d891635b09da963d8d6ba350100028fdca931605dae1ba719e3ed1ce6f6757095e8170b8466c6055c434782d13226000001204b986353ae9f139e5fae138a421619de7d17a374cbdee5708028bd3f63bcc4975a14ff7598c333ba0ce78e2068aa4baa3dce39dfd0368efcc486a0ea22e94518 {"ref_block_num":26327,"ref_block_prefix":4265916639,"expiration":"2016-11-23T10:45:24","operations":[["account_create",{"fee":"50.000 STEEM","creator":"steem","new_account_name":"terri","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6oDDpt3B5pkiH92jJCWEuoMTwHdruHNgzELu4J2GCg2VLVtccE",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6ijrCFyMxGzxAb8U7nFzcnxfxXKSgSLLoyFcib69d2qh2BGgJF",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6MhxCuTrDU37roA3fKSCq63PcYSgWA2pj5tq7rPygA45g1LWN3",1]]},"memo_key":"STM5yr7aZHdhYfCgoAae2VAuFukXjBguUPugrF8pPWRfuWMwcgr7U","json_metadata":""}]],"extensions":[],"signatures"😞"204b986353ae9f139e5fae138a421619de7d1`

**Comment by valzav** [comment]
Sounds like this was temporary. Please reopen if you see it again.
