### ISSUE TITLE
Mobile UI: User Menu Dropdown Pushes Off The Screen.

### ISSUE THREAD

**Issue by AllThingsLiving** [steemit/steemit.com#71]
When you click the user icon, the dropdown menu hangs off the screen and you have to scroll to the right to select an option.

Also, the side menu hangs off the scree, but you cannot scroll over to see everything, it just cuts off the words.

**Comment by razchiriac** [comment]
Hi there,

Could you provide a few details regarding this issue so I could try to reproduce it?

1. What device are you using? _(ex.: iPhone)_
2. What OS and version is the device  running? _(ex.: iOS 9.3.3)_
3. What browser are you using to access steemit.com? _(ex.: Safari)_
4. Does this happen in both portrait and landscape mode?

Cheers!

**Comment by fletchertyler914** [comment]
Hello, 

I posted some images and a description on steemit.com.
Check it out here:
https://steemit.com/steemit/@tyler-fletcher/steemit-mobile-view-is-seriously-hurting

I have an iPhone 6+ running iOS 8.1.2, using any browser I can replicate the issue.

**Comment by roadscape** [comment]
Most of the issues appear to have been resolved, the only problem I saw was that the side menu is too long vertically and cannot be scrolled. So I've tightened up padding on the list.
