### ISSUE TITLE
Open links in new window

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/steemit.com#710]
If links would open in a new window that would simplify my life greatly.

Each time I forget I have to hit the back button, but then I go to post that was open and not my feed.

Irritating.

**Comment by roadscape** [comment]
There is a security issue with opening links in new windows by default.

The best way around this is to hold ⌘ while clicking links on OSX or CTRL on Windows browsers.

**Comment by FreeBornAngel** [comment]
Ok, thank you!! I right click at home and control shift at the library.
