### ISSUE TITLE
Vimeo embeds not working in editor.

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/steemit.com#715]
I am getting it to load in markdown, but I format my posts in the editor.

I like to toggle between the editor and raw html so that I can see the preview, but I'm not getting the link picked up, and it looks like it's not making the thumbnail, either.

When I go in to edit the posts things change that I didn't change, too.

**Comment by jcalfee** [comment]
Please give me an example of what you have in the editor.

**Comment by jcalfee** [comment]
Nevermind.. I see the issue.  Yes, vimeo has not been well supported in the editor mode.  It works once if I put the iframe in html mode then go to the editor.  It works a lot better in markdown.  I'll have to look at that so see if there is something we can do..

**Comment by FreeBornAngel** [comment]
https://steemit.com/help/@freebornangel/vimeo-embed-test-post

Still not picking up the links,....

**Comment by jcalfee** [comment]
I notice that the iframe is gone as soon as the I get the state out of `react-rte-image` component.  This does not look so good in the current editor, because I did not see any way to preserve the iframe in `react-rte-image`..  If you want to look, react-rte-image is a close fork of [react-rte](https://www.npmjs.com/package/react-rte) (same stuff applies).  

I suggest to use markdown instead.  @roadscape do you recall if the slate editor handles this already?

**Comment by roadscape** [comment]
@jcalfee there are 2 issues here:
1. The current Editor does not support `<iframe>`s (and `<center>`, etc), so it will strip them out when serializing to HTML.
2. We do not support auto-embedding Vimeo from URLs

Slate editor can handle case 1 but case 2 would be a good workaround and would be good to have in any case

**Comment by roadscape** [comment]
Btw there is an issue open for Vimeo auto-embeds: #673

**Comment by jcalfee** [comment]
When #673 is released you will be able to embed viemo using URL and it will switch just fine between Raw and Editor.

**Comment by FreeBornAngel** [comment]
https://steemit.com/anarchy/@freebornangel/athens-thanks-the-local-police-for-their-service

If I read that correctly I am waiting for an update?

**Comment by roadscape** [comment]
You can now add a vimeo URL in the editor, and it will auto-embed upon posting. (You can go into Raw HTML mode to see a preview of what it will look like)

**Comment by FreeBornAngel** [comment]
All right!! You guys rock!!
