### ISSUE TITLE
What is the deal with the editor?

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/steemit.com#716]
I mean this is the most important thing to the platform, and it doesn't work?

When I toggle back and forth between raw html and editor things change on their own.

Why do I have to toggle back and forth to get a preview, can't I have a preview post button?

I know markdown was supposed to be learned by everybody that comes on board because some formatting genius thinks it is better, but I just want a simple editor so that I can highlight content and link it.
I really don't need it for more than that, except maybe to underline and italicize.

I don't know why I would want to take the time to learn markdown, and type the extra code, when the editor should do everything I need to do.
I don't see the majority of later adopters doing it, either.

Thank you for putting up with me, I know my tone lacks tact at times, and that ya'll do an incredible amount of work basically for free, but this is a basic feature and indispensable to migrating the masses.

**Comment by FreeBornAngel** [comment]
https://steemit.com/help/@freebornangel/still-trying-to-get-the-embed-codes-to-work

**Comment by sneak** [comment]
Thank you for your feedback.

**Comment by sneak** [comment]
(Also note that this is a dupe of #185 )

**Comment by roadscape** [comment]
@FreeBornAngel: switching between the Editor and Raw HTML mode is known to cause side-effects. Raw HTML is for advanced users and some use it to manually save drafts. The next-generation editor will take care of your concerns.

**Comment by FreeBornAngel** [comment]
Ok, thanks,...
