### ISSUE TITLE
Why do my posts round down?

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/steemit.com#720]
I have a dolphin that votes my posts regularly resulting each time (25+) in a .02 potential payout, but regardless of how many other people vote on the post, roughly 20, at payout time my payout rounds down to 0.0 and the rewards don't show up in the author rewards, or my wallet.
What is the deal with that?

My other question is: Do I get the minnow math added to my account, or does it zero out?

This is very frustrating, I get that my content will likely never be popular, but as long as I am getting the rewards that I do earn from the votes that I do get then I have no real complaint, but if the minnow math isn't being done, I have an issue with that.

The code is greek to me, for now, so I have to ask for clarification.
Thanks for your time,...

**Comment by sneak** [comment]
This is not a support forum, but a place used to track bugs.

Please refer to the steem source code for a full, authoritative explanation of the functioning of the rewards system.

**Comment by FreeBornAngel** [comment]
If I could read the source code I wouldn't have to ask questions, now would I?
I haven't been able to find anyone that can answer the question, or I wouldn't be bothering you at all.
