### ISSUE TITLE
Dropdowns not working on mobile

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#722]
When I am browsing my feed, the dropdown next to "home" that I would use to switch to "new" and "trending" does not work. I click on it, but the menu does not appear.

Also, the dropdown to see which users have voted on a post does not work either.

**Comment by mcifani** [comment]
@valzav By chance did you a push a commit/prod for this?  This now looks resolved.

**Comment by valzav** [comment]
@mcifani I've reverted this commit https://github.com/steemit/steemit.com/commit/bc25170d35c3f1508b630f59b2ddaf5362066382
Let's research this issue tomorrow. I think we should not emulate click events with mousedown.

**Comment by roadscape** [comment]
Proposed fix is PR #726
