### ISSUE TITLE
When doing an action that require higher permision show better explanation

### ISSUE THREAD

**Issue by Transisto** [steemit/steemit.com#724]
When trying to change my User logo I got

SERVER RETURNED ERROR
with
Missing Active Authority  Transisto [DISMISS]

I'm not sure what permission I need...
Personally I think the post key should be enough.

**Comment by roadscape** [comment]
What action were you trying to perform?

**Comment by Transisto** [comment]
> When trying to change my User logo

...

**Comment by roadscape** [comment]
The dialog that pops up currently says:

> This operation requires your Active or Owner key (or use your master password).

An account's json_metadata cannot be updated with a posting key.. this is a blockchain-level requirement. 

Something simpler could be implemented in the future using custom_json ops or offchain storage, either of which would only require a posting key.
