### ISSUE TITLE
Weird Behavior On Site - Password

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steemit.com#725]
>Hello, for the last week I do experience a HUGE PROBLEM with the site. The thing is that whenever I try to enter my password in the middle of the process I get this. (Picture is enclosed). I have tried typing it, have tried copy/paste'ing it. Do not know how to do it differently, because does not matter what I do- it shows the same exact thing. The same had happened for my sister, but somehow she had managed to overcome it, however, I can not.

>It is especially weird because my password does not contain those "forbidden characters/letters"

http://www.steemimg.com/images/2016/11/28/15218759_10205883207559300_819475765_n6f504.png

**Comment by TimCliff** [comment]
I got this too when I tried typing my password in one character at a time, but it disappeared once I had all the characters entered. Is this what is happening for you, or is the error still there after the whole PW is entered?

**Comment by valzav** [comment]
@jcalfee, could you take a look? Probably this message shouldn't be shown unless user click LOGIN button.

**Comment by sgunte** [comment]
@TimCliff  It is still there no matter what I do.

**Comment by TimCliff** [comment]
@sgunte - sorry for asking a 'stupid' question, but are you sure that you have the right password?

Also, which one of your passwords are you using, and what action are you trying to take that is prompting you for the pw?

**Comment by sgunte** [comment]
@TimCliff Yes, I have been using the same from June and have saved it on my iPod Touch and email, in case something happens. The thing, is that my laptop recently broke down, when I IT guys had fixed it- I had to re-enter it again and it just does not work. My sister had to do the same, had experienced same problems, but somehow had managed overcoming those.
 The thing, interesting-one, is that actually when I am about to finish typing it and type character "m" this message just pops-up.

This explanation is hectic and absolutely all-over-the-place. I am sorry, but I just do not know how to explain it in a better way. Do You think I should just give up and give up on the things that I have earned there and just start all over again with new account or keep on searching for the solution?

Thank You

**Comment by TimCliff** [comment]
Is 'm' the last character? Like I mentioned before, it happened to me before when I was typing it in, but went away when I finished typing the last character.

Do you know which pw you are using? (Is it your owner key or posting key?)

I can't recommend whether or not to create a new account, but we are trying to resolve the issue for you.

**Comment by sgunte** [comment]
No, it is not the last-one. Sadly, I do not know which one it is.

**Comment by TimCliff** [comment]
"No, it is not the last-one." Sorry, since I know that I have kind of asked this before - but if you type the remaining letters after the 'm' does it disappear?

"Sadly, I do not know which one it is."
Have you used multiple keys before, or is it just the "main" one you got when you signed up?

One other thing to try is see if it lets you change your password
https://steemit.com/change_password

**Comment by sgunte** [comment]
It does not disappear, moreover, when I start typing remaining letters it just appears immediately. 
I got only one.
This is what I see when I try to change my password:
![image](https://cloud.githubusercontent.com/assets/24229048/20731736/3e4844c0-b694-11e6-9b07-bbef6f5e4c48.png)

**Comment by TimCliff** [comment]
Can you try the "Recover Account" option and see what that does?

**Comment by sgunte** [comment]
To be honest, the first moves that I have done is to check out both of them. This is what I see still.
![image](https://cloud.githubusercontent.com/assets/24229048/20746145/3f9d0eec-b6ed-11e6-9f34-d9d8c6cd065d.png)

**Comment by TimCliff** [comment]
It does look like the password you are using is not being accepted. Unless you have any other keys/passwords to try, I am out of ideas. I'm not sure if anyone else has any suggestions, but starting a new account may be your only option :(

**Comment by jcalfee** [comment]
The warning message you posted in the beginning (in yellow) only starts testing your password after it reaches a certain length.  It is only a warning that something in the password missing or incorrect.  It is not checking the blockchain and it does not block you from trying to login with it.

Also, ignore the "forbidden characters/letters" .. it can be anything in the password.  I will simplify that message too it does tend to make people think they messed up one of those characters.  Something in your password is definitely typed incorrectly though if you see that warning after your done.  When you get it fixed you should print your password using a printer and save it on a USB.  Several copies are fine if you keep them secure.

I'll simplify the message and change to only show if we see a failed login.

**Comment by jcalfee** [comment]
Here is the message now.  It will only show up when you try to login if you typed the password incorrectly:

>This password or private key was entered incorrectly.  There is probably a hand writing or data-entry error.  Hint: A password or private key generated by Steemit will never contain 0 (zero), O (capital o), I (capital i) and l (lower case L) characters.
