### ISSUE TITLE
can't edit post when payout is declined

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#735]
the edit operation attempts to submit comment_options which increase the max accepted payout

**Comment by jcalfee** [comment]
@roadscape not sure I understand enough to help here.  

I did notice we should probably delete this todo. It is complicated for just a little space savings and it is distracting.

TransactionSaga.jsx ln 284: `// TODO Slightly smaller blockchain comments: if body === json_metadata.steem.link  ...`

**Comment by roadscape** [comment]
Well now I'm having trouble reproducing it. 

But presumably the steps were:

1) Submit a post with Payout Declined
2) Try to edit it
3) Receive error that maximum payout cannot be increased

Editing a post hides the Reward select box. So I assumed the problem was that when editing a post, the hidden reward option re-defaults to 50-50 and a max_accepted_payout of $1M, causing the assert error.

**Comment by roadscape** [comment]
Able to reproduce this bug in the specific post/browser combination. It's either Safari or session-specific. Using a different browser on the same machine works.

**Comment by roadscape** [comment]
Can't reproduce in Safari, so it must be session-specific

**Comment by roadscape** [comment]
Got it. Steps to reproduce:

1) Go to "Submit a Story"
2) Select "Power Up 100%" (this setting is now saved in localStorage)
3) Change it to "Decline Payout" (this does not change the saved setting)
4) Submit post
5) Try to edit the post. It will fail.

I suspect this is due to the Edit form silently defaulting to "Default 50% / 50%". 

When editing a post, it should (a) not try to change this value and/or (b) not submit a `comment_options` op at all
