### ISSUE TITLE
Tried to build on Debian Based System but ....

### ISSUE THREAD

**Issue by stephane303** [steemit/steemit.com#76]
But I get the following 
Not compatible with your operating system or architecture: fsevents@1.0.14 (As this is an OSX component)

You'll see some permission denied in the log file, but I tried the command again with sudo, so this can't be the cause.

[npm-debug.zip](https://github.com/steemit/steemit.com/files/389438/npm-debug.zip)

**Comment by Tadasu85** [comment]
Yep I can confirm this bug, can anyone tell me if there is a workaround? Or is this real?
