### ISSUE TITLE
some youtube previews are unavailable

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#761]
https://img.youtube.com/vi/P6JUegmdqus/maxresdefault.jpg

does not work, but 

https://img.youtube.com/vi/P6JUegmdqus/0.jpg

does.

**Comment by FreeBornAngel** [comment]
I've lost thumbnails to embed codes, just a grey play button.

**Comment by roadscape** [comment]
@FreeBornAngel could you pls share a URL exhibiting this behavior?

**Comment by FreeBornAngel** [comment]
Well, it is intermittent now, this link at the bottom was the one I noticed it on, but it seems to be there now.
https://steemit.com/anarchy/@freebornangel/i-have-a-dream
Today it was greyed out but appeared when I refreshed it.

**Comment by FreeBornAngel** [comment]
https://steemit.com/youtube/@skeptic/youtube-sjcks-again-copyright-copywrong
This one has remained grayed out after repeated refreshings.
I'm using edge if that makes any difference.
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

**Comment by FreeBornAngel** [comment]
https://steemit.com/film/@ianstrat/a-tribute-to-kirk-douglas-at-100-years-of-age

**Comment by roadscape** [comment]
Thank you, I see the issue. A fix will be released soon.

**Comment by FreeBornAngel** [comment]
thank you!! you guys are the best!!
