### ISSUE TITLE
votes dropdown truncated in post modal

### ISSUE THREAD

**Issue by roadscape** [steemit/steemit.com#762]
![image](https://cloud.githubusercontent.com/assets/5168676/20856530/1db8a40a-b8df-11e6-83e6-846303baa42a.png)

**Comment by svk31** [comment]
Can we just make the dropdown go above instead of below? Would prevent the extra padding that appears if there are no comments but many votes.

**Comment by roadscape** [comment]
That would work, but a bit unintuitive for a top-down sorted list. Imo it's ideal to keep the placement consistently below.
