### ISSUE TITLE
When i try to view who voted on the post the page won't scroll down far enough.

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/steemit.com#764]
It only happens on posts with no comments.
They stop at four and I can't scroll down more.
It just started today that I know about.

https://steemit.com/help/@freebornangel/vimeo-embed-test-post

That one has zero comments.

**Comment by FreeBornAngel** [comment]
Oh, now it quit,....

**Comment by FreeBornAngel** [comment]
This one too,...
https://steemit.com/anarchy/@freebornangel/the-broken-window-theory-of-freedom

**Comment by TimCliff** [comment]
Is this the same issue?
https://github.com/steemit/steemit.com/issues/762

**Comment by FreeBornAngel** [comment]
yes.
