### ISSUE TITLE
curation rewards itemization under user profile links to author, not curated permalink

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#769]

**Comment by svk31** [comment]
This isn't really a bug, it's a consequence of the backend not supplying the post category in the operation history object which means there's insufficient data to construct a url linking to the post.

We could make article links using `/@account/@post-title` for example and fetch the data at that point, or we could fire `get_content` calls for every article in the curation list but that seems a bit overkill to me.

**Comment by MELCHEZEDEK776** [comment]
Or we could connect people with numbers

**Comment by roadscape** [comment]
https://github.com/steemit/steemit.com/issues/608 provides a solution for this

**Comment by MELCHEZEDEK776** [comment]
#thetruthproject @christoryan.steemit.com
@ballinconscious

LETS USE EACH OTHER FOR #FairTrade and wipe put #Evil once and for all!
