### ISSUE TITLE
3p js lib being loaded

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#770]
https://github.com/steemit/steemit.com/blob/develop/server/server-html.jsx#L53

Do we trust polyfill.io with potentially every single users' keys?  I don't think we do.

**Comment by sneak** [comment]
Please fix this ASAP.

**Comment by svk31** [comment]
I guess the reason it's done like this is because the actual response is dynamic depending on which polyfills you need. For recent versions of Chrome and Firefox nothing is needed for example so the downloaded js is empty.

Do we have an overview of what polyfills are actually needed?

**Comment by valzav** [comment]
@svk31 polyfill is needed for Intl in some older browsers, the reason I used polyfill.io is because I didn't find an easy way to load polyfill before the main application. I'll revisit this soon.

**Comment by sneak** [comment]
Let's just download the complete polyfill script with the per-browser conditionals and commit it to our repo.  No need to load this from 3p - it's a major security risk.
