### ISSUE TITLE
posts with secondary tags do not appear in tag-based lists for those secondary tags

### ISSUE THREAD

**Issue by abitmore** [steemit/steemit.com#784]
Only posts with same primary tag will be shown in https://steemit.com/created/tag-name and etc?

For example, [this post](https://steemit.com/life/@sweetsssj/travel-with-me-my-trip-to-xiamen-and-the-wyndham-hotel) has a #cn tag but it's not shown in https://steemit.com/created/cn.
More info (reporter): https://steemit.com/cn/@smarketing/steemit-tags

**Comment by svk31** [comment]
Related to this? https://github.com/steemit/steem/issues/673

**Comment by roadscape** [comment]
Yes this is purely a backend bug, see https://github.com/steemit/steem/issues/673 for details.
