### ISSUE TITLE
85% drop in amount right at the moment of payout, from approx $1,250 down to $143.

### ISSUE THREAD

**Issue by kentfrost** [steemit/steemit.com#79]
There were no unvotes or downvotes against my post - other users were able to confirm this as well.
Not sure if this expected behavior or not, but I certainly didn't expect it.
I know there is a 25% payment that goes to the curators, then 75% to the author which is then split 50/50 between SBD and SP, but that math doesn't seem be what happened in this case.

I have a picture I took _(to show my wife what the thread was garnering)_ taken at 3:01PM CST.
It showed at that time to be at $1,306.40. 
http://i.imgur.com/Cgky3HU.jpg

The peak was somewhere around nearly $1500 earlier in the afternoon. Then, just before the moment of payout, it was hovering around $1,250, give or take a few dollars. 
At the very second it went to pay out, it DROPPED to $190 according to steemstats.com, and the thread itself still shows $143 now, which is the figure that was used to pay out. 
The SBD payout amount was set to be about $470, then dropped roughly 85%, leaving me with $71.754 at the very moment it went to pay me.

This is the post:
https://steemit.com/tag/@winstonwolfe/seriously-forget-about-the-money 
I know...ironic title.

Can anyone look into this and see if this is accurate, or perhaps a bug? 
If it is accurate then I will accept it. If not, I wanted to bring it to the attention of the developers so this doesn't happen to anyone else.

Thank you for your time!!

**Comment by abitmore** [comment]
Explained in [this post](https://steemit.com/steemit/@winstonwolfe/lesson-learned-i-got-the-payout-i-deserved-get-your-post-perfect-before-posting-do-not-edit-it). Perhaps GUI should show the penalty info.

**Comment by roadscape** [comment]
Closing this issue; #153 and #87 will address these points
