### ISSUE TITLE
feature request: /tags.html/created page is not sortable

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#806]
...it should also probably be at a much better url route

**Comment by roadscape** [comment]
Closing in favor of #116 which covers sorting and paginating tags.

**Comment by roadscape** [comment]
Pagination requires microservice (see #115)

Simple sorting can be implemented in the meantime.

Reopening this and closing #116

**Comment by jcalfee** [comment]
Please make sure to do as much data sorting as possible in the Saga files...

**Comment by roadscape** [comment]
This has been merged in #885, closing
