### ISSUE TITLE
display names with an @ in blockchain aren't fixed for display

### ISSUE THREAD

**Issue by sneak** [steemit/steemit.com#811]
afaict 55832d4ca1f48fbb891cc83196a25fe6fde5f942 only fixes the *input* of display names prefixed with an `@`.  Any such in the blockchain will still get displayed - this fix was applied in the wrong place.

Clientside validation is fine and good but ultimately ineffective.  The correct fix for this is in the display side - if the display name starts with an `@`, just show the username instead and refuse to show the display name.  The security bug is not yet fixed.

**Comment by sneak** [comment]
Wait, I missed this part... it's still missing the leading whitespace check though:

https://github.com/steemit/steemit.com/commit/55832d4ca1f48fbb891cc83196a25fe6fde5f942#diff-7b239fbc2f1dd8386d45537465ef356dR38

**Comment by roadscape** [comment]
- display name no longer allows input starting with `@`
 - any display names already in the blockchain starting with `@` will be ignored
 - leading whitespace check not necessary on that line, as its already been trimmed
