### ISSUE TITLE
Keep editor header visible at the top of the page on scroll

### ISSUE THREAD

**Issue by razchiriac** [steemit/steemit.com#82]
<img width="830" alt="screen shot 2016-07-29 at 2 53 28 am" src="https://cloud.githubusercontent.com/assets/13440073/17240202/d59386b4-5537-11e6-8894-bdd283b2f5a3.png">
 
What? Keep this^ at the top when scrolling past it while writing a post.

Why? Ease of use. Less frustration when styling while writing.

**Comment by jcalfee** [comment]
https://github.com/steemit/steemit.com/issues/42#issuecomment-234559944

**Comment by jcalfee** [comment]
Please subscribe to this ticket:  https://github.com/steemit/steemit.com/issues/185

**Comment by jcalfee** [comment]
This looks a lot easier than trying to keep that one bar at the top.   Just freeze the editor page and let them scroll only the editor content..
https://steemit.com/steem/@bitcoiner/steemit-easyedit-let-s-make-the-editor-great-again

I wonder how many of these we have not even seen.  This post was under the tags: steem steemit editor steemtools steemapps  ...

**Comment by roadscape** [comment]
I've made it work in chrome, still needs testing on mobile and other browsers.. this may be the tricky part.
