### ISSUE TITLE
Followers / Follow Disappeared

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steemit.com#820]
From Facebook

> Hi Steemit.  Most of the people I follow have been deleted, (not by me), and people following me are unfollowing. Could you see if my account has a problem?  Thanks ~ kind regards, @pilgrimtraveler

**Comment by TimCliff** [comment]
Hi @RenaudGagne - they are aware of the issue, and are working on a fix as part of https://github.com/steemit/steemit.com/issues/772

Don't worry - your followers aren't gone , it is just a display issue where they are not showing.

**Comment by roadscape** [comment]
This was fixed in #799 and we'll push the changes soon.
