### ISSUE TITLE
NSFW / Porn - Policies

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steemit.com#826]
Earlier this week I had this post show up in the PUBLIC trending section of Steemit.com

https://steemit.com/porn/@alexanova/qm66i-alexa-nova-owen-gray-pov

Now, I want some clarifications about Steemit.inc policies regarding adult content. I flagged this post because I consider it inappropriate content. I do not advocate to ban that content altogether from the platform since it would be unmanageable as the website scale. 

What I understood from the past is that anything tagged NSFW wouldn't show up on the public section of the website. Why hasn't it work this time around? Did the policy change? 

IF Steemit.inc change the policy in it's code, why doesn't it ask the users to verify or to confirm that they are adults? I'm worried about hte legal issue regarding this too. 

I would also like to know it because I have a GIANT logo of STEEM on my car and I wouldn't want to be promoting or associated with a website that allow that kind of content to make their front page. Everybody knows in my community that I am associated with this website and many under-age people may have joined the platform because they know I am a part of it.  

I would like clarification about what is Steemit Inc stance on the matter ASAP.

**Comment by roadscape** [comment]
No policies have changed recently, but there is currently a bug with how tags are handled in the backend - https://github.com/steemit/steem/issues/673 - it should be resolved soon.

**Comment by sneak** [comment]
> I would also like to know it because I have a GIANT logo of STEEM on my car and I wouldn't want to be promoting or associated with a website that allow that kind of content to make their front page. 

I can clarify that: we will be associated with **all** types of legal content, including adult, nsfw, tasteless, and all manner of disgusting stuff.  If it's legal in the jurisdiction we live and work, we're going to have it on steemit.com.  Prepare yourself. :)

**Comment by RenaudGagne** [comment]
@sneak : I don't have issue having that kind of content on steemit. My issue is that content being on the public front page of steemit. If it is what is was in the past (meaning people had to directly go to the nsfw page in order to see nsfw content then I don't have issue with it. 

Can you confirm exactly what is the policy then...because now I am confuse.

**Comment by sneak** [comment]
@roadscape came up with an insanely great solution to this problem which is already committed and live on the test site.

This is probably how we're going to do it going forward: https://test.steemit.com/@alexanova

Cheers,
-jp

**Comment by TimCliff** [comment]
Awesome!!!

**Comment by RenaudGagne** [comment]
Will it show the same way on the trending page?

**Comment by jcalfee** [comment]
@RenaudGagne yes .. all lists now and in the future get this feature automatically.
