### ISSUE TITLE
Provide human friendly error message at account creation

### ISSUE THREAD

**Issue by tibonova** [steemit/steemit.com#829]
Recently I saw a question in the Steemit.chat at # help. 

>  thanks, who can help me create the account? I get the error after my email and phone have been verified. When I create my username and get my password, I re-enter the password in get a very large error that doesn't let me create account
part of the error says insufficient balance to create account but I don't see any instructions in the FAQ about needing funds first...

I explained to her that she doesn't need to pay anything for subscription. 
[This post](https://steemit.com/error/@soratoasu/does-this-mean-people-can-t-create-any-new-steem-it-accounts-anymore) is (not written by her but) related to the problem. 

These kind of messages are very confusing and new users may loose trust. I think many users won't try again registering if they don't get a clear advice/message to do that (and a few won't in any case after an error as the first experience, but this is another issue, first things first.)

**Comment by roadscape** [comment]
Thanks for the report. The insufficient balance issue is on our end; we have implemented alerts for this condition so it will not be a problem going forward.
