### ISSUE TITLE
/@username/jrhkjehfkjwebr does not 404 like it should

### ISSUE THREAD

**Issue by abitmore** [steemit/steemit.com#844]
e.g. https://steemit.com/@dantheman/transfer
(reported by @dnotestein)

**Comment by roadscape** [comment]
Where did he find that URL? It should be 
https://steemit.com/@dantheman/transfers

**Comment by mcifani** [comment]
More catchall/redirect for non existent endpoints should be helpful in these cases.

**Comment by mcifani** [comment]
https://github.com/steemit/steemit.com/pull/851

**Comment by pfunks** [comment]
Related bug? Trying to access a non-existent user page times out: https://steemit.com/@dan1theman

**Comment by roadscape** [comment]
@pfunks non-existing user timeouts issue is #693

**Comment by mcifani** [comment]
Yep this will also resolve #693 - This is currently being reworked to also handle new short post redirects.

**Comment by roadscape** [comment]
@mcifani looks to me like this is resolved. Could you please confirm?

**Comment by mcifani** [comment]
@roadscape This is now resolved in PR https://github.com/steemit/steemit.com/pull/1011
