### ISSUE TITLE
Post modal does not scroll by using the scroll bar

### ISSUE THREAD

**Issue by tibonova** [steemit/steemit.com#847]
A user in steemit.chat # help, who are using a Macbook, cannot scroll post modal. He can only scroll if he opens a link in a new window or reload the page (modal window disappears.) 

I'm using Linux+Firefox, and for me, mouse wheel scrolling works, but I've also experienced problems with it using the scroll bar. I must drag the bottom of the scroll bar. If I drag at the top of it, the modal window will exit, and in the window that it falls back, all of the posts' texts will be selected.

**Comment by roadscape** [comment]
Which browser are they using?

**Comment by tibonova** [comment]
I've asked him.
>On Chrome right now where the problem arose

**Comment by roadscape** [comment]
This should be resolved soon w/ val's PR
