### ISSUE TITLE
Typing in reply box on post closes post

### ISSUE THREAD

**Issue by lafona** [steemit/steemit.com#848]
When I try to make a comment in a reply box, as soon as I start typing the whole post is closed. I find myself back at the trending or sorted page from where I started. It doesn't seem to happen when I copy/paste something into the box. This happens to me using chrome.

**Comment by roadscape** [comment]
Which OS are you using?

Does this happen if you try the same in an incognito window?

**Comment by svk31** [comment]
Sounds like it could be a similar bug to https://github.com/steemit/steemit.com/issues/613.

Which language keyboard are you using, and does it happen for all letters?

**Comment by lafona** [comment]
I am running Ubuntu 14.04 with google chrome. The issue didn't occur using
incognito mode and seems to have resolved after updating chrome. I have
standard? english keyboard.

**Comment by roadscape** [comment]
Sounds like it was a browser bug, I haven't heard of anything quite like this happening on an English keybd. Let us know if you experience this again.
