### ISSUE TITLE
Nor the title or the body of the post is return by call to the node 

### ISSUE THREAD

**Issue by stephane303** [steemit/steemit.com#85]
It's well described here:
https://steemit.com/steemd/@razem-io/runningy-my-own-steemd-node-why-is-title-and-body-empty-am-i-missing-some-configuration#@artakan/re-razem-io-runningy-my-own-steemd-node-why-is-title-and-body-empty-am-i-missing-some-configuration-20160729t202751858z

What are we missing ?

**Comment by aaroncox** [comment]
It sounds like the steemd server you're connecting to has the `-DLOW_MEMORY_NODE=ON`. If this is a server you've built, recompile without that flag. 

I've also noticed a lot of people using EZSTEEM, which has this flag enabled by default.

**Comment by artakan** [comment]
Yes that was exactly the problem, it's fine now, thanks.

**Comment by omotherhen** [comment]
@aaroncox Does low_memory_node impact anything else that has to do with cli_wallet?

**Comment by svk31** [comment]
It will impact anything related to actual blog content as described above, but in terms of doing transfers and other transactions you're fine to do so with a LO_MEM node.
