### ISSUE TITLE
Typo on wallet page.

### ISSUE THREAD

**Issue by klye-dev** [steemit/steemit.com#856]
Clicking the "Convert to STEEM" menu option on the SBD part of the wallet pops up a modal with a spelling error.

"These STEEM DOLLAR will immediatly become unavailable."

I've underlined it in red in the following image:

http://puu.sh/sQ8Jf/7fcb8e08f8.png

**Comment by sneak** [comment]
good lookin' out. fix committed.  feel free to submit PRs directly for stuff like this in the future - you can use the search bar at the top of the repository to find specific strings.

**Comment by klye-dev** [comment]
Will do sneak. Have a good one sir.
