### ISSUE TITLE
WeChat Signup & Integration

### ISSUE THREAD

**Issue by JasonMcz** [steemit/steemit.com#86]
**There was a post mentioned by users under CN tag. This could drastically increase the amount CN users on the site to drive more traffic and more demand/liquidity for STEEM/SBD.**

https://steemit.com/cn/@xiaohui/stongly-suggest-to-dan-and-ned-that-steemit-support-for-qq-or-wechat-verifieation-steemit-qq

@abitmore

**Comment by faddat** [comment]
https://github.com/node-webot/wechat-oauth

**Comment by valzav** [comment]
Is there any plan how to prevent bots registration?

**Comment by faddat** [comment]
I don't think that wechat accounts are any more likely to be zombies/bots than Facebook accounts.  They're tied to phone numbers, so there's a cost for making them.  So I guess, to answer your question, that I figure we use the same plan to prevent bot registration that is currently used with FB / Reddit:

**Self-interested risk** _with as many safeguards as possible_ (like how we check the reddit reputation when making accounts).

Getting into international markets in big ways (or even in small ways) and outside of the English-Web-Bubble would be monumentally gigantic for STEEM and Steemit.

**Comment by abitmore** [comment]
Perhaps it's better to just make a Chinese fork, like the Russian one.

**Comment by faddat** [comment]
@abitmore 
I have no idea.  These are hard questions.

**Comment by jcalfee** [comment]
TeleSign can send an SMS verification code to China for about $.018 cents each.

**Comment by faddat** [comment]
So there's the less than two cent SMS option.... and so ya know-- there's also the fact that you can't get a Weixin account without using a phone number...

**Comment by TimCliff** [comment]
Is this request needed anymore now that signup validation has been switched from Facebook/Reddit to SMS and image verification?

**Comment by abitmore** [comment]
Afaik CAPTCHA is blocked in China. So we still need a solution.

**Comment by faddat** [comment]
Joy!

Well, who is our CAPTCHA provider?  Is there a telegeographically neutral provider?

**Comment by abitmore** [comment]
See https://github.com/steemit/steemit.com/issues/515

**Comment by faddat** [comment]
Don't think so.

Still might be good to add wechat / qq, however given that we now provide
an easy way for people from China to make accounts, the situation is vastly
improved.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by sneak** [comment]
Working around censorship firewalls is not a design goal at this time. Perhaps in the future.

**Comment by faddat** [comment]
We have been banished from the internet's magic kingdom?

**Comment by faddat** [comment]
You have no idea how entirely I understand these problems :(.

Yup, let's stick to xibaba's favorites only.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421
