### ISSUE TITLE
Better type checking when reading block-chain json_metadata

### ISSUE THREAD

**Issue by jcalfee** [steemit/steemit.com#867]

**Comment by jcalfee** [comment]
related: https://github.com/steemit/steemit.com/commit/14a6fae9e7e87d0ed42b6e772f3c61b915c93aa0

Lessons learned:  All our blockchain parsing code needs to be as robust as public API code so unexpected data will not cause an error to propagate and crash full page load..

**Comment by roadscape** [comment]
Merged in #868
