### ISSUE TITLE
Comments revert to created order, past post payout

### ISSUE THREAD

**Issue by pfunks** [steemit/steemit.com#876]
There is a high value to the curation of comments and therefore their rank or order. This is default behavior on a post long-term on websites such as Reddit. Currently on Steemit, comments lose their curation sorting after the post's first payout, losing the value of those upvotes and downvotes. 

I'd like to see Steemit factor total comment value, both in first and second payouts, to determine where the comments sit in the default "trending" sort order. This would give curation of comments even greater value, especially in the long-term.

**Comment by roadscape** [comment]
two related tasks:
 - "created" sort needs to be renamed to "age" sort
 - functionally, its supposed to be “sort by upvotes” not “sort by votes”

**Comment by pfunks** [comment]
Just found essentially the same issue, posted in July: #62
