### ISSUE TITLE
Curation Rewards Only Shows Last 24 hrs of rewards

### ISSUE THREAD

**Issue by thecryptofiend** [steemit/steemit.com#877]
This was pointed out by @craig-grant in this post towards the end of the video:

https://steemit.com/freedom/@craig-grant/promote-your-steemit-blog-post-to-raise-the-value-of-steem

It seems he doesn't see the correct rewards when he looks at his wallet rewards page.  

I have checked mine and I have the same issue - it only seems to show 24 hrs worth - I have double checked by cross referencing with Steemdb.

You can check my wallet page here: https://steemit.com/@thecryptofiend/curation-rewards
and compare with SteemDB here: https://steemdb.com/@thecryptofiend/curation

(I incorrectly posted this in Steem Issues earlier and have closed that and moved this here)

**Comment by roadscape** [comment]
This is the same issue as #375
