### ISSUE TITLE
Feature: Show a List of APPs or 3rd Parties Given Account Permissions

### ISSUE THREAD

**Issue by finleyexp** [steemit/steemit.com#880]
In the Permissions section, it seems beneficial to add a list of who else is using the account (APPs, etc.). Additionally, adding some way to remove these 3rd party users would be helpful. If this already exists, please let me know how to access the feature. Thank you!

**Comment by TimCliff** [comment]
I don't believe that there is a way to support what you are proposing. 

When you provide your private key to someone or a third party tool, they are able to do whatever the key has authority to do. 

The blockchain will not record _who_ does what with the key, just what action(s) were taken with it. In other words, it has no knowledge of who you shared your key with, and whether it is you or someone else using it.

If your key is comprised, then your only option is to revoke it and reissue yourself a new key.

It is generally not recommended to share your keys with anyone or a third party site.

**Comment by roadscape** [comment]
@TimCliff is correct, though in the future a service like SteemConnect will take care of this.

**Comment by finleyexp** [comment]
@TimCliff @roadscape okay. Thanks for responding. I'm still really freaking new to blockchain. ;)
