### ISSUE TITLE
Cannot edit comment

### ISSUE THREAD

**Issue by anduweb** [steemit/steemit.com#895]
Trying to edit one of my comments does not work. This is for a single comment, other comments, newer or older can be edited without an issue.
Behavior: click Edit, edit box shows up, edited text, clicking the UPDATE POST button does nothing.
Creating GitHub item as requested by @roadscape on the steemitwebsite channel on steemit.chat

Un-editable comment is [this one](https://steemit.com/scam/@mynameisbrian/can-you-imagine-an-usd8-000-000-steem-market-buy-a-conversation-with-an-email-scammer#@anduweb/re-mynameisbrian-can-you-imagine-an-usd8-000-000-steem-market-buy-a-conversation-with-an-email-scammer-20161221t202932085z).

**Comment by roadscape** [comment]
Is the `Update Post` button enabled (i.e. clickable)?

Are you using Chrome? Could you open the console and report if there are any errors which appear? 
You can get there by pressing `Ctrl + Shift + J` on Windows, or `Cmd + Opt + J` on OSX.

**Comment by roadscape** [comment]
@anduweb any update on this?

**Comment by anduweb** [comment]
Apologies on the delay. The behavior is still there.
- the feeling is that the button is clickable (e.g. responds to mouse hover, goes from light blue to dark blue when pressed) but after the first click it stays in the down state and _seems unresponsive_.

You're right, there is an error. In the developer console I get this every time I click the UPDATE POST button.
```
Uncaught TypeError: Cannot create property 'tags' on string '{"tags": ["scam"]}'
    at reply (app.6dc4855….js:14)
    at app.6dc4855….js:14
    at v (app.6dc4855….js:73)
    at u (app.6dc4855….js:73)
    at app.6dc4855….js:73
    at app.6dc4855….js:73
    at Object.r (app.6dc4855….js:8)
    at a (app.6dc4855….js:8)
    at Object.s [as executeDispatchesInOrder] (app.6dc4855….js:8)
    at p (app.6dc4855….js:5)
    at m (app.6dc4855….js:5)
reply @ app.6dc4855….js:14
(anonymous) @ app.6dc4855….js:14
v @ app.6dc4855….js:73
u @ app.6dc4855….js:73
(anonymous) @ app.6dc4855….js:73
(anonymous) @ app.6dc4855….js:73
r @ app.6dc4855….js:8
a @ app.6dc4855….js:8
s @ app.6dc4855….js:8
p @ app.6dc4855….js:5
m @ app.6dc4855….js:5
n @ app.6dc4855….js:11
processEventQueue @ app.6dc4855….js:5
r @ app.6dc4855….js:18
handleTopLevel @ app.6dc4855….js:18
o @ app.6dc4855….js:18
perform @ app.6dc4855….js:6
batchedUpdates @ app.6dc4855….js:13
o @ app.6dc4855….js:4
dispatchEvent @ app.6dc4855….js:18
```
Hope this helps!

**Comment by roadscape** [comment]
Thank you, this helps a lot. Curious -- was this particular comment created through steemit.com or an alt client?

**Comment by anduweb** [comment]
Absolutely, my pleasure @roadscape. It was created through steemit.com as busy's interface needs a bit more work on this side unfortunately. I'm still using busy from time to time for surfing though, as the UI is better that Steemit.com's atm.

There isn't a variable in the meta that mentions the client the comments/posts are submitted to the blockchain is it? Maybe there should be...

**Comment by roadscape** [comment]
Top-level posts are marked with "app/version", but we don't do this for comments. Perhaps we should..

**Comment by roadscape** [comment]
Somehow this comment's JSON metadata was double-encoded:

`"json_metadata": "\"{\\\"tags\\\": [\\\"scam\\\"]}\"",`

Whereas other comments show:

`"json_metadata": "{\"tags\":[\"scam\"]}",`

**Comment by anduweb** [comment]
@roadscape I think you may be right and I'm completely amnesic. I just added a comment on a post from Busy, and the same thing happens, I checked the console and the same error. I don't know why I didn't do that when we were talking last week,. So I did post that comment from Busy a while back and didn't remember. I'll link this github issue on the busy steemit.chat channel so they can reference it too. Thanks a million!
