### ISSUE TITLE
Feature request: adjustable vote weight 

### ISSUE THREAD

**Issue by abitmore** [steemit/steemit.com#91]
If a same request is already here, please mark this issue as duplicate.

>James Calfee:
Adjusting vote weight is the kind of thing that can can easily be done in a pull request.  I'll be happy to vote for someone who does a good job.  As long as it looks good and does not pull in huge libraries I think we can accept it into the code base.  Everyone has had higher priority things so we have not been able to do it.

The one who made it would be rewarded imo.

**Comment by dv8silencer** [comment]
Do you mean something like when someone votes, they have a choice between -100 to 100%?

**Comment by iamsmooth** [comment]
IMO this is an advanced/whale feature and it appears in a GUI at al it should be hidden in a setting, hidden by default, etc. Most users just want to click a button and vote without thinking about picking a weight (thinking much at all) and that is how it should be.

**Comment by aaroncox** [comment]
The above branch on my fork is a concept I threw together for how this could work, would love some feedback. It works pretty well and is hidden by default like @iamsmooth mentioned. The library included is fairly small, I can always work on ripping it down even more if needed.

---

![steemit-vote-weight](https://cloud.githubusercontent.com/assets/677686/17275820/2f72c512-56ca-11e6-99dd-3e320dc4c792.gif)

**Comment by JasonMcz** [comment]
I personally think this is not a necessary feature -- It adds another layer of complexity to it. Currently a lot of bots or if you know how to interact with the interface you can upvote and downvote only with % of your weight, however, I don't see how normal user would absolutely need a feature like that? For example, my friend who just joined the site probably still have no idea how the whole SP, STEEM and SBD system works now the learning curve will become more steep because he needs to understand the voting weight dynamic.

@aaroncox  Nice work on that interface concept!

**Comment by aaroncox** [comment]
Thanks @JasonMcz! 

I do agree, it's not ***necessary***, but I do think it's a nice power user feature. I can imagine situations occur where a user with a lot of SP enjoys a post, but doesn't want to throw their full voting power at the post, so currently they don't vote on it at all. 

With it being hidden by default (only showing the chevron) I personally don't think it adds any complexity or friction to the base user experience. Users can choose whether or not to use it, if they even find it, nothing forces them to participate. 

Stepping back a bit from this specific feature, I'd be interested to know what the consensus is from the development team: do we avoid power-user features on steemit to keep the experience clean **or** do we add power-user features, as long as they're not impacting the base user experience.

**Comment by iamsmooth** [comment]
IMO power user features are great but hiding them is also great and I'm not sure a chevron counts as hiding. In discussion of another feature it was proposed to use a secret keystroke (control-shift-something) as a sort of easter egg to activate the feature. Power users are very comfortable with such things in many UIs.

It is very possible accommodate both power users and the desire to keep the experience clean. Done right there is no need for a trade off.

**Comment by aaroncox** [comment]
Above is a new commit that hides the advanced voting features until S + T + E + M are all pressed at the same time. Pressing this 4 character combination toggles a localStorage value called advancedMode, which is then used to determine whether or not we should show the slider. 

![steemit-vote-weight-toggle](https://cloud.githubusercontent.com/assets/677686/17355222/dec1fdae-5903-11e6-937c-9dd397a98270.gif)

I'm not entirely happy with how I achieved the keybindings, I feel they could be in a more global location instead of being part of the `Voting.jsx` component. If anyone has any guidance about where these bindings to control the advancedMode flag belong, I'd love to hear it.

**Comment by JasonMcz** [comment]
@iamsmooth , that's a good idea. Overall I think this is a good idea especially for whales like you or Bernie, your vote has a lot of weight that can change the where the post is going to be in the next few hours. 

@aaroncox , saw your commit, did you take a look at @ayrton key-handler?
https://github.com/ayrton/react-key-handler

**Comment by aaroncox** [comment]
@JasonMcz I have now :)

I'd have no problem swapping over to something like this, but I was trying to avoid pulling in new libraries (as the original issue posted hinted). There's a lot already hah. More than happy to go that route, but I'd love some confirmation as to whether adding a 2nd external library for this one feature is worth adding a new library. 

I'm still attempting to gauge the philosophy of the core committers using situations like this.

**Comment by Someguy123** [comment]
@aaroncox While I like your typing idea, similar to how Google does their YT easter eggs, it would probably make more sense to have a Settings page under your account.

All it would need would be another tab similar to Blog, Posts, Wallet etc. and a simple tick box `Enable Vote Slider (control how strong your votes are)`

**Comment by aaroncox** [comment]
@Someguy123 With the new changes today to the account page, this should be a lot easier to do than when I started working on this.

Things are moving quick! 👍

**Comment by JasonMcz** [comment]
The new changes look quite nice actually!

**Comment by aaroncox** [comment]
I have a rough draft for a preferences screen implemented, as well as improvements mentioned above for the vote weight slider.

![steemstats-preferences](https://cloud.githubusercontent.com/assets/677686/17503776/6fa40770-5da7-11e6-813e-e885a49a1c94.gif)

I've added a new `Preferences` tab that shows on the wallet page with the same conditional logic as `Password` (if you're the owner). This preferences tab has a single option, but could be used in the future for many more options.

The data storage mechanism for preferences is still localStorage, so it's machine specific, but this could be altered and saved somewhere else for portability. 

The vote weight slider also got a few changes:

- No longer displays as weight, but as a whole number percent. This should be easier for users to understand, as opposed to 0 to 10000.
- Minimum value of 1% (100) has been added. We can alter this number based on whatever is decided with steemit/steem#254.
- The step increment on the slider is now 100, meaning clean percentages.
- A close "button" has been added right next to the displayed percent. This button closes the slider and resets the percentage back to 100%. It's essentially a cancel function.

**Comment by svk31** [comment]
I quite like this and I've been thinking for a time now we need a Preferences tab. I would like to maybe add 'curation mode' to Preferences as well but that's another discussion.

One issue now is that the Profile menu is getting a bit crowded, I will collapse Curation rewards and Author rewards into a dropdown which should help, and we should probably look at organizing the 'Wallet' tab a bit better.

I'm not sure we need the slider to be as fine-grained as 1%, perhaps 5% would be better? Anyway that's something we can tweak as we start to get a feel for using it. We could also let the user set it but perhaps that's overcomplicating things.

**Comment by aaroncox** [comment]
>I'm not sure we need the slider to be as fine-grained as 1%, perhaps 5% would be better? Anyway that's something we can tweak as we start to get a feel for using it. We could also let the user set it but perhaps that's overcomplicating things.

I'm open for whatever step increment, it's easily tweakable with the slider plugin's "step" value. I like the idea of letting the user tweak it as well. Another setting I was considering adding to the "preferences" section was a `default vote weight`. I imagine accounts with larger SP balances could use this feature to specify a low percentage as their default weight reducing the impact they typically have on posts.

> One issue now is that the Profile menu is getting a bit crowded, I will collapse Curation rewards and Author rewards into a dropdown which should help, and we should probably look at organizing the 'Wallet' tab a bit better.

I almost took a stab at completely rebuilding that menu. It was driving me crazy that the wallet menu wasn't aligned on the right part of the screen and the spacing was off. I didn't start on it because I was unsure if anyone else was actively working on it, or if it was anyone's project.

**Comment by svk31** [comment]
That would be a nice setting to have for sure!

I noticed the alignment was off all too, not sure when that happened.

I'm afraid there's no easy way to know what's being worked on at the moment, we'll have to look at making things more structured and perhaps creating a new front-end dev channel somewhere.

**Comment by jcalfee** [comment]
jcalfee [11:53 AM]  
I pushed a branch 91-adjustable-vote-weight .. this has just the "adjustable-vote-weight" without key bindings and preference page.  My thinking is key bindings will be fine if we plan to use them for other stuff; let's leave that for another ticket.

Also did not add the preference page, we might end up cherry-picking that too but let's finish the UI and see if we still need it.

a) there is a layout problem when using vote weight on the main post.  
![image](https://cloud.githubusercontent.com/assets/204121/17525640/a163ea20-5e31-11e6-96bd-bd481a32a252.png)

b) the feature should be hidden for anyone with less than a certain threshold... @roadscape can you recommend a metric and value to use?

c) The down arrow needs to disappear if already voted.

You can reference `https://github.com/steemit/steemit.com/issues/91` in the commit message.

**Comment by aaroncox** [comment]
I'm looking at the CSS issues this morning, I'll see if I can get em cleaned up. It looks like once the responsiveness starts kicking in, it's position gets wacky.

**Comment by valzav** [comment]
Experimental vertical slider, check out my last commit.
![image](https://cloud.githubusercontent.com/assets/28658/17534029/4be17aa8-5e55-11e6-8649-96b3dde3df29.png)
![image](https://cloud.githubusercontent.com/assets/28658/17534036/50643ce6-5e55-11e6-89af-3f9ddf2ef109.png)

**Comment by aaroncox** [comment]
I'm a little torn on the vertical slider for a couple reasons. 

The first and foremost being that it makes it so I no longer have a "quick vote" that only takes a single click. Shouldn't there still be a single click action?

The second part is just that it's vertical. I can't describe exactly why, my initial thoughts are that volume sliders on an audio board go up and down, but for some reason 1-100% scales on a website go left to right. That could just be because I'm used to it being horizontal, and this could be my personal preference.

I do like the moving of the percentage and a more clear CTA of "Vote" that appears in the dropdown though. Those are both big positive changes. It's definitely a more clean design than the absolutely positioned div I was dropping on the page. 

Look forward as to what others think of the variations.

**Comment by valzav** [comment]
This drop down will only be shown to a small fraction of users (to whales and dolphins who can move payout by more than $1 with a single vote). Everybody else will have the same one click experience. Also I think the control should remember its last position so if you don't want to change your voting weight just click bit vote button, so it would be two click for whales and one click for everybody else.

**Comment by valzav** [comment]
If you don't mind I'll continue today working on this control - I want to make it to close when user clicks outside, also for some reason the bottom part (selected) doesn't go blue when I move the slider.

**Comment by aaroncox** [comment]
Feel free to continue, we had slightly different visions of it's interactivity. 

I will say, I'm a little sad that I won't be able to use it, but I understand the priority getting it out for people with much larger weights than myself.

**Comment by roadscape** [comment]
The cutoff for enabling this feature will need to be closer to 100M VESTS because it takes ~200MV to move the payout by $1 (at current feed price of ~2.05).

@aaroncox after we get a basic stable version out, it would be nice to get community help w/ UX improvements.

**Comment by iamsmooth** [comment]
Agree this isn't needed for low SP accounts.

Feedback from people with high SP is still that they'd still want it to be an option, including an option whether to show the slider every time or have a persistent setting of vote power other than 100% without needing multiple clicks to vote. The former could probably be done with some UI (long click for example)

**Comment by abitmore** [comment]
@valzav @roadscape Current GUI doesn't save your opinion when you chose to vote with 100% weight, but it does save when you chose other numbers. It annoys since I vote with 100% most time. Now I need to adjust the weight to 100% every time after ever voted with a lower weight once.

**Comment by abitmore** [comment]
Reported by a nice guy:
>There’s a nice feature that allows you to set your voting % on a whale account, log out and into a minnow account and vote with the same %.
>Minnow cannot adjust without going back into whale account.

**Comment by roadscape** [comment]
- Implemented @iamsmooth's suggestion of aligning the 'Upvote' and 'Confirm Weight' buttons
 - Fixed bug of not saving if you use 100% weight (@abit)
 - Vote weights are now saved per account (@abit)
 - Horizontal layout

![image](https://cloud.githubusercontent.com/assets/5168676/17681294/e2fd0882-6312-11e6-992d-3729bc9f9029.png)

**Comment by roadscape** [comment]
The last change I made was to save separate vote weight for top-level posts vs. comments. I suspect this will encourage more voting on comments.
