### ISSUE TITLE
Links in curation rewards section are broken - missing topic

### ISSUE THREAD

**Issue by hrosspet** [steemit/steemit.com#912]

**Comment by roadscape** [comment]
Short form post URL's (e.g. https://steemit.com/@larkenrose/government-always-a-bad-deal) are currently not working. @mcifani are you still dealing w/ this issue? I believe it was a conflict with the new account page 404 feature

**Comment by mcifani** [comment]
@roadscape Short urls are good try master locally(seems the latest is not pushed to prod).

**Comment by valzav** [comment]
Strange - it works in my development environment with the same ws endpoint as on steemit.com

**Comment by roadscape** [comment]
Seems to have been fixed with latest release + update to 0.16.1
