### ISSUE TITLE
Resteem Button On Feeds For Mobile Devices

### ISSUE THREAD

**Issue by taoteh1221** [steemit/steemit.com#915]
When I curate on my phone it's a lot of extra work to quickly resteem from a post preview in a feed. Currently there is no resteem button on phone-sized screens unless you view the article and scroll down to the bottom.

**Comment by mcifani** [comment]
I agree re-steeming should be as simple from mobile as the desktop experience.  @roadscape @val any issues to remove hiding it on collapsed state? I'll display it otherwise.
