### ISSUE TITLE
where can i find signing_key ?

### ISSUE THREAD

**Issue by zhangmingliang1** [steemit/steemit.com#916]
I wants to supply a service to let somebody sign in ,where can i find signing_key ? what is current register fee , 5 steem ? how do i set following params ?

{
  "db": {
    "username": "root",
    "password": "",
    "database": "steemit_dev",
    "host": "127.0.0.1",
    "dialect": "mysql"
  },
  "session_cookie_key": "stm-dev",
  "session_key": "steemses",
  "server_session_secret": "",
  "grant": {
    "server": {
      "protocol": "http",
      "host": "localhost:3002"
    },
    "facebook": {
      "key": "",
      "secret": "",
      "callback": "/handle_facebook_callback",
      "scope": [
        "email",
        "user_location"
      ]
    },
    "reddit": {
      "key": "",
      "secret": "",
      "callback": "/handle_reddit_callback",
      "custom_params": {"state": "void", "duration": "temporary"},
      "scope": [
        "identity"
      ]
    }
  },
  "helmet": {
  },
  "registrar": {
    "account": "",
    "signing_key": "",
    "fee": "5.000 STEEM"
  },
  "requestAccountRecovery": {
    "signing_key": "5J.....",
    "recovery_account": "steem"
  },
  "ws_connection_client": "wss://node.steem.ws",
  "ws_connection_server": [
    "wss://node.steem.ws"
  ],
  "sendgrid": {
    "key": "SG.xxx_yyyy",
    "from": "noreply@example.com",
    "templates": {
      "confirm_email": "some_template_id"
    }
  },
  "telesign": {
      "customer_id": "",
      "rest_api_key": ""
  },
  "recaptcha": {
    "site_key": "",
    "secret_key": ""
  },
  "tarantool": {
    "host": "localhost",
    "port": 3301,
    "username": "guest",
    "password": ""
  },
  "mixpanel": "",
  "img_proxy_prefix": "",
  "ipfs_prefix": "",
  "disable_signups": false,
  "read_only_mode": false,
  "uploadImage": "https://..."
}

**Comment by roadscape** [comment]
`signing_key` is for the faucet account. current min registration fee is `30.000 STEEM`. 

Please join #dev channel on steemit.chat for support chat
