### ISSUE TITLE
SBD in converstion will complete 3 months ago?

### ISSUE THREAD

**Issue by kurtr** [steemit/steemit.com#924]
I have absolutley no idea what is going on here. I think my wallet is drunk. I noticed this over a month ago and then forgot about it again until now. It's in the title attribute. 

https://steemit.com/@kurtrohlandt/transfers

![untitled](https://cloud.githubusercontent.com/assets/1468721/21560073/22c67b56-ce61-11e6-9f5d-00d66c09a043.png)

**Comment by pfunks** [comment]
Same issue as #896

**Comment by roadscape** [comment]
> Same issue as #896

Yep, fix is pending in #899
