### ISSUE TITLE
User Reported Issue - Disappearing Posts from New Page

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#925]
A user is reporting that their post is not showing up when they view the "new" page. I had them scroll down to where it should have appeared in the list and had them take a screen shot. Their post is not in the position where it is on my new page.

Here is a screen shot from my computer showing the post that is missing (see arrow)
![image](https://cloud.githubusercontent.com/assets/20735105/21560288/1ac8d488-ce22-11e6-8bb7-a5c3c29a90cc.png)

Here is a screen shot from his their. The posts above the arrow (that are there on my computer) are missing:
![image](https://cloud.githubusercontent.com/assets/20735105/21560297/42bcd87c-ce22-11e6-9413-8564da0e5bea.png)

I had him take another screen shot around the same post .

![image](https://cloud.githubusercontent.com/assets/20735105/21560347/42c12c6e-ce23-11e6-9a29-d78f136167e7.png)

**Comment by roadscape** [comment]
On the `/created` page, the post ordering should always be the same. Here you posted 3 screenshots, each with an entirely different set of posts preceding "Italian Bank Run". In the last screenshot I see that the dates jump from "32 minutes ago" to "2 hours ago". So clearly something is missing client-side.

Never seen this before. Is it reproducible?

**Comment by TimCliff** [comment]
I was baffled by it as well. Until he sent me the screen shots, I didn't think it was possible for different sets of posts to be returned. He says it happens frequently.

**Comment by valzav** [comment]
There is not enough evidence, please keep an eye on it. Feel free to reopen this issue if it happens again.
