### ISSUE TITLE
Support - Using email & Phone Number to reset account?

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steemit.com#930]
> Hi I tried to sign up and just as I was trying to copy my password to back it up....my phone died. I know I can't recover the PW but is there anyway I can reset the account using same email and phone number please? Thanks Julie

**Comment by RenaudGagne** [comment]
Can someone answer please?

**Comment by valzav** [comment]
This can lead to the faucet's abuse. Current Steemit's policy is one account per phone/email.
