### ISSUE TITLE
Proposed Changes to Flagging

### ISSUE THREAD

**Issue by TimCliff** [steemit/steemit.com#932]
There is a lot of discussion about the appropriate use of the flag/downvote. 

Examples:
https://steemit.com/voting/@sigmajin/the-dwin-fallacy-in-defense-of-the-flag-part-ii
https://steemit.com/steem/@bitcoindoom/why-down-votes-and-flags-are-an-unavoidable-consequence-of-game-theory

Some feel that it should only be used to combat defined abuse (plagiarism, spam, etc.), while others see it as a means to deal with overvalued posts by lowering the rewards. With the current implementation - getting 'flagged' is usually interpreted by the person receiving the flag as an attack, or indication that they did something wrong.

The current pop-up for flagging enforces this belief:
![image](https://cloud.githubusercontent.com/assets/20735105/21583315/829faad4-d041-11e6-865b-353882712d6b.png)

There is a discussion in issue https://github.com/steemit/steemit.com/issues/215 over larger changes to the flagging / downvote framework. I support this discussion and the direction that is going, but I understand those changes may take quite a bit of time before they are implemented.

In the meantime I propose three simple changes that could be implemented to better support 'subjective flagging':
1. Rename "Flag" to back to "Downvote"
2. Add an item to the list of acceptable downvoting reasons: "The payout is too high (subjective)"
3. In the downvote popup, add "It is recommended that as a courtesy to the author of the post/comment that you are downvoting, you reply with a comment to let them know the reason you downvoted."

If there is support for these changes, I can work on a pull request for them.

**Comment by thecryptofiend** [comment]
I'm not so keen on this.  I personally think this will make things worse by making it more acceptable to flag/downvote.  Thinking in terms of human psychology I think a downvote will be seen as being just as negative.

**Comment by pfunks** [comment]
My memory is not perfect but in trying to recall the origins of the flag UI, I remember there were a growing number of newbie downvote spats on new posts. This may have been before auto-self-upvoting was a feature. The reason it is an issue is because posts on Steemit are "muted" (ie made light grey and darker grey on-hover) when the post's rshares are anywhere in the negative. 

This mostly had the intended effect of reducing revenge downvotes and wars. But as we've discussed plenty in #215 and in many chat sessions, the unintended consequences of the flag UI concept have been user confusion and muddying the purpose of Steem downvotes. "Flag" just comes with too much baggage from other websites, and the concept on Steemit does not match the concept on centralized, moderated sites. So at the very least, it's misnamed. I think @TimCliff's suggestions for changes here are great.

**Comment by thecryptofiend** [comment]
I agree that there are problems but I think human nature will lead to excessive abuse of the flag/downvote feature if we rename/reposition it.  I have seen how people get offended on Reddit via downvotes and that is without the financial incentive.  No matter how you frame it I think many people will feel aggrieved as they will see it as theft from them or a personal attack whether that is true or not.  If the community really want it then fair enough but I think right now the balance is correct.

**Comment by jcalfee** [comment]
Maybe we should just make it a bit safer just to help this avoid further debate (and time) in the future.
change:
"The flag should be used for the following" 

.. to something like:  "Some common reasons to flag are:"

Everyone makes good points .. the text should just be rather simple and politically neutral (non-opinionated) in my view..

**Comment by thecryptofiend** [comment]
@jcalfee I like your thinking on this :)

**Comment by TimCliff** [comment]
I really like the "Some common reasons to flag are" suggestion. I agree that simple + politically neutral is a good direction to go.

I do feel that we should add this to the list of common reasons though:
"The payout is too high (subjective)"
I know @thecryptofiend wants to try and prevent people from doing that (and I don't completely disagree) but people _are_ flagging for that reason.

Also, I am willing to let it go if there is strong opposition to it - but I do feel that renaming "flag" to "downvote" will make people at least a little less aggrieved. There _is_ a connotation to the word "flag", which implies that someone did something wrong / rules were broken.

**Comment by sneak** [comment]
There is not support; flagging is not broken right now and the current implementation is not an impediment to our growth objectives.

Perhaps we will revisit flagging/downvoting at some point in the future, but I'm leaning toward removing the UI for it entirely.

Debating the merits and uses of flagging on steemit.com is permissible.  Doing so in the bugtracker is not. :)
