### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by christoph3** [steemit/steemit.com#944]
My name is Christopher S Butler and my son recently changed my crypto passwords and stole my coins. I also saw what appeared to be where he has hacked the wallets of whales and stolen over 600,000 Etheriums. I cannot access my accounts but the last time I was able to get into Steemit, I saw where he had stolen about 75 steem dollars. I'm no longer able to access my account because he changed the password. Thankfully, I had most of my steem in steempower. I also had around 197 waves tokens and was supposed to have about 250 Etheriums among other misc. coins. I've turned him into the feds but they show little interest. I'm very concerned that he may have wiped some people out. I have a copy of his computer as of a few months ago on an external hard drive but I'm a technical klutz. He also got into my bank accounts and bought coins for himself without my permission. In addition, stole guns, and various other personal belongings.In addition to that, he hit a friend of mine that's 67 and a single dad of an 8 year old son living on a fixed income. He hit him for around $1400.00. Although my loss is much greater, I can make more $ but this person is living on a fixed income. As far as the other victims, God only knows. He stole his brothers car and wrecked it. He was charged with DUI and has been in jail since early December. I am filing charges as he has hit me for thousands of dollars and I'm fed up with his criminal activity. My biggest concern is returning the coins to the rightful owners  but I'm at a loss as to what to do. He had his laptop with him and now it is with his personal belongings at the Dallas Police Department. The crypto world is a mind scramble and the authorities have showed little or no interest pursuing that arena. Any suggestions on how I should proceed? Again, my biggest fear is the other victims. If I'm right about the stolen Ethers, that adds up to several million dollars. I saw 2 wallets he had. One had over 500,000 Ether's the other 100,000. It's possible he just made it appear that way but the 500,000 I saw was by accident and complete surprise to him. The 100,000 was a "mistake", according to him as he was supposed to send me 100 that he owed me. I'm pretty sure he has been trading under my accounts since I kicked him out. He had an icon on his desktop with my entire computer on it. Passwords and all. Whe I would tell him to remove it he would ignore me. After I figured out he was running a scam on me and others, I made him move out. He was only supposed to be here for a couple of weeks but that turned into seven months and several thousand dollars. Please advise, I want to do the right thing  but I need help. Thank you. You may email me at chrisbutleradj@hotmail.com or I can be reached by phone at 972 998 7592. Again, thanks. Christopher S Butler

**Comment by TimCliff** [comment]
The issue tracker is for bugs and specific implementation discussion.  It is not a support form, and should not be used to discuss issues outside the scope of Steemit development.

If you son has hacked your Steemit account, there is a password recovery feature built into the blockchain. As long as you still have your password from before you son stole the account, you can recover it here:
(substitute your username in place of "youraccount")
https://steemit.com/@youraccount/password

If you no longer have your password, then nothing can be done to recover the account. Any funds that have already been transferred out of the account can not be recovered either.

**Comment by christoph3** [comment]
Thanks

**Comment by TimCliff** [comment]
Welcome. Good luck resolving your issue.

**Comment by christoph3** [comment]
When I try it says my account wasn't changed. It wasn't because it's still under christoph3. then I can't even open a new account because my only phone # is already used.


Thanks for your helpcb


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by christoph3** [comment]
No, I tried a few times and he must have also changed the private keys. I've tried to just open a new account but my phone number is already used and it won't let me use it again.


It's only a couple of hundred bucks but it was a long term hold.


I have a copy of his computer on an external hard drive but he's changed the passwords since I got it. However, there's enough criminal evidence on it that I think his computer could be taken by subpoena as  it is in with his personal belongings at the Dallas county Jail.


I've finally convinced local investigators to go through the hard drive.


There were two wallets I saw that he had. One of them had over 500,000 Etheriums in it and the other had 100,000 Etheriums.


One night he slipped up and commented that he was surprised he didn't get caught stealing the 100,000 coins. I acted like it went over my head. I really need to find the rightful owners of those coins. My fear is that he may have wiped someone out.


The 100,000 was mid week at night around September. The 500,000 was on a Saturday afternoon around June or July. I walked in my office and caught him off guard. When I saw what  was in the wallet I said, " Ryan, that's over $6,000,000.00. He said, " Yea, you just happened to see a fat payday". At the time I though it was legit but after the comment about stealing the 100,000 I knew he had been hacking other peoples wallets.


He also scammed a friend of mine and my friend told me that one night at his house Ryan told him, " this is how you hack into a whales wallet". My friend is just as lost on this stuff as I am and he said he had no idea what he was actually doing. He was so fast on the computer we just stayed lost.


I can make more money, but again, my concern is the victims of the millions of dollars. I hated to turn my own son in but it was the right thing to do. He needs to be stopped.


I just hope the police can figure it out because this stuff turns my brain to spaghetti.


I'll keep you posted and I'm open to anyone's assistance or input because I'm completely out of my realm dealing with this stuff.


Thanks. cb




Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by TimCliff** [comment]
This really isn't the place for this discussion. @sneak - do you want to close this?

@christoph3 - If you need further assistance regarding your Steemit account, please create an account for https://steemit.chat/ . There is a "help" channel there, although it is intended to be a help channel **specifically for Steemit related support**. Your larger issue (everything that does not directly involve Steemit) is something that would be better discussed in a different chat channel.

**Comment by christoph3** [comment]
Thanks Tim,


Steemit had sent me this link so I went with it. This whole crypto thing fry's my brain but I do have much more faith in it than the dollar!


Again, thank you.


cb


Sent from Outlook<http://aka.ms/weboutlook>


________________________________
