### ISSUE TITLE
Clicking on persons website link

### ISSUE THREAD

**Issue by Tadasu85** [steemit/steemit.com#945]
This should open a new tab with _blank not override the steemit.com tab and fill with the link. Are you guys literally trying to drive people away?

**Comment by mcifani** [comment]
We are currently not utilizing _blank on certain hyperlinks for vulnerability and privacy precautions.  If you'd like to read more on the issues: https://dev.to/ben/the-targetblank-vulnerability-by-example.  Thanks for your suggestion, closing the ticket.
