### ISSUE TITLE
User unable to register - Do Steemit Block Yandex emails address?

### ISSUE THREAD

**Issue by RenaudGagne** [steemit/steemit.com#946]
A user came to me via facebook having issues being able to register an account. He keeps receiving the following error:
> Sorry, we are unable to register your account at this time, please try again later.

Is it an issue with Yandex or phone numbers from Russia?

**Comment by valzav** [comment]
Currently we are blocking Ukrainian phone numbers due to the faucet's abuse. Will allow them later after the next release.
