### ISSUE TITLE
Account creation/phone verification is broken

### ISSUE THREAD

**Issue by kanatzidis** [steemit/steemit.com#959]
I am unable to verify my phone number while creating an account. After entering my phone number (correctly, in the format specified `xxx-xxx-xxxx`) it tells me "Unable to verify your phone number. Please try a different phone number."

I have tried two valid phone numbers, in both Brave and Chrome. What's going on?

**Comment by jcalfee** [comment]
SMS seems to be working.  Please send your number to Contact Steemit <contact@steemit.com> so we can look into it.
