### ISSUE TITLE
Latest update of the website isn't handling timezone changes gracefully.

### ISSUE THREAD

**Issue by willbanks** [steemit/steemit.com#96]
I'm traveling and cross timezones regularly, this only started in the last 24hrs, it was a never an issue before, however the site has become unusable unless I clear cache and log back in.  That's not an acceptable solution.  Might be better to get a system clock and calculate offset from GMT if nessecary rather than trying to use some tz stuff that could change randomly on you if folks are traveling.  Doubt I'm and edge case either.  If people have to correct for clock skew due to the TZ having or not DST in reality vs whatever the browser devs decided would be a good source for tz data.

app.975defc….js:27 RangeError: Unsupported time zone specified undefined(…)(anonymous function) @ app.975defc….js:27
app.975defc….js:1 Uncaught TypeError: Cannot read property '__reactInternalInstance$2mxwhkpzcbm760ycc8zrt9ms4i' of null

**Comment by jcalfee** [comment]
Is this still an issue?

**Comment by roadscape** [comment]
I haven't seen any reports of this in the last 6 weeks, doesn't seem to be an issue
