### ISSUE TITLE
In the tag list, the payouts for a specific tag seem to be wrong

### ISSUE THREAD

**Issue by dragosroua** [steemit/steemit.com#975]
I followed the tag #challenge30 for 10 days and it went up to 12.612 SBD yesterday. When I checked again today, the total number of SBD for that tag was 1127. The number of posts and comments seems to be correct, so there must be either an inconsistence in the way the price in SBD is calculated or a profound and undeniable manifestation of ignorance from my part, which I am ready to assume, if you point me to the right sources of information. Attached are the two screenshots.

<img width="1440" alt="screen shot 2017-01-10 at 7 14 17 am" src="https://cloud.githubusercontent.com/assets/1648447/21836985/8fb922da-d7d1-11e6-938d-28b94809fbc3.png">
<img width="1440" alt="screen shot 2017-01-11 at 7 31 56 am" src="https://cloud.githubusercontent.com/assets/1648447/21836986/8fe283dc-d7d1-11e6-8411-d438e1571364.png">

Thank you!

**Comment by roadscape** [comment]
I believe this was due to this issue: https://github.com/steemit/steem/issues/751

Our nodes have been updated so the total payout calcs should now be correct.
